package abmaterial.ab.com;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.debug.*;

public class abmshared extends Object{
public static abmshared mostCurrent = new abmshared();

public static BA ba;
static {
		ba = new  anywheresoftware.b4a.StandardBA("abmaterial.ab.com", "abmaterial.ab.com.abmshared", null);
		ba.loadHtSubs(abmshared.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "abmaterial.ab.com.abmshared", ba);
		}
	}
    public static Class<?> getObject() {
		return abmshared.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static com.ab.abmaterial.ABMTheme _mytheme = null;
public static com.ab.abmaterial.ABMaterial _abm = null;
public static boolean _needsauthorization = false;
public static String _appversion = "";
public static String _apppublishedstarturl = "";
public static String _appname = "";
public static String _trackingid = "";
public static anywheresoftware.b4a.objects.collections.Map _cachedpages = null;
public static int _cachescavengeperiodseconds = 0;
public static int _sessionmaxinactiveintervalseconds = 0;
public static b4j.example.dateutils _dateutils = null;
public static abmaterial.ab.com.main _main = null;
public static abmaterial.ab.com.abmprint _abmprint = null;
public static com.ab.abmaterial.ABMCodeLabel  _buildcodeblock(com.ab.abmaterial.ABMPage _page,String _id,anywheresoftware.b4a.keywords.StringBuilderWrapper _code) throws Exception{
com.ab.abmaterial.ABMCodeLabel _codelab = null;
 //BA.debugLineNum = 592;BA.debugLine="public Sub BuildCodeBlock(page As ABMPage, id As S";
 //BA.debugLineNum = 593;BA.debugLine="Dim codelab As ABMCodeLabel";
_codelab = new com.ab.abmaterial.ABMCodeLabel();
 //BA.debugLineNum = 594;BA.debugLine="codelab.Initialize(page, id, code.ToString, \"vb\")";
_codelab.Initialize(_page,_id,_code.ToString(),"vb");
 //BA.debugLineNum = 595;BA.debugLine="Return codelab";
if (true) return _codelab;
 //BA.debugLineNum = 596;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMCodeLabel  _buildcodeblockfromsmartstring(com.ab.abmaterial.ABMPage _page,String _id,String _code) throws Exception{
com.ab.abmaterial.ABMCodeLabel _codelab = null;
 //BA.debugLineNum = 598;BA.debugLine="public Sub BuildCodeBlockFromSmartString(page As A";
 //BA.debugLineNum = 599;BA.debugLine="Dim codelab As ABMCodeLabel";
_codelab = new com.ab.abmaterial.ABMCodeLabel();
 //BA.debugLineNum = 600;BA.debugLine="codelab.Initialize(page, id, code, \"vb\")";
_codelab.Initialize(_page,_id,_code,"vb");
 //BA.debugLineNum = 601;BA.debugLine="Return codelab";
if (true) return _codelab;
 //BA.debugLineNum = 602;BA.debugLine="End Sub";
return null;
}
public static String  _buildfooter(com.ab.abmaterial.ABMPage _page) throws Exception{
 //BA.debugLineNum = 472;BA.debugLine="Sub BuildFooter(page As ABMPage)";
 //BA.debugLineNum = 473;BA.debugLine="page.Footer.AddRows(1, True, \"\").AddCellsOS(2,0,0";
_page.Footer.AddRows((int) (1),anywheresoftware.b4a.keywords.Common.True,"").AddCellsOS((int) (2),(int) (0),(int) (0),(int) (0),(int) (6),(int) (6),(int) (6),"");
 //BA.debugLineNum = 474;BA.debugLine="page.Footer.BuildGrid 'IMPORTANT once you loaded";
_page.Footer.BuildGrid();
 //BA.debugLineNum = 476;BA.debugLine="page.Footer.UseTheme(\"footertheme\")";
_page.Footer.UseTheme("footertheme");
 //BA.debugLineNum = 477;BA.debugLine="End Sub";
return "";
}
public static String  _buildfooterfixed(com.ab.abmaterial.ABMPage _page) throws Exception{
 //BA.debugLineNum = 489;BA.debugLine="Sub BuildFooterFixed(page As ABMPage)";
 //BA.debugLineNum = 490;BA.debugLine="page.isFixedFooter= True";
_page.IsFixedFooter = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 492;BA.debugLine="page.PaddingBottom = 200";
_page.PaddingBottom = (int) (200);
 //BA.debugLineNum = 494;BA.debugLine="page.Footer.AddRows(1, True, \"\").AddCellsOS(2,0,0";
_page.Footer.AddRows((int) (1),anywheresoftware.b4a.keywords.Common.True,"").AddCellsOS((int) (2),(int) (0),(int) (0),(int) (0),(int) (6),(int) (6),(int) (6),"");
 //BA.debugLineNum = 495;BA.debugLine="page.Footer.BuildGrid 'IMPORTANT once you loaded";
_page.Footer.BuildGrid();
 //BA.debugLineNum = 497;BA.debugLine="page.Footer.UseTheme(\"footertheme\")";
_page.Footer.UseTheme("footertheme");
 //BA.debugLineNum = 498;BA.debugLine="End Sub";
return "";
}
public static com.ab.abmaterial.ABMLabel  _buildheader(com.ab.abmaterial.ABMPage _page,String _id,String _text) throws Exception{
com.ab.abmaterial.ABMLabel _hdr = null;
 //BA.debugLineNum = 555;BA.debugLine="public Sub BuildHeader(page As ABMPage, id As Stri";
 //BA.debugLineNum = 556;BA.debugLine="Dim hdr As ABMLabel";
_hdr = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 557;BA.debugLine="hdr.Initialize(page, id, Text, ABM.SIZE_H5, False";
_hdr.Initialize(_page,_id,_text,_abm.SIZE_H5,anywheresoftware.b4a.keywords.Common.False,"lightblue");
 //BA.debugLineNum = 558;BA.debugLine="Return hdr";
if (true) return _hdr;
 //BA.debugLineNum = 559;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMContainer  _buildiconblock(com.ab.abmaterial.ABMPage _page,String _id,String _iconname) throws Exception{
com.ab.abmaterial.ABMContainer _cont = null;
com.ab.abmaterial.ABMLabel _lblicon = null;
com.ab.abmaterial.ABMLabel _lbliconname = null;
 //BA.debugLineNum = 613;BA.debugLine="public Sub BuildIconBlock(page As ABMPage, id As S";
 //BA.debugLineNum = 614;BA.debugLine="Dim cont As ABMContainer";
_cont = new com.ab.abmaterial.ABMContainer();
 //BA.debugLineNum = 615;BA.debugLine="cont.Initialize(page, id, \"lightblue\")";
_cont.Initialize(_page,_id,"lightblue");
 //BA.debugLineNum = 616;BA.debugLine="cont.AddRows(2,False, \"\").AddCells12(1,\"\")";
_cont.AddRows((int) (2),anywheresoftware.b4a.keywords.Common.False,"").AddCells12((int) (1),"");
 //BA.debugLineNum = 617;BA.debugLine="cont.BuildGrid ' IMPORTANT";
_cont.BuildGrid();
 //BA.debugLineNum = 622;BA.debugLine="Dim lblicon As ABMLabel";
_lblicon = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 623;BA.debugLine="lblicon.Initialize(page, id & \"icon\", \"\", ABM.SIZ";
_lblicon.Initialize(_page,_id+"icon","",_abm.SIZE_H5,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 624;BA.debugLine="lblicon.IconName = iconName";
_lblicon.IconName = _iconname;
 //BA.debugLineNum = 625;BA.debugLine="lblicon.IconSize = ABM.ICONSIZE_MEDIUM";
_lblicon.IconSize = _abm.ICONSIZE_MEDIUM;
 //BA.debugLineNum = 626;BA.debugLine="cont.Cell(1,1).AddComponent(lblicon)";
_cont.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_lblicon));
 //BA.debugLineNum = 628;BA.debugLine="Dim lbliconName As ABMLabel";
_lbliconname = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 629;BA.debugLine="lbliconName.Initialize(page, id & \"lbl\", iconName";
_lbliconname.Initialize(_page,_id+"lbl",_iconname,_abm.SIZE_SPAN,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 630;BA.debugLine="cont.Cell(2,1).AddComponent(lbliconName)";
_cont.Cell((int) (2),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbliconname));
 //BA.debugLineNum = 632;BA.debugLine="Return cont";
if (true) return _cont;
 //BA.debugLineNum = 633;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMImage  _buildimage(com.ab.abmaterial.ABMPage _page,String _id,String _image,double _opacity,String _caption) throws Exception{
com.ab.abmaterial.ABMImage _img = null;
 //BA.debugLineNum = 604;BA.debugLine="public Sub BuildImage(page As ABMPage, id As Strin";
 //BA.debugLineNum = 605;BA.debugLine="Dim img As ABMImage";
_img = new com.ab.abmaterial.ABMImage();
 //BA.debugLineNum = 606;BA.debugLine="img.Initialize(page, id, image,opacity)";
_img.Initialize(_page,_id,_image,_opacity);
 //BA.debugLineNum = 607;BA.debugLine="img.IsMaterialBoxed = True";
_img.IsMaterialBoxed = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 608;BA.debugLine="img.IsResponsive = True";
_img.IsResponsive = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 609;BA.debugLine="img.Caption = Caption";
_img.Caption = _caption;
 //BA.debugLineNum = 610;BA.debugLine="Return img";
if (true) return _img;
 //BA.debugLineNum = 611;BA.debugLine="End Sub";
return null;
}
public static String  _buildnavigationbar(com.ab.abmaterial.ABMPage _page,String _title,String _logo,String _activetopreturnname,String _activesidereturnname,String _activesidesubreturnname) throws Exception{
com.ab.abmaterial.ABMImage _sbtopimg = null;
 //BA.debugLineNum = 130;BA.debugLine="Sub BuildNavigationBar(page As ABMPage, Title As S";
 //BA.debugLineNum = 139;BA.debugLine="Dim sbtopimg As ABMImage";
_sbtopimg = new com.ab.abmaterial.ABMImage();
 //BA.debugLineNum = 140;BA.debugLine="sbtopimg.Initialize(page, \"sbtopimg\", logo, 1)";
_sbtopimg.Initialize(_page,"sbtopimg",_logo,1);
 //BA.debugLineNum = 141;BA.debugLine="sbtopimg.SetFixedSize(236, 49)";
_sbtopimg.SetFixedSize((int) (236),(int) (49));
 //BA.debugLineNum = 150;BA.debugLine="page.NavigationBar.Initialize(page, \"nav1\", ABM.S";
_page.NavigationBar().Initialize(_page,"nav1",_abm.SIDEBAR_MANUAL_HIDEMEDIUMSMALL,_title,anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,(int) (330),(int) (48),(com.ab.abmaterial.ABMComponent)(_sbtopimg),_abm.COLLAPSE_ACCORDION,"nav1theme");
 //BA.debugLineNum = 158;BA.debugLine="page.NavigationBar.TopBarDropDownConstrainWidth =";
_page.NavigationBar().TopBarDropDownConstrainWidth = anywheresoftware.b4a.keywords.Common.False;
 //BA.debugLineNum = 159;BA.debugLine="page.NavigationBar.ActiveTopReturnName = ActiveTo";
_page.NavigationBar().ActiveTopReturnName = _activetopreturnname;
 //BA.debugLineNum = 160;BA.debugLine="page.NavigationBar.ActiveSideReturnName = ActiveS";
_page.NavigationBar().ActiveSideReturnName = _activesidereturnname;
 //BA.debugLineNum = 161;BA.debugLine="page.NavigationBar.ActiveSideSubReturnName = Acti";
_page.NavigationBar().ActiveSideSubReturnName = _activesidesubreturnname;
 //BA.debugLineNum = 164;BA.debugLine="page.NavigationBar.AddTopItem(\"DUMMY\", \"DUMMY\", \"";
_page.NavigationBar().AddTopItem("DUMMY","DUMMY","","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.False));
 //BA.debugLineNum = 167;BA.debugLine="page.NavigationBar.AddSideBarItem(\"DUMMY\", \"DUMMY";
_page.NavigationBar().AddSideBarItem("DUMMY","DUMMY","","");
 //BA.debugLineNum = 170;BA.debugLine="End Sub";
return "";
}
public static com.ab.abmaterial.ABMLabel  _buildparagraph(com.ab.abmaterial.ABMPage _page,String _id,String _text) throws Exception{
com.ab.abmaterial.ABMLabel _lbl = null;
 //BA.debugLineNum = 573;BA.debugLine="public Sub BuildParagraph(page As ABMPage, id As S";
 //BA.debugLineNum = 574;BA.debugLine="Dim lbl As ABMLabel";
_lbl = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 575;BA.debugLine="lbl.Initialize(page, id, Text , ABM.SIZE_PARAGRAP";
_lbl.Initialize(_page,_id,_text,_abm.SIZE_PARAGRAPH,anywheresoftware.b4a.keywords.Common.False,"justify");
 //BA.debugLineNum = 576;BA.debugLine="Return lbl";
if (true) return _lbl;
 //BA.debugLineNum = 577;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMLabel  _buildparagraphbq(com.ab.abmaterial.ABMPage _page,String _id,String _text) throws Exception{
com.ab.abmaterial.ABMLabel _lbl = null;
 //BA.debugLineNum = 579;BA.debugLine="public Sub BuildParagraphBQ(page As ABMPage, id As";
 //BA.debugLineNum = 580;BA.debugLine="Dim lbl As ABMLabel";
_lbl = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 581;BA.debugLine="lbl.Initialize(page, id, Text , ABM.SIZE_PARAGRAP";
_lbl.Initialize(_page,_id,_text,_abm.SIZE_PARAGRAPH,anywheresoftware.b4a.keywords.Common.False,"");
 //BA.debugLineNum = 582;BA.debugLine="lbl.IsBlockQuote = True";
_lbl.IsBlockQuote = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 583;BA.debugLine="Return lbl";
if (true) return _lbl;
 //BA.debugLineNum = 584;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMTable  _buildparamtable(com.ab.abmaterial.ABMPage _page,String _id,anywheresoftware.b4a.objects.collections.List _headers,anywheresoftware.b4a.objects.collections.List _names,anywheresoftware.b4a.objects.collections.List _descriptions) throws Exception{
com.ab.abmaterial.ABMTable _tbl = null;
anywheresoftware.b4a.objects.collections.List _themes = null;
int _i = 0;
anywheresoftware.b4a.objects.collections.List _values = null;
 //BA.debugLineNum = 510;BA.debugLine="public Sub BuildParamTable(page As ABMPage, id As";
 //BA.debugLineNum = 511;BA.debugLine="Dim tbl As ABMTable";
_tbl = new com.ab.abmaterial.ABMTable();
 //BA.debugLineNum = 512;BA.debugLine="tbl.Initialize(page, id, False, False, False, \"Pa";
_tbl.Initialize(_page,_id,anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.False,"Params");
 //BA.debugLineNum = 513;BA.debugLine="tbl.IgnoreFormattingCodes = True ' build in to ig";
_tbl.IgnoreFormattingCodes = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 514;BA.debugLine="Dim themes As List";
_themes = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 516;BA.debugLine="themes.Initialize2(Array As String(\"header\",\"head";
_themes.Initialize2(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"header","header"}));
 //BA.debugLineNum = 517;BA.debugLine="tbl.SetHeaders(Headers)";
_tbl.SetHeaders(_headers);
 //BA.debugLineNum = 518;BA.debugLine="tbl.SetHeaderThemes(themes)";
_tbl.SetHeaderThemes(_themes);
 //BA.debugLineNum = 520;BA.debugLine="themes.Initialize2(Array As String(\"name\",\"descri";
_themes.Initialize2(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"name","description"}));
 //BA.debugLineNum = 522;BA.debugLine="For i = 0 To Names.Size - 1";
{
final int step9 = 1;
final int limit9 = (int) (_names.getSize()-1);
for (_i = (int) (0) ; (step9 > 0 && _i <= limit9) || (step9 < 0 && _i >= limit9); _i = ((int)(0 + _i + step9)) ) {
 //BA.debugLineNum = 523;BA.debugLine="Dim Values As List";
_values = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 524;BA.debugLine="Values.Initialize";
_values.Initialize();
 //BA.debugLineNum = 525;BA.debugLine="Values.Add( Names.Get(i))";
_values.Add(_names.Get(_i));
 //BA.debugLineNum = 526;BA.debugLine="Values.Add( Descriptions.Get(i))";
_values.Add(_descriptions.Get(_i));
 //BA.debugLineNum = 527;BA.debugLine="tbl.AddRow(\"uid\" & i, Values)";
_tbl.AddRow("uid"+BA.NumberToString(_i),_values);
 //BA.debugLineNum = 528;BA.debugLine="tbl.SetRowThemes(themes)";
_tbl.SetRowThemes(_themes);
 }
};
 //BA.debugLineNum = 530;BA.debugLine="Return tbl";
if (true) return _tbl;
 //BA.debugLineNum = 531;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMTable  _buildparamtable2(com.ab.abmaterial.ABMPage _page,String _id,anywheresoftware.b4a.objects.collections.List _headers,anywheresoftware.b4a.objects.collections.List _names,anywheresoftware.b4a.objects.collections.List _descriptions) throws Exception{
com.ab.abmaterial.ABMTable _tbl = null;
anywheresoftware.b4a.objects.collections.List _themes = null;
int _i = 0;
anywheresoftware.b4a.objects.collections.List _values = null;
 //BA.debugLineNum = 533;BA.debugLine="public Sub BuildParamTable2(page As ABMPage, id As";
 //BA.debugLineNum = 534;BA.debugLine="Dim tbl As ABMTable";
_tbl = new com.ab.abmaterial.ABMTable();
 //BA.debugLineNum = 535;BA.debugLine="tbl.Initialize(page, id, False, False, False, \"Pa";
_tbl.Initialize(_page,_id,anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.False,"Params");
 //BA.debugLineNum = 536;BA.debugLine="Dim themes As List";
_themes = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 538;BA.debugLine="themes.Initialize2(Array As String(\"header\",\"head";
_themes.Initialize2(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"header","header"}));
 //BA.debugLineNum = 539;BA.debugLine="tbl.SetHeaders(Headers)";
_tbl.SetHeaders(_headers);
 //BA.debugLineNum = 540;BA.debugLine="tbl.SetHeaderThemes(themes)";
_tbl.SetHeaderThemes(_themes);
 //BA.debugLineNum = 542;BA.debugLine="themes.Initialize2(Array As String(\"name\",\"descri";
_themes.Initialize2(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"name","description"}));
 //BA.debugLineNum = 544;BA.debugLine="For i = 0 To Names.Size - 1";
{
final int step8 = 1;
final int limit8 = (int) (_names.getSize()-1);
for (_i = (int) (0) ; (step8 > 0 && _i <= limit8) || (step8 < 0 && _i >= limit8); _i = ((int)(0 + _i + step8)) ) {
 //BA.debugLineNum = 545;BA.debugLine="Dim Values As List";
_values = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 546;BA.debugLine="Values.Initialize";
_values.Initialize();
 //BA.debugLineNum = 547;BA.debugLine="Values.Add( Names.Get(i))";
_values.Add(_names.Get(_i));
 //BA.debugLineNum = 548;BA.debugLine="Values.Add( Descriptions.Get(i))";
_values.Add(_descriptions.Get(_i));
 //BA.debugLineNum = 549;BA.debugLine="tbl.AddRow(\"uid\" & i, Values)";
_tbl.AddRow("uid"+BA.NumberToString(_i),_values);
 //BA.debugLineNum = 550;BA.debugLine="tbl.SetRowThemes(themes)";
_tbl.SetRowThemes(_themes);
 }
};
 //BA.debugLineNum = 552;BA.debugLine="Return tbl";
if (true) return _tbl;
 //BA.debugLineNum = 553;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMContainer  _buildsidebarcomponent(com.ab.abmaterial.ABMPage _page,String _id,String _image,String _title,String _subtitle) throws Exception{
com.ab.abmaterial.ABMContainer _itemcont = null;
com.ab.abmaterial.ABMContainer _subitemcont = null;
com.ab.abmaterial.ABMImage _img = null;
com.ab.abmaterial.ABMLabel _lbl1 = null;
com.ab.abmaterial.ABMLabel _lbl2 = null;
com.ab.abmaterial.ABMEditor _editor = null;
 //BA.debugLineNum = 313;BA.debugLine="Sub BuildSideBarComponent(page As ABMPage, id As S";
 //BA.debugLineNum = 314;BA.debugLine="Dim ItemCont As ABMContainer";
_itemcont = new com.ab.abmaterial.ABMContainer();
 //BA.debugLineNum = 315;BA.debugLine="ItemCont.Initialize(page, id, \"\")";
_itemcont.Initialize(_page,_id,"");
 //BA.debugLineNum = 316;BA.debugLine="ItemCont.AddRowsM(1,False,0,0, \"\").AddCellsOSMP(1";
_itemcont.AddRowsM((int) (1),anywheresoftware.b4a.keywords.Common.False,(int) (0),(int) (0),"").AddCellsOSMP((int) (1),(int) (0),(int) (0),(int) (0),(int) (3),(int) (3),(int) (3),(int) (4),(int) (0),(int) (0),(int) (0),"").AddCellsOSMP((int) (1),(int) (0),(int) (0),(int) (0),(int) (9),(int) (9),(int) (9),(int) (4),(int) (0),(int) (0),(int) (0),"");
 //BA.debugLineNum = 317;BA.debugLine="ItemCont.AddRowsM(1,False,0,0, \"\").AddCells12(1,";
_itemcont.AddRowsM((int) (1),anywheresoftware.b4a.keywords.Common.False,(int) (0),(int) (0),"").AddCells12((int) (1),"");
 //BA.debugLineNum = 318;BA.debugLine="ItemCont.BuildGrid 'IMPORTANT once you loaded the";
_itemcont.BuildGrid();
 //BA.debugLineNum = 320;BA.debugLine="Dim SubItemCont As ABMContainer";
_subitemcont = new com.ab.abmaterial.ABMContainer();
 //BA.debugLineNum = 321;BA.debugLine="SubItemCont.Initialize(page, id & \"SubItemCont\",";
_subitemcont.Initialize(_page,_id+"SubItemCont","");
 //BA.debugLineNum = 322;BA.debugLine="SubItemCont.AddRowsM(1,False, 0,0,\"\").AddCells12M";
_subitemcont.AddRowsM((int) (1),anywheresoftware.b4a.keywords.Common.False,(int) (0),(int) (0),"").AddCells12MP((int) (1),(int) (-6),(int) (0),(int) (0),(int) (0),"").AddCells12((int) (1),"");
 //BA.debugLineNum = 323;BA.debugLine="SubItemCont.BuildGrid 'IMPORTANT once you loaded";
_subitemcont.BuildGrid();
 //BA.debugLineNum = 325;BA.debugLine="ItemCont.Cell(1,2).AddComponent(SubItemCont)";
_itemcont.Cell((int) (1),(int) (2)).AddComponent((com.ab.abmaterial.ABMComponent)(_subitemcont));
 //BA.debugLineNum = 327;BA.debugLine="Dim img As ABMImage";
_img = new com.ab.abmaterial.ABMImage();
 //BA.debugLineNum = 328;BA.debugLine="img.Initialize(page, id & \"img\", image, 1)";
_img.Initialize(_page,_id+"img",_image,1);
 //BA.debugLineNum = 329;BA.debugLine="img.SetFixedSize(48,48)";
_img.SetFixedSize((int) (48),(int) (48));
 //BA.debugLineNum = 330;BA.debugLine="img.IsCircular = True";
_img.IsCircular = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 331;BA.debugLine="img.IsResponsive = True";
_img.IsResponsive = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 333;BA.debugLine="ItemCont.Cell(1,1).AddComponent(img)";
_itemcont.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_img));
 //BA.debugLineNum = 335;BA.debugLine="Dim lbl1 As ABMLabel";
_lbl1 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 336;BA.debugLine="lbl1.Initialize(page, id & \"lbl1\", Title, ABM.SIZ";
_lbl1.Initialize(_page,_id+"lbl1",_title,_abm.SIZE_H6,anywheresoftware.b4a.keywords.Common.False,"lightblue");
 //BA.debugLineNum = 337;BA.debugLine="lbl1.VerticalAlign = True";
_lbl1.VerticalAlign = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 339;BA.debugLine="SubItemCont.Cell(1,1).AddComponent(lbl1)";
_subitemcont.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl1));
 //BA.debugLineNum = 341;BA.debugLine="Dim lbl2 As ABMLabel";
_lbl2 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 342;BA.debugLine="lbl2.Initialize(page, id & \"lbl2\", Subtitle, ABM.";
_lbl2.Initialize(_page,_id+"lbl2",_subtitle,_abm.SIZE_H6,anywheresoftware.b4a.keywords.Common.False,"");
 //BA.debugLineNum = 343;BA.debugLine="lbl2.VerticalAlign = True";
_lbl2.VerticalAlign = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 345;BA.debugLine="SubItemCont.Cell(1,2).AddComponent(lbl2)";
_subitemcont.Cell((int) (1),(int) (2)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl2));
 //BA.debugLineNum = 347;BA.debugLine="Dim editor As ABMEditor";
_editor = new com.ab.abmaterial.ABMEditor();
 //BA.debugLineNum = 348;BA.debugLine="editor.Initialize(page, \"editor\", True, True, \"ed";
_editor.Initialize(_page,"editor",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"editor");
 //BA.debugLineNum = 349;BA.debugLine="ItemCont.Cell(2,1).AddComponent(editor)";
_itemcont.Cell((int) (2),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_editor));
 //BA.debugLineNum = 351;BA.debugLine="Return ItemCont";
if (true) return _itemcont;
 //BA.debugLineNum = 352;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMContainer  _buildsidebartopcomponent(com.ab.abmaterial.ABMPage _page,String _id,String _image,String _title,String _subtitle) throws Exception{
com.ab.abmaterial.ABMContainer _itemcont = null;
com.ab.abmaterial.ABMContainer _subitemcont = null;
com.ab.abmaterial.ABMImage _img = null;
com.ab.abmaterial.ABMLabel _lbl1 = null;
com.ab.abmaterial.ABMLabel _lbl2 = null;
com.ab.abmaterial.ABMChart _chart3 = null;
com.ab.abmaterial.ABMChartSerie _serie3a = null;
com.ab.abmaterial.ABMChartSerie _serie3b = null;
 //BA.debugLineNum = 354;BA.debugLine="Sub BuildSideBarTopComponent(page As ABMPage, id A";
 //BA.debugLineNum = 358;BA.debugLine="Dim ItemCont As ABMContainer";
_itemcont = new com.ab.abmaterial.ABMContainer();
 //BA.debugLineNum = 359;BA.debugLine="ItemCont.Initialize(page, id, \"\")";
_itemcont.Initialize(_page,_id,"");
 //BA.debugLineNum = 360;BA.debugLine="ItemCont.AddRowsM(1,False,0,0, \"\").AddCellsOSMP(1";
_itemcont.AddRowsM((int) (1),anywheresoftware.b4a.keywords.Common.False,(int) (0),(int) (0),"").AddCellsOSMP((int) (1),(int) (0),(int) (0),(int) (0),(int) (3),(int) (3),(int) (3),(int) (4),(int) (0),(int) (0),(int) (0),"").AddCellsOSMP((int) (1),(int) (0),(int) (0),(int) (0),(int) (9),(int) (9),(int) (9),(int) (4),(int) (0),(int) (0),(int) (0),"");
 //BA.debugLineNum = 361;BA.debugLine="ItemCont.AddRowsM(1,False,0,0, \"\").AddCellsOSMP(1";
_itemcont.AddRowsM((int) (1),anywheresoftware.b4a.keywords.Common.False,(int) (0),(int) (0),"").AddCellsOSMP((int) (1),(int) (0),(int) (0),(int) (0),(int) (12),(int) (12),(int) (12),(int) (0),(int) (0),(int) (0),(int) (0),"");
 //BA.debugLineNum = 362;BA.debugLine="ItemCont.BuildGrid 'IMPORTANT once you loaded the";
_itemcont.BuildGrid();
 //BA.debugLineNum = 364;BA.debugLine="Dim SubItemCont As ABMContainer";
_subitemcont = new com.ab.abmaterial.ABMContainer();
 //BA.debugLineNum = 365;BA.debugLine="SubItemCont.Initialize(page, id & \"SubItemCont\",";
_subitemcont.Initialize(_page,_id+"SubItemCont","");
 //BA.debugLineNum = 366;BA.debugLine="SubItemCont.AddRowsM(1,False, 0,0,\"\").AddCells12M";
_subitemcont.AddRowsM((int) (1),anywheresoftware.b4a.keywords.Common.False,(int) (0),(int) (0),"").AddCells12MP((int) (1),(int) (-6),(int) (0),(int) (0),(int) (0),"").AddCells12((int) (1),"");
 //BA.debugLineNum = 367;BA.debugLine="SubItemCont.BuildGrid 'IMPORTANT once you loaded";
_subitemcont.BuildGrid();
 //BA.debugLineNum = 369;BA.debugLine="ItemCont.Cell(1,2).AddComponent(SubItemCont)";
_itemcont.Cell((int) (1),(int) (2)).AddComponent((com.ab.abmaterial.ABMComponent)(_subitemcont));
 //BA.debugLineNum = 371;BA.debugLine="Dim img As ABMImage";
_img = new com.ab.abmaterial.ABMImage();
 //BA.debugLineNum = 372;BA.debugLine="img.Initialize(page, id & \"img\", image, 1)";
_img.Initialize(_page,_id+"img",_image,1);
 //BA.debugLineNum = 373;BA.debugLine="img.SetFixedSize(48,48)";
_img.SetFixedSize((int) (48),(int) (48));
 //BA.debugLineNum = 374;BA.debugLine="img.IsCircular = True";
_img.IsCircular = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 375;BA.debugLine="img.IsResponsive = True";
_img.IsResponsive = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 377;BA.debugLine="ItemCont.Cell(1,1).AddComponent(img)";
_itemcont.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_img));
 //BA.debugLineNum = 379;BA.debugLine="Dim lbl1 As ABMLabel";
_lbl1 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 380;BA.debugLine="lbl1.Initialize(page, id & \"lbl1\", Title, ABM.SIZ";
_lbl1.Initialize(_page,_id+"lbl1",_title,_abm.SIZE_H6,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 381;BA.debugLine="lbl1.VerticalAlign = True";
_lbl1.VerticalAlign = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 383;BA.debugLine="SubItemCont.Cell(1,1).AddComponent(lbl1)";
_subitemcont.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl1));
 //BA.debugLineNum = 385;BA.debugLine="Dim lbl2 As ABMLabel";
_lbl2 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 386;BA.debugLine="lbl2.Initialize(page, id & \"lbl2\", Subtitle, ABM.";
_lbl2.Initialize(_page,_id+"lbl2",_subtitle,_abm.SIZE_H6,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 387;BA.debugLine="lbl2.VerticalAlign = True";
_lbl2.VerticalAlign = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 389;BA.debugLine="SubItemCont.Cell(1,2).AddComponent(lbl2)";
_subitemcont.Cell((int) (1),(int) (2)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl2));
 //BA.debugLineNum = 392;BA.debugLine="Dim chart3 As ABMChart";
_chart3 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 393;BA.debugLine="chart3.Initialize(page, \"chart3\", ABM.CHART_TYPEB";
_chart3.Initialize(_page,"chart3",_abm.CHART_TYPEBAR,_abm.CHART_RATIO_GOLDENSECTION,"chartsidebar");
 //BA.debugLineNum = 395;BA.debugLine="chart3.OptionsBar.AxisYOnlyInteger=True";
_chart3.OptionsBar().AxisYOnlyInteger = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 396;BA.debugLine="chart3.OptionsBar.ChartPaddingRight=60";
_chart3.OptionsBar().ChartPaddingRight = (int) (60);
 //BA.debugLineNum = 399;BA.debugLine="chart3.AddLabels(Array As String(\"M\", \"T\", \"W\", \"";
_chart3.AddLabels(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"M","T","W","T","F","S","S"}));
 //BA.debugLineNum = 402;BA.debugLine="Dim Serie3A As ABMChartSerie";
_serie3a = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 403;BA.debugLine="Serie3A.InitializeForBar";
_serie3a.InitializeForBar();
 //BA.debugLineNum = 404;BA.debugLine="Serie3A.SetValues(Array As Int(30,50,70,80,100,14";
_serie3a.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (30),(int) (50),(int) (70),(int) (80),(int) (100),(int) (140),(int) (170)}));
 //BA.debugLineNum = 405;BA.debugLine="chart3.AddSerie(Serie3A)";
_chart3.AddSerie(_serie3a);
 //BA.debugLineNum = 407;BA.debugLine="Dim Serie3B As ABMChartSerie";
_serie3b = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 408;BA.debugLine="Serie3B.InitializeForBar";
_serie3b.InitializeForBar();
 //BA.debugLineNum = 409;BA.debugLine="Serie3B.SetValues(Array As Int(100,120,180,150,19";
_serie3b.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (100),(int) (120),(int) (180),(int) (150),(int) (190),(int) (100),(int) (70)}));
 //BA.debugLineNum = 410;BA.debugLine="chart3.AddSerie(Serie3B)";
_chart3.AddSerie(_serie3b);
 //BA.debugLineNum = 413;BA.debugLine="ItemCont.Cell(2,1).AddComponent(chart3)";
_itemcont.Cell((int) (2),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart3));
 //BA.debugLineNum = 415;BA.debugLine="Return ItemCont";
if (true) return _itemcont;
 //BA.debugLineNum = 416;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMLabel  _buildspan(com.ab.abmaterial.ABMPage _page,String _id,String _text) throws Exception{
com.ab.abmaterial.ABMLabel _lbl = null;
 //BA.debugLineNum = 586;BA.debugLine="public Sub BuildSpan(page As ABMPage, id As String";
 //BA.debugLineNum = 587;BA.debugLine="Dim lbl As ABMLabel";
_lbl = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 588;BA.debugLine="lbl.Initialize(page, id, Text , ABM.SIZE_SPAN, Fa";
_lbl.Initialize(_page,_id,_text,_abm.SIZE_SPAN,anywheresoftware.b4a.keywords.Common.False,"");
 //BA.debugLineNum = 589;BA.debugLine="Return lbl";
if (true) return _lbl;
 //BA.debugLineNum = 590;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMLabel  _buildsubheader(com.ab.abmaterial.ABMPage _page,String _id,String _text) throws Exception{
com.ab.abmaterial.ABMLabel _shdr = null;
 //BA.debugLineNum = 561;BA.debugLine="public Sub BuildSubHeader(page As ABMPage, id As S";
 //BA.debugLineNum = 562;BA.debugLine="Dim shdr As ABMLabel";
_shdr = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 563;BA.debugLine="shdr.Initialize(page, id, Text, ABM.SIZE_H5, Fals";
_shdr.Initialize(_page,_id,_text,_abm.SIZE_H5,anywheresoftware.b4a.keywords.Common.False,"");
 //BA.debugLineNum = 564;BA.debugLine="Return shdr";
if (true) return _shdr;
 //BA.debugLineNum = 565;BA.debugLine="End Sub";
return null;
}
public static com.ab.abmaterial.ABMLabel  _buildsubheader2(com.ab.abmaterial.ABMPage _page,String _id,String _text) throws Exception{
com.ab.abmaterial.ABMLabel _shdr = null;
 //BA.debugLineNum = 567;BA.debugLine="public Sub BuildSubHeader2(page As ABMPage, id As";
 //BA.debugLineNum = 568;BA.debugLine="Dim shdr As ABMLabel";
_shdr = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 569;BA.debugLine="shdr.Initialize(page, id, Text, ABM.SIZE_H6, Fals";
_shdr.Initialize(_page,_id,_text,_abm.SIZE_H6,anywheresoftware.b4a.keywords.Common.False,"");
 //BA.debugLineNum = 570;BA.debugLine="Return shdr";
if (true) return _shdr;
 //BA.debugLineNum = 571;BA.debugLine="End Sub";
return null;
}
public static String  _buildtheme(String _themename) throws Exception{
 //BA.debugLineNum = 42;BA.debugLine="Sub BuildTheme(themeName As String)";
 //BA.debugLineNum = 43;BA.debugLine="MyTheme.Initialize(themeName)";
_mytheme.Initialize(_themename);
 //BA.debugLineNum = 46;BA.debugLine="MyTheme.Page.BackColor = ABM.COLOR_BLUEGREY";
_mytheme.Page.BackColor = _abm.COLOR_BLUEGREY;
 //BA.debugLineNum = 47;BA.debugLine="MyTheme.Page.BackColorIntensity = ABM.INTENSITY_L";
_mytheme.Page.BackColorIntensity = _abm.INTENSITY_LIGHTEN5;
 //BA.debugLineNum = 50;BA.debugLine="MyTheme.AddNavigationBarTheme(\"nav1theme\")";
_mytheme.AddNavigationBarTheme("nav1theme");
 //BA.debugLineNum = 51;BA.debugLine="MyTheme.NavigationBar(\"nav1theme\").TopBarBackColo";
_mytheme.NavigationBar("nav1theme").TopBarBackColor = _abm.COLOR_LIGHTBLUE;
 //BA.debugLineNum = 54;BA.debugLine="MyTheme.AddNavigationBarTheme(\"nav2theme\")";
_mytheme.AddNavigationBarTheme("nav2theme");
 //BA.debugLineNum = 55;BA.debugLine="MyTheme.NavigationBar(\"nav2theme\").SideBarWavesEf";
_mytheme.NavigationBar("nav2theme").SideBarWavesEffect = _abm.WAVESEFFECT_NONE;
 //BA.debugLineNum = 56;BA.debugLine="MyTheme.NavigationBar(\"nav2theme\").SideBarBackCol";
_mytheme.NavigationBar("nav2theme").SideBarBackColor = _abm.COLOR_BLUEGREY;
 //BA.debugLineNum = 57;BA.debugLine="MyTheme.NavigationBar(\"nav2theme\").SideBarBackCol";
_mytheme.NavigationBar("nav2theme").SideBarBackColorIntensity = _abm.INTENSITY_LIGHTEN4;
 //BA.debugLineNum = 60;BA.debugLine="MyTheme.AddNavigationBarTheme(\"nav3theme\")";
_mytheme.AddNavigationBarTheme("nav3theme");
 //BA.debugLineNum = 61;BA.debugLine="MyTheme.NavigationBar(\"nav3theme\").SideBarWavesEf";
_mytheme.NavigationBar("nav3theme").SideBarWavesEffect = _abm.WAVESEFFECT_NONE;
 //BA.debugLineNum = 62;BA.debugLine="MyTheme.NavigationBar(\"nav3theme\").SideBarBackCol";
_mytheme.NavigationBar("nav3theme").SideBarBackColor = _abm.COLOR_LIME;
 //BA.debugLineNum = 63;BA.debugLine="MyTheme.NavigationBar(\"nav3theme\").SideBarBackCol";
_mytheme.NavigationBar("nav3theme").SideBarBackColorIntensity = _abm.INTENSITY_LIGHTEN4;
 //BA.debugLineNum = 66;BA.debugLine="MyTheme.AddNavigationBarTheme(\"nav4theme\")";
_mytheme.AddNavigationBarTheme("nav4theme");
 //BA.debugLineNum = 67;BA.debugLine="MyTheme.NavigationBar(\"nav4theme\").SideBarWavesEf";
_mytheme.NavigationBar("nav4theme").SideBarWavesEffect = _abm.WAVESEFFECT_NONE;
 //BA.debugLineNum = 68;BA.debugLine="MyTheme.NavigationBar(\"nav4theme\").SideBarBackCol";
_mytheme.NavigationBar("nav4theme").SideBarBackColor = _abm.COLOR_TEAL;
 //BA.debugLineNum = 69;BA.debugLine="MyTheme.NavigationBar(\"nav4theme\").SideBarBackCol";
_mytheme.NavigationBar("nav4theme").SideBarBackColorIntensity = _abm.INTENSITY_LIGHTEN4;
 //BA.debugLineNum = 72;BA.debugLine="MyTheme.AddContainerTheme(\"footertheme\")";
_mytheme.AddContainerTheme("footertheme");
 //BA.debugLineNum = 73;BA.debugLine="MyTheme.Container(\"footertheme\").BackColor = ABM.";
_mytheme.Container("footertheme").BackColor = _abm.COLOR_LIGHTBLUE;
 //BA.debugLineNum = 74;BA.debugLine="MyTheme.Container(\"footertheme\").BackColorIntensi";
_mytheme.Container("footertheme").BackColorIntensity = _abm.INTENSITY_DARKEN3;
 //BA.debugLineNum = 77;BA.debugLine="MyTheme.AddLabelTheme(\"whitefc\")";
_mytheme.AddLabelTheme("whitefc");
 //BA.debugLineNum = 78;BA.debugLine="MyTheme.Label(\"whitefc\").ForeColor = ABM.COLOR_WH";
_mytheme.Label("whitefc").ForeColor = _abm.COLOR_WHITE;
 //BA.debugLineNum = 81;BA.debugLine="MyTheme.AddLabelTheme(\"justify\")";
_mytheme.AddLabelTheme("justify");
 //BA.debugLineNum = 82;BA.debugLine="MyTheme.Label(\"justify\").align = ABM.TEXTALIGN_JU";
_mytheme.Label("justify").Align = _abm.TEXTALIGN_JUSTIFY;
 //BA.debugLineNum = 85;BA.debugLine="MyTheme.AddLabelTheme(\"lightblue\")";
_mytheme.AddLabelTheme("lightblue");
 //BA.debugLineNum = 86;BA.debugLine="MyTheme.Label(\"lightblue\").ForeColor = ABM.COLOR_";
_mytheme.Label("lightblue").ForeColor = _abm.COLOR_LIGHTBLUE;
 //BA.debugLineNum = 87;BA.debugLine="MyTheme.Label(\"lightblue\").ForeColorIntensity = A";
_mytheme.Label("lightblue").ForeColorIntensity = _abm.INTENSITY_DARKEN2;
 //BA.debugLineNum = 90;BA.debugLine="MyTheme.AddTableTheme(\"params\")";
_mytheme.AddTableTheme("params");
 //BA.debugLineNum = 91;BA.debugLine="MyTheme.Table(\"params\").ZDepth = ABM.ZDEPTH_2";
_mytheme.Table("params").ZDepth = _abm.ZDEPTH_2;
 //BA.debugLineNum = 92;BA.debugLine="MyTheme.Table(\"params\").AddCellTheme(\"header\")";
_mytheme.Table("params").AddCellTheme("header");
 //BA.debugLineNum = 93;BA.debugLine="MyTheme.Table(\"params\").Cell(\"header\").BackColor";
_mytheme.Table("params").Cell("header").BackColor = _abm.COLOR_BLUEGREY;
 //BA.debugLineNum = 94;BA.debugLine="MyTheme.Table(\"params\").Cell(\"header\").BackColorI";
_mytheme.Table("params").Cell("header").BackColorIntensity = _abm.INTENSITY_DARKEN2;
 //BA.debugLineNum = 95;BA.debugLine="MyTheme.Table(\"params\").Cell(\"header\").ForeColor";
_mytheme.Table("params").Cell("header").ForeColor = _abm.COLOR_WHITE;
 //BA.debugLineNum = 96;BA.debugLine="MyTheme.Table(\"params\").AddCellTheme(\"name\")";
_mytheme.Table("params").AddCellTheme("name");
 //BA.debugLineNum = 97;BA.debugLine="MyTheme.Table(\"params\").Cell(\"name\").BackColor =";
_mytheme.Table("params").Cell("name").BackColor = _abm.COLOR_BLUEGREY;
 //BA.debugLineNum = 98;BA.debugLine="MyTheme.Table(\"params\").Cell(\"name\").BackColorInt";
_mytheme.Table("params").Cell("name").BackColorIntensity = _abm.INTENSITY_LIGHTEN2;
 //BA.debugLineNum = 99;BA.debugLine="MyTheme.Table(\"params\").Cell(\"name\").VerticalAlig";
_mytheme.Table("params").Cell("name").VerticalAlign = _abm.TABLECELL_VERTICALALIGN_TOP;
 //BA.debugLineNum = 100;BA.debugLine="MyTheme.Table(\"params\").AddCellTheme(\"description";
_mytheme.Table("params").AddCellTheme("description");
 //BA.debugLineNum = 101;BA.debugLine="MyTheme.Table(\"params\").Cell(\"description\").BackC";
_mytheme.Table("params").Cell("description").BackColor = _abm.COLOR_WHITE;
 //BA.debugLineNum = 102;BA.debugLine="MyTheme.Table(\"params\").Cell(\"description\").Verti";
_mytheme.Table("params").Cell("description").VerticalAlign = _abm.TABLECELL_VERTICALALIGN_TOP;
 //BA.debugLineNum = 105;BA.debugLine="MyTheme.AddToastTheme(\"toast\")";
_mytheme.AddToastTheme("toast");
 //BA.debugLineNum = 106;BA.debugLine="MyTheme.Toast(\"toast\").Rounded = True";
_mytheme.Toast("toast").Rounded = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 107;BA.debugLine="MyTheme.Toast(\"toast\").ActionForeColor = ABM.COLO";
_mytheme.Toast("toast").ActionForeColor = _abm.COLOR_ORANGE;
 //BA.debugLineNum = 110;BA.debugLine="MyTheme.AddToastTheme(\"toastred\")";
_mytheme.AddToastTheme("toastred");
 //BA.debugLineNum = 111;BA.debugLine="MyTheme.Toast(\"toastred\").Rounded = True";
_mytheme.Toast("toastred").Rounded = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 112;BA.debugLine="MyTheme.Toast(\"toastred\").ActionForeColor = ABM.C";
_mytheme.Toast("toastred").ActionForeColor = _abm.COLOR_BLACK;
 //BA.debugLineNum = 113;BA.debugLine="MyTheme.Toast(\"toastred\").BackColor = ABM.COLOR_R";
_mytheme.Toast("toastred").BackColor = _abm.COLOR_RED;
 //BA.debugLineNum = 116;BA.debugLine="MyTheme.AddContainerTheme(\"lightblue\")";
_mytheme.AddContainerTheme("lightblue");
 //BA.debugLineNum = 117;BA.debugLine="MyTheme.Container(\"lightblue\").BackColor = ABM.CO";
_mytheme.Container("lightblue").BackColor = _abm.COLOR_LIGHTBLUE;
 //BA.debugLineNum = 118;BA.debugLine="MyTheme.Container(\"lightblue\").BackColorIntensity";
_mytheme.Container("lightblue").BackColorIntensity = _abm.INTENSITY_DARKEN2;
 //BA.debugLineNum = 120;BA.debugLine="MyTheme.AddContainerTheme(\"darkblue\")";
_mytheme.AddContainerTheme("darkblue");
 //BA.debugLineNum = 121;BA.debugLine="MyTheme.Container(\"darkblue\").BackColor = ABM.COL";
_mytheme.Container("darkblue").BackColor = _abm.COLOR_LIGHTBLUE;
 //BA.debugLineNum = 122;BA.debugLine="MyTheme.Container(\"darkblue\").BackColorIntensity";
_mytheme.Container("darkblue").BackColorIntensity = _abm.INTENSITY_DARKEN3;
 //BA.debugLineNum = 124;BA.debugLine="MyTheme.AddChartTheme(\"chartsidebar\")";
_mytheme.AddChartTheme("chartsidebar");
 //BA.debugLineNum = 125;BA.debugLine="MyTheme.Chart(\"chartsidebar\").ZDepth = ABM.ZDEPTH";
_mytheme.Chart("chartsidebar").ZDepth = _abm.ZDEPTH_2;
 //BA.debugLineNum = 126;BA.debugLine="MyTheme.Chart(\"chartsidebar\").BackColor = ABM.COL";
_mytheme.Chart("chartsidebar").BackColor = _abm.COLOR_WHITE;
 //BA.debugLineNum = 127;BA.debugLine="MyTheme.Chart(\"chartsidebar\").BackColorIntensity";
_mytheme.Chart("chartsidebar").BackColorIntensity = _abm.INTENSITY_LIGHTEN5;
 //BA.debugLineNum = 128;BA.debugLine="End Sub";
return "";
}
public static String  _connectfooter(com.ab.abmaterial.ABMPage _page) throws Exception{
com.ab.abmaterial.ABMLabel _lbl1 = null;
com.ab.abmaterial.ABMLabel _lbl2 = null;
 //BA.debugLineNum = 479;BA.debugLine="Sub ConnectFooter(page As ABMPage)";
 //BA.debugLineNum = 480;BA.debugLine="Dim lbl1 As ABMLabel";
_lbl1 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 481;BA.debugLine="lbl1.Initialize(page, \"footlbl1\", \"Blog: Alwaysbu";
_lbl1.Initialize(_page,"footlbl1","Blog: Alwaysbusy's Corner{BR}{BR}B4J by Anywhere Software{BR}Materialize CSS by students from Carnegie Mellon University",_abm.SIZE_PARAGRAPH,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 482;BA.debugLine="page.Footer.Cell(1,1).AddComponent(lbl1)";
_page.Footer.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl1));
 //BA.debugLineNum = 484;BA.debugLine="Dim lbl2 As ABMLabel";
_lbl2 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 485;BA.debugLine="lbl2.Initialize(page, \"footlbl2\", \"ABMaterial Cop";
_lbl2.Initialize(_page,"footlbl2","ABMaterial Copyright @2015-2016{BR}By Alain Bailleul{BR}{BR}Email: alain.bailleul@telenet.be",_abm.SIZE_PARAGRAPH,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 486;BA.debugLine="page.Footer.Cell(1,2).AddComponent(lbl2)";
_page.Footer.Cell((int) (1),(int) (2)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl2));
 //BA.debugLineNum = 487;BA.debugLine="End Sub";
return "";
}
public static String  _connectfooterfixed(com.ab.abmaterial.ABMPage _page) throws Exception{
com.ab.abmaterial.ABMLabel _lbl1 = null;
com.ab.abmaterial.ABMLabel _lbl2 = null;
 //BA.debugLineNum = 500;BA.debugLine="Sub ConnectFooterFixed(page As ABMPage)";
 //BA.debugLineNum = 501;BA.debugLine="Dim lbl1 As ABMLabel";
_lbl1 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 502;BA.debugLine="lbl1.Initialize(page, \"footlbl1\", \"Blog: Alwaysbu";
_lbl1.Initialize(_page,"footlbl1","Blog: Alwaysbusy's Corner{BR}{BR}B4J by Anywhere Software{BR}Materialize CSS by students from Carnegie Mellon University",_abm.SIZE_PARAGRAPH,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 503;BA.debugLine="page.Footer.Cell(1,1).AddComponent(lbl1)";
_page.Footer.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl1));
 //BA.debugLineNum = 505;BA.debugLine="Dim lbl2 As ABMLabel";
_lbl2 = new com.ab.abmaterial.ABMLabel();
 //BA.debugLineNum = 506;BA.debugLine="lbl2.Initialize(page, \"footlbl2\", \"ABMaterial Cop";
_lbl2.Initialize(_page,"footlbl2","ABMaterial Copyright @2015-2016{BR}By Alain Bailleul{BR}{BR}Email: alain.bailleul@telenet.be",_abm.SIZE_PARAGRAPH,anywheresoftware.b4a.keywords.Common.False,"whitefc");
 //BA.debugLineNum = 507;BA.debugLine="page.Footer.Cell(1,2).AddComponent(lbl2)";
_page.Footer.Cell((int) (1),(int) (2)).AddComponent((com.ab.abmaterial.ABMComponent)(_lbl2));
 //BA.debugLineNum = 508;BA.debugLine="End Sub";
return "";
}
public static String  _connectnavigationbar(com.ab.abmaterial.ABMPage _page) throws Exception{
 //BA.debugLineNum = 172;BA.debugLine="Sub ConnectNavigationBar(page As ABMPage)";
 //BA.debugLineNum = 175;BA.debugLine="page.NavigationBar.Clear";
_page.NavigationBar().Clear();
 //BA.debugLineNum = 193;BA.debugLine="page.NavigationBar.AddTopItem(\"Contact\", \"\", \"mdi";
_page.NavigationBar().AddTopItem("Contact","","mdi-action-account-circle","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.False));
 //BA.debugLineNum = 232;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 233;BA.debugLine="page.NavigationBar.AddSideBarItem(\"About\", \"About";
_page.NavigationBar().AddSideBarItem("About","About","mdi-action-dashboard","../AboutPage/abmaterial-about.html");
 //BA.debugLineNum = 234;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 235;BA.debugLine="page.NavigationBar.AddSideBarItem(\"GettingStarted";
_page.NavigationBar().AddSideBarItem("GettingStarted","Getting started","mdi-editor-insert-comment","../GettingStartedPage/abmaterial-getting-started.html");
 //BA.debugLineNum = 236;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 237;BA.debugLine="page.NavigationBar.AddSideBarItem(\"Themes\", \"Them";
_page.NavigationBar().AddSideBarItem("Themes","Themes","mdi-action-invert-colors","../ThemesPage/abmaterial-theme-color.html");
 //BA.debugLineNum = 238;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 239;BA.debugLine="page.NavigationBar.AddSideBarItem(\"Layouts\", \"Gri";
_page.NavigationBar().AddSideBarItem("Layouts","Grids","mdi-editor-border-all","../GridsPage/abmaterial-grid-layout.html");
 //BA.debugLineNum = 240;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 241;BA.debugLine="page.NavigationBar.AddSideBarItem(\"Controls\", \"Co";
_page.NavigationBar().AddSideBarItem("Controls","Controls","mdi-image-palette","");
 //BA.debugLineNum = 242;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMActionButton","ABMActionButton","","../CompActionButtonPage/abmaterial-action-button.html");
 //BA.debugLineNum = 243;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMAudioPlayer","ABMAudioPlayer (1.08)","","../CompAudioPlayerPage/abmaterial-audioplayer.html");
 //BA.debugLineNum = 244;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMBadge","ABMBadge","","../CompBadgePage/abmaterial-badge.html");
 //BA.debugLineNum = 245;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMButton","ABMButton","","../CompButtonPage/abmaterial-button.html");
 //BA.debugLineNum = 246;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMCalendar","ABMCalendar","","../CompCalendarPage/abmaterial-calendar.html");
 //BA.debugLineNum = 247;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMCanvas","ABMCanvas","","../CompCanvasPage/abmaterial-canvas.html");
 //BA.debugLineNum = 248;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMCard","ABMCard","","../CompCardPage/abmaterial-card.html");
 //BA.debugLineNum = 249;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMChart","ABMChart","","../CompChartPage/abmaterial-chart.html");
 //BA.debugLineNum = 250;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMChat","ABMChat (2.50)","","../CompChatPage/abmaterial-chat.html");
 //BA.debugLineNum = 251;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMCheckbox","ABMCheckbox","","../CompCheckboxPage/abmaterial-checkbox.html");
 //BA.debugLineNum = 252;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMChip","ABMChip","","../CompChipPage/abmaterial-chip.html");
 //BA.debugLineNum = 253;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMChronologyList","ABMChronologyList (2.00)","","../CompChronologyPage/abmaterial-chronology.html");
 //BA.debugLineNum = 254;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMCodeLabel","ABMCodeLabel","","../CompCodeLabelPage/abmaterial-code-label.html");
 //BA.debugLineNum = 255;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMCombo","ABMCombo","","../CompComboPage/abmaterial-combo.html");
 //BA.debugLineNum = 256;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMCustomComponent","ABMCustomComponent","","../CompCustomCompPage/abmaterial-custom-component.html");
 //BA.debugLineNum = 257;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMDateTimePicker","ABMDateTimePicker (1.06)","","../CompDateTimePickerPage/abmaterial-date-time-picker.html");
 //BA.debugLineNum = 258;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMDateTimeScroller","ABMDateTimeScroller (1.06)","","../CompDateTimeScrollerPage/abmaterial-date-time-scroller.html");
 //BA.debugLineNum = 259;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMDivider","ABMDivider","","../CompDividerPage/abmaterial-divider.html");
 //BA.debugLineNum = 260;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMFileInput","ABMFileInput (1.20)","","../CompFileInputPage/abmaterial-fileinput.html");
 //BA.debugLineNum = 261;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMEditor","ABMEditor (1.07)","","../CompEditorPage/abmaterial-editor.html");
 //BA.debugLineNum = 262;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMGoogleMap","ABMGoogleMap","","../CompGoogleMapPage/abmaterial-google-map.html");
 //BA.debugLineNum = 263;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMImage","ABMImage","","../CompImagePage/abmaterial-image.html");
 //BA.debugLineNum = 264;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMImageSlider","ABMImageSlider","","../CompSliderPage/abmaterial-image-slider-carousel.html");
 //BA.debugLineNum = 265;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMInput","ABMInput","","../CompInputPage/abmaterial-input.html");
 //BA.debugLineNum = 266;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMLabel","ABMLabel","","../CompLabelPage/abmaterial-label.html");
 //BA.debugLineNum = 267;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMList","ABMList","","../CompListPage/abmaterial-list.html");
 //BA.debugLineNum = 268;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMPagination","ABMPagination","","../CompPaginationPage/abmaterial-pagination.html");
 //BA.debugLineNum = 269;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMPatternLock","ABMPatternLock (1.20)","","../CompPatternLockPage/abmaterial-patternlock.html");
 //BA.debugLineNum = 270;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMPDFViewer","ABMPDFViewer (1.08)","","../CompPDFViewerPage/abmaterial-pdfviewer.html");
 //BA.debugLineNum = 271;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMPercentSlider","ABMPercentSlider (2.50)","","../CompPercentSliderPage/abmaterial-percentslider.html");
 //BA.debugLineNum = 272;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMPivotTable","ABMPivotTable (1.08)","","../CompPivotTablePage/abmaterial-pivottable.html");
 //BA.debugLineNum = 273;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMPlanner","ABMPlanner (2.50)","","../CompPlannerPage/abmaterial-planner.html");
 //BA.debugLineNum = 274;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMRadioGroup","ABMRadioGroup","","../CompRadioGroupPage/abmaterial-radio-group.html");
 //BA.debugLineNum = 275;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMRange","ABMRange","","../CompRangePage/abmaterial-range.html");
 //BA.debugLineNum = 276;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMSignaturePad","ABMSignaturePad","","../CompSignaturePage/abmaterial-signature.html");
 //BA.debugLineNum = 277;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMSlider","ABMSlider","","../CompRealSliderPage/abmaterial-slider.html");
 //BA.debugLineNum = 278;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMSocialOAuth","ABMSocialOAuth","","../CompOAuthPage/abmaterial-oauth.html");
 //BA.debugLineNum = 279;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMSocialShare","ABMSocialShare (1.07)","","../CompSocialSharePage/abmaterial-social-share.html");
 //BA.debugLineNum = 280;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMSVGSurface","ABMSVGSurface (1.20)","","../CompSVGSurfacePage/abmaterial-svgsurface.html");
 //BA.debugLineNum = 281;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMSwitch","ABMSwitch","","../CompSwitchPage/abmaterial-switch.html");
 //BA.debugLineNum = 282;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMTabs","ABMTabs","","../CompTabsPage/abmaterial-tabs.html");
 //BA.debugLineNum = 283;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMTimeLine","ABMTimeLine (1.09)","","../CompTimeLinePage/abmaterial-timeline.html");
 //BA.debugLineNum = 284;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMTreeTable","ABMTreeTable","","../CompTreeTablePage/abmaterial-tree-table.html");
 //BA.debugLineNum = 285;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMUpload","ABMUpload","","../CompUploadPage/abmaterial-file-upload.html");
 //BA.debugLineNum = 286;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Controls\",";
_page.NavigationBar().AddSideBarSubItem("Controls","ABMVideo","ABMVideo","","../CompVideoPage/abmaterial-video.html");
 //BA.debugLineNum = 288;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 289;BA.debugLine="page.NavigationBar.AddSideBarItem(\"Helpers\", \"Hel";
_page.NavigationBar().AddSideBarItem("Helpers","Helpers","mdi-device-now-widgets","");
 //BA.debugLineNum = 290;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMContainer","ABMContainer","","../HelperContainerPage/abmaterial-container.html");
 //BA.debugLineNum = 291;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMFlexWall","ABMFlexWall (1.09)","","../HelperFlexWallPage/abmaterial-flexwall.html");
 //BA.debugLineNum = 292;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMGenerator","ABMGenerator (1.07)","","../HelperGeneratorPage/abmaterial-generator.html");
 //BA.debugLineNum = 293;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMModalSheet","ABMModalSheet","","../HelperModalSheetPage/abmaterial-modal-sheet.html");
 //BA.debugLineNum = 294;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMNavigationBar","ABMNavigationBar","","../HelperNavigationBarPage/abmaterial-navigation-bar.html");
 //BA.debugLineNum = 295;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMPage","ABMPage","","../HelperPagePage/abmaterial-page.html");
 //BA.debugLineNum = 296;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMParallax","ABMParallax","","../HelperParallaxPage/abmaterial-parallax.html");
 //BA.debugLineNum = 297;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMTable","ABMTable","","../HelperTablePage/abmaterial-table.html");
 //BA.debugLineNum = 298;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Helpers\", \"";
_page.NavigationBar().AddSideBarSubItem("Helpers","ABMTableMutable","ABMTableMutable (1.20)","","../HelperTableMutablePage/abmaterial-table-mutable.html");
 //BA.debugLineNum = 299;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 300;BA.debugLine="page.NavigationBar.AddSideBarItem(\"Icons\", \"Icons";
_page.NavigationBar().AddSideBarItem("Icons","Icons","mdi-action-account-circle","../IconsPage/abmaterial-material-icons.html");
 //BA.debugLineNum = 301;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 302;BA.debugLine="page.NavigationBar.AddSideBarItem(\"Firebase\", \"Fi";
_page.NavigationBar().AddSideBarItem("Firebase","Firebase","mdi-device-gps-not-fixed","");
 //BA.debugLineNum = 303;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Firebase\",";
_page.NavigationBar().AddSideBarSubItem("Firebase","Firebase","Firebase Auth (1.20)","","../OtherFirebasePage/abmaterial-firebase.html");
 //BA.debugLineNum = 304;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Firebase\",";
_page.NavigationBar().AddSideBarSubItem("Firebase","FirebaseStor","Firebase Storage (1.20)","","../OtherFirebaseStorPage/abmaterial-firebasestorage.html");
 //BA.debugLineNum = 305;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 306;BA.debugLine="page.NavigationBar.AddSideBarItem(\"Donators\", \"Do";
_page.NavigationBar().AddSideBarItem("Donators","Donators","mdi-editor-attach-money","");
 //BA.debugLineNum = 307;BA.debugLine="page.NavigationBar.AddSideBarSubItem(\"Donators\",";
_page.NavigationBar().AddSideBarSubItem("Donators","ExtraLibs","Extra libraries","","../DonatorsExtraLibsPage/abmaterial-extralibs.html");
 //BA.debugLineNum = 308;BA.debugLine="page.NavigationBar.AddSideBarDivider(\"\")";
_page.NavigationBar().AddSideBarDivider("");
 //BA.debugLineNum = 310;BA.debugLine="page.NavigationBar.Refresh ' IMPORTANT";
_page.NavigationBar().Refresh();
 //BA.debugLineNum = 311;BA.debugLine="End Sub";
return "";
}
public static String  _date2string(long _date,boolean _withtime) throws Exception{
String _origformat = "";
String _mydate = "";
 //BA.debugLineNum = 435;BA.debugLine="Sub Date2String(date As Long, withTime As Boolean)";
 //BA.debugLineNum = 436;BA.debugLine="Dim OrigFormat As String=DateTime.DateFormat";
_origformat = anywheresoftware.b4a.keywords.Common.DateTime.getDateFormat();
 //BA.debugLineNum = 437;BA.debugLine="If withTime Then";
if (_withtime) { 
 //BA.debugLineNum = 438;BA.debugLine="DateTime.DateFormat=\"yyyy-MM-dd'T'HH:mm:ss\"";
anywheresoftware.b4a.keywords.Common.DateTime.setDateFormat("yyyy-MM-dd'T'HH:mm:ss");
 }else {
 //BA.debugLineNum = 440;BA.debugLine="DateTime.DateFormat=\"yyyy-MM-dd\"";
anywheresoftware.b4a.keywords.Common.DateTime.setDateFormat("yyyy-MM-dd");
 };
 //BA.debugLineNum = 442;BA.debugLine="Dim MyDate As String =DateTime.Date(date)";
_mydate = anywheresoftware.b4a.keywords.Common.DateTime.Date(_date);
 //BA.debugLineNum = 443;BA.debugLine="DateTime.DateFormat=OrigFormat";
anywheresoftware.b4a.keywords.Common.DateTime.setDateFormat(_origformat);
 //BA.debugLineNum = 444;BA.debugLine="Return MyDate";
if (true) return _mydate;
 //BA.debugLineNum = 445;BA.debugLine="End Sub";
return "";
}
public static String  _logoff(com.ab.abmaterial.ABMPage _page) throws Exception{
String _network = "";
String _name = "";
 //BA.debugLineNum = 418;BA.debugLine="Sub LogOff(page As ABMPage)";
 //BA.debugLineNum = 419;BA.debugLine="Dim Network As String = page.ws.Session.GetAttrib";
_network = BA.ObjectToString(_page.ws.getSession().GetAttribute("authType"));
 //BA.debugLineNum = 420;BA.debugLine="Dim Name As String = page.ws.Session.GetAttribute";
_name = BA.ObjectToString(_page.ws.getSession().GetAttribute("authName"));
 //BA.debugLineNum = 421;BA.debugLine="Select Case Network";
switch (BA.switchObjectToInt(_network,"local",_abm.SOCIALOAUTH_FACEBOOK)) {
case 0: {
 //BA.debugLineNum = 425;BA.debugLine="page.ws.Session.SetAttribute(\"authType\", \"\")";
_page.ws.getSession().SetAttribute("authType",(Object)(""));
 //BA.debugLineNum = 426;BA.debugLine="page.ws.Session.SetAttribute(\"authName\", \"\")";
_page.ws.getSession().SetAttribute("authName",(Object)(""));
 //BA.debugLineNum = 427;BA.debugLine="page.ws.Session.SetAttribute(\"IsAuthorized\", \"\"";
_page.ws.getSession().SetAttribute("IsAuthorized",(Object)(""));
 //BA.debugLineNum = 428;BA.debugLine="NavigateToPage(page.ws, page.GetPageID, \"../\")";
_navigatetopage(_page.ws,_page.GetPageID(),"../");
 break; }
case 1: {
 //BA.debugLineNum = 431;BA.debugLine="page.SignOffSocialNetwork(Network, \"\", Name)";
_page.SignOffSocialNetwork(_network,"",_name);
 break; }
}
;
 //BA.debugLineNum = 433;BA.debugLine="End Sub";
return "";
}
public static String  _mid(String _text,int _start,int _length) throws Exception{
 //BA.debugLineNum = 464;BA.debugLine="Sub Mid(Text As String, Start As Int, Length As In";
 //BA.debugLineNum = 465;BA.debugLine="Return Text.SubString2(Start-1,Start+Length-1)";
if (true) return _text.substring((int) (_start-1),(int) (_start+_length-1));
 //BA.debugLineNum = 466;BA.debugLine="End Sub";
return "";
}
public static String  _mid2(String _text,int _start) throws Exception{
 //BA.debugLineNum = 468;BA.debugLine="Sub Mid2(Text As String, Start As Int) As String";
 //BA.debugLineNum = 469;BA.debugLine="Return Text.SubString(Start-1)";
if (true) return _text.substring((int) (_start-1));
 //BA.debugLineNum = 470;BA.debugLine="End Sub";
return "";
}
public static String  _navigatetopage(anywheresoftware.b4j.object.WebSocket _ws,String _pageid,String _targeturl) throws Exception{
 //BA.debugLineNum = 18;BA.debugLine="Public Sub NavigateToPage(ws As WebSocket, PageId";
 //BA.debugLineNum = 19;BA.debugLine="If AppVersion <> \"\" Then";
if ((_appversion).equals("") == false) { 
 //BA.debugLineNum = 20;BA.debugLine="TargetUrl = TargetUrl & \"?\" & AppVersion";
_targeturl = _targeturl+"?"+_appversion;
 };
 //BA.debugLineNum = 22;BA.debugLine="ABM.RemoveMeFromCache(CachedPages, PageId)";
_abm.RemoveMeFromCache(_cachedpages,_pageid);
 //BA.debugLineNum = 23;BA.debugLine="If ws.Open Then";
if (_ws.getOpen()) { 
 //BA.debugLineNum = 24;BA.debugLine="ws.Eval(\"window.location = arguments[0]\", Array";
_ws.Eval("window.location = arguments[0]",anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)(_targeturl)}));
 //BA.debugLineNum = 25;BA.debugLine="ws.Flush";
_ws.Flush();
 };
 //BA.debugLineNum = 27;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public MyTheme As ABMTheme";
_mytheme = new com.ab.abmaterial.ABMTheme();
 //BA.debugLineNum = 4;BA.debugLine="Private ABM As ABMaterial 'ignore";
_abm = new com.ab.abmaterial.ABMaterial();
 //BA.debugLineNum = 5;BA.debugLine="Public NeedsAuthorization As Boolean = False";
_needsauthorization = anywheresoftware.b4a.keywords.Common.False;
 //BA.debugLineNum = 6;BA.debugLine="Public AppVersion As String = DateTime.Now";
_appversion = BA.NumberToString(anywheresoftware.b4a.keywords.Common.DateTime.getNow());
 //BA.debugLineNum = 7;BA.debugLine="Public AppPublishedStartURL As String = \"http://p";
_apppublishedstarturl = "http://prd.one-two.com:51042/demo/";
 //BA.debugLineNum = 8;BA.debugLine="Public AppName As String = \"demo\"";
_appname = "demo";
 //BA.debugLineNum = 11;BA.debugLine="Public TrackingID As String";
_trackingid = "";
 //BA.debugLineNum = 13;BA.debugLine="Public CachedPages As Map";
_cachedpages = new anywheresoftware.b4a.objects.collections.Map();
 //BA.debugLineNum = 14;BA.debugLine="Public CacheScavengePeriodSeconds As Int = 15*60";
_cachescavengeperiodseconds = (int) (15*60);
 //BA.debugLineNum = 15;BA.debugLine="Public SessionMaxInactiveIntervalSeconds As Int =";
_sessionmaxinactiveintervalseconds = (int) (30*60);
 //BA.debugLineNum = 16;BA.debugLine="End Sub";
return "";
}
public static String  _redirectoutput(String _dir,String _filename) throws Exception{
anywheresoftware.b4a.objects.streams.File.OutputStreamWrapper _out = null;
anywheresoftware.b4j.object.JavaObject _ps = null;
anywheresoftware.b4j.object.JavaObject _jo = null;
 //BA.debugLineNum = 29;BA.debugLine="Sub RedirectOutput (Dir As String, FileName As Str";
 //BA.debugLineNum = 31;BA.debugLine="Dim out As OutputStream = File.OpenOutput(Dir,";
_out = new anywheresoftware.b4a.objects.streams.File.OutputStreamWrapper();
_out = anywheresoftware.b4a.keywords.Common.File.OpenOutput(_dir,_filename,anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 32;BA.debugLine="Dim ps As JavaObject";
_ps = new anywheresoftware.b4j.object.JavaObject();
 //BA.debugLineNum = 33;BA.debugLine="ps.InitializeNewInstance(\"java.io.PrintStream\",";
_ps.InitializeNewInstance("java.io.PrintStream",new Object[]{(Object)(_out.getObject()),(Object)(anywheresoftware.b4a.keywords.Common.True),(Object)("utf8")});
 //BA.debugLineNum = 34;BA.debugLine="Dim jo As JavaObject";
_jo = new anywheresoftware.b4j.object.JavaObject();
 //BA.debugLineNum = 35;BA.debugLine="jo.InitializeStatic(\"java.lang.System\")";
_jo.InitializeStatic("java.lang.System");
 //BA.debugLineNum = 36;BA.debugLine="jo.RunMethod(\"setOut\", Array(ps))";
_jo.RunMethod("setOut",new Object[]{(Object)(_ps.getObject())});
 //BA.debugLineNum = 37;BA.debugLine="jo.RunMethod(\"setErr\", Array(ps))";
_jo.RunMethod("setErr",new Object[]{(Object)(_ps.getObject())});
 //BA.debugLineNum = 39;BA.debugLine="End Sub";
return "";
}
public static long  _string2date(String _date) throws Exception{
long _lng = 0L;
String _origformat = "";
String _d = "";
String _t = "";
 //BA.debugLineNum = 447;BA.debugLine="Sub String2Date(date As String) As Long";
 //BA.debugLineNum = 448;BA.debugLine="Dim lng As Long";
_lng = 0L;
 //BA.debugLineNum = 449;BA.debugLine="Dim OrigFormat As String=DateTime.DateFormat";
_origformat = anywheresoftware.b4a.keywords.Common.DateTime.getDateFormat();
 //BA.debugLineNum = 450;BA.debugLine="If date.Length > 10 Then";
if (_date.length()>10) { 
 //BA.debugLineNum = 451;BA.debugLine="DateTime.DateFormat = \"yyyy-MM-dd\"";
anywheresoftware.b4a.keywords.Common.DateTime.setDateFormat("yyyy-MM-dd");
 //BA.debugLineNum = 452;BA.debugLine="DateTime.DateFormat = \"HH:mm:ss\"";
anywheresoftware.b4a.keywords.Common.DateTime.setDateFormat("HH:mm:ss");
 //BA.debugLineNum = 453;BA.debugLine="Dim d As String = date.SubString2(0,11)";
_d = _date.substring((int) (0),(int) (11));
 //BA.debugLineNum = 454;BA.debugLine="Dim t As String = date.SubString(12)";
_t = _date.substring((int) (12));
 //BA.debugLineNum = 455;BA.debugLine="lng = DateTime.DateTimeParse(d,t)";
_lng = anywheresoftware.b4a.keywords.Common.DateTime.DateTimeParse(_d,_t);
 }else {
 //BA.debugLineNum = 457;BA.debugLine="DateTime.DateFormat = \"yyyy-MM-dd\"";
anywheresoftware.b4a.keywords.Common.DateTime.setDateFormat("yyyy-MM-dd");
 //BA.debugLineNum = 458;BA.debugLine="lng = DateTime.Dateparse(date)";
_lng = anywheresoftware.b4a.keywords.Common.DateTime.DateParse(_date);
 };
 //BA.debugLineNum = 460;BA.debugLine="DateTime.DateFormat=OrigFormat";
anywheresoftware.b4a.keywords.Common.DateTime.setDateFormat(_origformat);
 //BA.debugLineNum = 461;BA.debugLine="Return lng";
if (true) return _lng;
 //BA.debugLineNum = 462;BA.debugLine="End Sub";
return 0L;
}
}
