package abmaterial.ab.com;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.B4AClass;
import anywheresoftware.b4a.debug.*;

public class compcanvaspage extends B4AClass.ImplB4AClass implements BA.SubDelegator{
    public static java.util.HashMap<String, java.lang.reflect.Method> htSubs;
    private void innerInitialize(BA _ba) throws Exception {
        if (ba == null) {
            ba = new  anywheresoftware.b4a.StandardBA("abmaterial.ab.com", "abmaterial.ab.com.compcanvaspage", this);
            if (htSubs == null) {
                ba.loadHtSubs(this.getClass());
                htSubs = ba.htSubs;
            }
            ba.htSubs = htSubs;
             
        }
        if (BA.isShellModeRuntimeCheck(ba))
                this.getClass().getMethod("_class_globals", abmaterial.ab.com.compcanvaspage.class).invoke(this, new Object[] {null});
        else
            ba.raiseEvent2(null, true, "class_globals", false);
    }

 public anywheresoftware.b4a.keywords.Common __c = null;
public anywheresoftware.b4j.object.WebSocket _ws = null;
public com.ab.abmaterial.ABMPage _page = null;
public com.ab.abmaterial.ABMTheme _theme = null;
public com.ab.abmaterial.ABMaterial _abm = null;
public String _name = "";
public String _abmpageid = "";
public int _mytoastid = 0;
public int _kyleteller = 0;
public b4j.example.dateutils _dateutils = null;
public abmaterial.ab.com.main _main = null;
public abmaterial.ab.com.abmshared _abmshared = null;
public abmaterial.ab.com.abmprint _abmprint = null;
public String  _btn_clicked(String _target) throws Exception{
com.ab.abmaterial.ABMCanvas _canvas1 = null;
com.ab.abmaterial.ABMCanvasObject _kyle = null;
int _x = 0;
int _y = 0;
 //BA.debugLineNum = 430;BA.debugLine="Sub btn_Clicked(Target As String)";
 //BA.debugLineNum = 431;BA.debugLine="Dim canvas1 As ABMCanvas = page.Component(\"canvas";
_canvas1 = (com.ab.abmaterial.ABMCanvas)(_page.Component("canvas1"));
 //BA.debugLineNum = 432;BA.debugLine="Dim Kyle As ABMCanvasObject";
_kyle = new com.ab.abmaterial.ABMCanvasObject();
 //BA.debugLineNum = 433;BA.debugLine="Dim x As Int = Rnd(0,1024-109)";
_x = __c.Rnd((int) (0),(int) (1024-109));
 //BA.debugLineNum = 434;BA.debugLine="Dim y As Int = Rnd(0,569-136)";
_y = __c.Rnd((int) (0),(int) (569-136));
 //BA.debugLineNum = 435;BA.debugLine="kyleTeller=kyleTeller+1";
_kyleteller = (int) (_kyleteller+1);
 //BA.debugLineNum = 436;BA.debugLine="Kyle.InitializeAsRectangle(page, \"kyle\" & kyleTel";
_kyle.InitializeAsRectangle(_page,"kyle"+BA.NumberToString(_kyleteller),_x,_y,(int) (109),(int) (136),__c.True);
 //BA.debugLineNum = 437;BA.debugLine="Kyle.drawImage(\"kyle\", 0,0)";
_kyle.drawImage("kyle",0,0);
 //BA.debugLineNum = 438;BA.debugLine="canvas1.AddObject(Kyle)";
_canvas1.AddObject(_kyle);
 //BA.debugLineNum = 439;BA.debugLine="canvas1.refresh ' IMPORTANT";
_canvas1.Refresh();
 //BA.debugLineNum = 440;BA.debugLine="End Sub";
return "";
}
public com.ab.abmaterial.ABMCanvasObject  _buildclock() throws Exception{
com.ab.abmaterial.ABMCanvasObject _clock = null;
double _radius = 0;
double _ang = 0;
int _num = 0;
double _hour = 0;
double _minute = 0;
double _second = 0;
 //BA.debugLineNum = 475;BA.debugLine="Sub BuildClock() As ABMCanvasObject";
 //BA.debugLineNum = 476;BA.debugLine="Dim clock As ABMCanvasObject";
_clock = new com.ab.abmaterial.ABMCanvasObject();
 //BA.debugLineNum = 477;BA.debugLine="Dim Radius As Double = 150";
_radius = 150;
 //BA.debugLineNum = 479;BA.debugLine="clock.InitializeAsRectangle(page, \"clock\", 0,0,30";
_clock.InitializeAsRectangle(_page,"clock",(int) (0),(int) (0),(int) (300),(int) (300),__c.True);
 //BA.debugLineNum = 481;BA.debugLine="Radius = Radius * 0.9";
_radius = _radius*0.9;
 //BA.debugLineNum = 484;BA.debugLine="clock.translate(150,150)";
_clock.translate(150,150);
 //BA.debugLineNum = 485;BA.debugLine="clock.beginPath";
_clock.beginPath();
 //BA.debugLineNum = 486;BA.debugLine="clock.arc(0,0,Radius, 0, 2*cPI)";
_clock.arc(0,0,_radius,0,2*__c.cPI);
 //BA.debugLineNum = 487;BA.debugLine="clock.fillStyleColor(\"#FFFFFF\")";
_clock.fillStyleColor("#FFFFFF");
 //BA.debugLineNum = 488;BA.debugLine="clock.fill";
_clock.fill();
 //BA.debugLineNum = 489;BA.debugLine="clock.strokeStyleRadialGradient(0,0,Radius*0.95,0";
_clock.strokeStyleRadialGradient(0,0,_radius*0.95,0,0,_radius*1.05,anywheresoftware.b4a.keywords.Common.ArrayToList(new double[]{0,0.5,1}),anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"#333","white","#333"}));
 //BA.debugLineNum = 490;BA.debugLine="clock.lineWidth(Radius*0.1)";
_clock.lineWidth(_radius*0.1);
 //BA.debugLineNum = 491;BA.debugLine="clock.stroke()";
_clock.stroke();
 //BA.debugLineNum = 493;BA.debugLine="clock.beginPath";
_clock.beginPath();
 //BA.debugLineNum = 494;BA.debugLine="clock.arc(0, 0, Radius*0.1, 0, 2*cPI)";
_clock.arc(0,0,_radius*0.1,0,2*__c.cPI);
 //BA.debugLineNum = 495;BA.debugLine="clock.fillStyleColor(\"#333\")";
_clock.fillStyleColor("#333");
 //BA.debugLineNum = 496;BA.debugLine="clock.fill";
_clock.fill();
 //BA.debugLineNum = 499;BA.debugLine="clock.font(\"arial\", Radius*0.15)";
_clock.font("arial",(int) (_radius*0.15));
 //BA.debugLineNum = 500;BA.debugLine="clock.textBaseline(ABM.CANVAS_TEXTBASELINE_MID";
_clock.textBaseline(_abm.CANVAS_TEXTBASELINE_MIDDLE);
 //BA.debugLineNum = 501;BA.debugLine="clock.textAlign(ABM.CANVAS_TEXTALIGN_CENTER)";
_clock.textAlign(_abm.CANVAS_TEXTALIGN_CENTER);
 //BA.debugLineNum = 502;BA.debugLine="Dim ang As Double";
_ang = 0;
 //BA.debugLineNum = 503;BA.debugLine="For num = 1 To 12";
{
final int step21 = 1;
final int limit21 = (int) (12);
for (_num = (int) (1) ; (step21 > 0 && _num <= limit21) || (step21 < 0 && _num >= limit21); _num = ((int)(0 + _num + step21)) ) {
 //BA.debugLineNum = 504;BA.debugLine="ang = num * cPI / 6";
_ang = _num*__c.cPI/(double)6;
 //BA.debugLineNum = 505;BA.debugLine="clock.rotate(ang)";
_clock.rotate(_ang);
 //BA.debugLineNum = 506;BA.debugLine="clock.translate(0, -Radius*0.85)";
_clock.translate(0,-_radius*0.85);
 //BA.debugLineNum = 507;BA.debugLine="clock.rotate(-ang)";
_clock.rotate(-_ang);
 //BA.debugLineNum = 508;BA.debugLine="clock.fillText(\"\" & num, 0, 0)";
_clock.fillText(""+BA.NumberToString(_num),0,0);
 //BA.debugLineNum = 509;BA.debugLine="clock.rotate(ang)";
_clock.rotate(_ang);
 //BA.debugLineNum = 510;BA.debugLine="clock.translate(0, Radius*0.85)";
_clock.translate(0,_radius*0.85);
 //BA.debugLineNum = 511;BA.debugLine="clock.rotate(-ang)";
_clock.rotate(-_ang);
 }
};
 //BA.debugLineNum = 515;BA.debugLine="Dim hour As Double = DateTime.GetHour(DateTime.No";
_hour = __c.DateTime.GetHour(__c.DateTime.getNow());
 //BA.debugLineNum = 516;BA.debugLine="Dim minute As Double = DateTime.GetMinute(DateTim";
_minute = __c.DateTime.GetMinute(__c.DateTime.getNow());
 //BA.debugLineNum = 517;BA.debugLine="Dim second As Double = DateTime.GetSecond(DateTim";
_second = __c.DateTime.GetSecond(__c.DateTime.getNow());
 //BA.debugLineNum = 518;BA.debugLine="hour = hour Mod 12";
_hour = _hour%12;
 //BA.debugLineNum = 519;BA.debugLine="hour = (hour*cPI/6)+(minute*cPI/(6*60))+(second*c";
_hour = (_hour*__c.cPI/(double)6)+(_minute*__c.cPI/(double)(6*60))+(_second*__c.cPI/(double)(360*60));
 //BA.debugLineNum = 520;BA.debugLine="BuildHand(clock, hour, Radius*0.5, Radius*0.07)";
_buildhand(_clock,(int) (_hour),_radius*0.5,_radius*0.07);
 //BA.debugLineNum = 521;BA.debugLine="minute=(minute*cPI/30)+(second*cPI/(30*60))";
_minute = (_minute*__c.cPI/(double)30)+(_second*__c.cPI/(double)(30*60));
 //BA.debugLineNum = 522;BA.debugLine="BuildHand(clock, minute, Radius*0.8, Radius*0.07)";
_buildhand(_clock,(int) (_minute),_radius*0.8,_radius*0.07);
 //BA.debugLineNum = 523;BA.debugLine="second=(second*cPI/30)";
_second = (_second*__c.cPI/(double)30);
 //BA.debugLineNum = 524;BA.debugLine="BuildHand(clock, second, Radius*0.9, Radius*0.02)";
_buildhand(_clock,(int) (_second),_radius*0.9,_radius*0.02);
 //BA.debugLineNum = 526;BA.debugLine="Return clock";
if (true) return _clock;
 //BA.debugLineNum = 527;BA.debugLine="End Sub";
return null;
}
public com.ab.abmaterial.ABMCanvasObject  _buildcontrolbar() throws Exception{
com.ab.abmaterial.ABMCanvasObject _cont = null;
 //BA.debugLineNum = 540;BA.debugLine="Sub BuildControlBar() As ABMCanvasObject";
 //BA.debugLineNum = 541;BA.debugLine="Dim cont As ABMCanvasObject";
_cont = new com.ab.abmaterial.ABMCanvasObject();
 //BA.debugLineNum = 542;BA.debugLine="cont.InitializeAsRectangle(page, \"contbar\", 0,0,1";
_cont.InitializeAsRectangle(_page,"contbar",(int) (0),(int) (0),(int) (1024),(int) (100),__c.False);
 //BA.debugLineNum = 543;BA.debugLine="cont.beginPath";
_cont.beginPath();
 //BA.debugLineNum = 544;BA.debugLine="cont.lineWidth(5)";
_cont.lineWidth(5);
 //BA.debugLineNum = 545;BA.debugLine="cont.lineCap(ABM.CANVAS_LINECAP_ROUND)";
_cont.lineCap(_abm.CANVAS_LINECAP_ROUND);
 //BA.debugLineNum = 546;BA.debugLine="cont.strokeStyleColor(\"#888888\")";
_cont.strokeStyleColor("#888888");
 //BA.debugLineNum = 547;BA.debugLine="cont.moveTo(20,47)";
_cont.moveTo(20,47);
 //BA.debugLineNum = 548;BA.debugLine="cont.lineTo(1004,47)";
_cont.lineTo(1004,47);
 //BA.debugLineNum = 549;BA.debugLine="cont.stroke";
_cont.stroke();
 //BA.debugLineNum = 550;BA.debugLine="Return cont";
if (true) return _cont;
 //BA.debugLineNum = 551;BA.debugLine="End Sub";
return null;
}
public com.ab.abmaterial.ABMCanvasObject  _buildcontrolcircle() throws Exception{
com.ab.abmaterial.ABMCanvasObject _cont = null;
 //BA.debugLineNum = 553;BA.debugLine="Sub BuildControlCircle() As ABMCanvasObject";
 //BA.debugLineNum = 554;BA.debugLine="Dim cont As ABMCanvasObject";
_cont = new com.ab.abmaterial.ABMCanvasObject();
 //BA.debugLineNum = 555;BA.debugLine="cont.InitializeAsCircle(page, \"contcirc\", 50,48,4";
_cont.InitializeAsCircle(_page,"contcirc",(int) (50),(int) (48),(int) (40),__c.True);
 //BA.debugLineNum = 557;BA.debugLine="cont.SetDragZone(50,48,924,1)";
_cont.SetDragZone(50,48,924,1);
 //BA.debugLineNum = 559;BA.debugLine="cont.beginPath";
_cont.beginPath();
 //BA.debugLineNum = 560;BA.debugLine="cont.arc(0,0,40, 0, 2*cPI)";
_cont.arc(0,0,40,0,2*__c.cPI);
 //BA.debugLineNum = 561;BA.debugLine="cont.fillStyleColor(\"#000000\")";
_cont.fillStyleColor("#000000");
 //BA.debugLineNum = 562;BA.debugLine="cont.fill";
_cont.fill();
 //BA.debugLineNum = 563;BA.debugLine="cont.save";
_cont.save();
 //BA.debugLineNum = 564;BA.debugLine="cont.translate(-40,-40)";
_cont.translate(-40,-40);
 //BA.debugLineNum = 565;BA.debugLine="cont.drawImage3(\"eric\", 0,0,147,135,5,5, 70,64)";
_cont.drawImage3("eric",0,0,147,135,5,5,70,64);
 //BA.debugLineNum = 566;BA.debugLine="cont.closePath";
_cont.closePath();
 //BA.debugLineNum = 567;BA.debugLine="cont.restore";
_cont.restore();
 //BA.debugLineNum = 568;BA.debugLine="Return cont";
if (true) return _cont;
 //BA.debugLineNum = 569;BA.debugLine="End Sub";
return null;
}
public String  _buildhand(com.ab.abmaterial.ABMCanvasObject _clock,int _pos,double _length,double _width) throws Exception{
 //BA.debugLineNum = 529;BA.debugLine="Sub BuildHand(clock As ABMCanvasObject, pos As Int";
 //BA.debugLineNum = 530;BA.debugLine="clock.beginPath";
_clock.beginPath();
 //BA.debugLineNum = 531;BA.debugLine="clock.lineWidth(width)";
_clock.lineWidth(_width);
 //BA.debugLineNum = 532;BA.debugLine="clock.lineCap(ABM.CANVAS_LINECAP_ROUND)";
_clock.lineCap(_abm.CANVAS_LINECAP_ROUND);
 //BA.debugLineNum = 533;BA.debugLine="clock.moveTo(0,0)";
_clock.moveTo(0,0);
 //BA.debugLineNum = 534;BA.debugLine="clock.rotate(pos)";
_clock.rotate(_pos);
 //BA.debugLineNum = 535;BA.debugLine="clock.lineTo(0, -length)";
_clock.lineTo(0,-_length);
 //BA.debugLineNum = 536;BA.debugLine="clock.stroke";
_clock.stroke();
 //BA.debugLineNum = 537;BA.debugLine="clock.rotate(-pos)";
_clock.rotate(-_pos);
 //BA.debugLineNum = 538;BA.debugLine="End Sub";
return "";
}
public String  _buildpage() throws Exception{
 //BA.debugLineNum = 99;BA.debugLine="public Sub BuildPage()";
 //BA.debugLineNum = 101;BA.debugLine="BuildTheme";
_buildtheme();
 //BA.debugLineNum = 104;BA.debugLine="page.InitializeWithTheme(Name, \"/ws/\" & ABMShared";
_page.InitializeWithTheme(_name,"/ws/"+_abmshared._appname+"/"+_name,__c.False,_abmshared._sessionmaxinactiveintervalseconds,_theme);
 //BA.debugLineNum = 105;BA.debugLine="page.ShowLoader=True";
_page.setShowLoader(__c.True);
 //BA.debugLineNum = 106;BA.debugLine="page.ShowLoaderType=ABM.LOADER_TYPE_MANUAL ' NEW";
_page.setShowLoaderType(_abm.LOADER_TYPE_MANUAL);
 //BA.debugLineNum = 107;BA.debugLine="page.PageTitle = \"ABMCanvas\"";
_page.PageTitle = "ABMCanvas";
 //BA.debugLineNum = 108;BA.debugLine="page.PageDescription = \"The canvas component \"";
_page.PageDescription = "The canvas component ";
 //BA.debugLineNum = 109;BA.debugLine="page.PageHTMLName = \"abmaterial-canvas.html\"";
_page.PageHTMLName = "abmaterial-canvas.html";
 //BA.debugLineNum = 110;BA.debugLine="page.PageKeywords = \"ABMaterial, material design,";
_page.PageKeywords = "ABMaterial, material design, B4X, B4J, SEO, framework, search engine optimization";
 //BA.debugLineNum = 111;BA.debugLine="page.PageSiteMapPriority = \"0.50\"";
_page.PageSiteMapPriority = "0.50";
 //BA.debugLineNum = 112;BA.debugLine="page.PageSiteMapFrequency = ABM.SITEMAP_FREQ_MONT";
_page.PageSiteMapFrequency = _abm.SITEMAP_FREQ_MONTHLY;
 //BA.debugLineNum = 113;BA.debugLine="page.UseGoogleAnalytics(ABMShared.TrackingID, Nul";
_page.UseGoogleAnalytics(_abmshared._trackingid,(anywheresoftware.b4a.objects.collections.List) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.List(), (java.util.List)(__c.Null)));
 //BA.debugLineNum = 115;BA.debugLine="ABMShared.BuildNavigationBar(page, \"ABMCanvas\", \"";
_abmshared._buildnavigationbar(_page,"ABMCanvas","../images/logo.png","","Controls","ABMCanvas");
 //BA.debugLineNum = 118;BA.debugLine="page.AddRows(11,True, \"\").AddCells12(1,\"\")";
_page.AddRows((int) (11),__c.True,"").AddCells12((int) (1),"");
 //BA.debugLineNum = 119;BA.debugLine="page.BuildGrid 'IMPORTANT once you loaded the com";
_page.BuildGrid();
 //BA.debugLineNum = 125;BA.debugLine="page.AddCanvasImage(\"background\", \"../images/back";
_page.AddCanvasImage("background","../images/background.jpg");
 //BA.debugLineNum = 126;BA.debugLine="page.AddCanvasImage(\"kyle\", \"../images/kyle.png\")";
_page.AddCanvasImage("kyle","../images/kyle.png");
 //BA.debugLineNum = 127;BA.debugLine="page.AddCanvasImage(\"kenny\", \"../images/kenny.png";
_page.AddCanvasImage("kenny","../images/kenny.png");
 //BA.debugLineNum = 128;BA.debugLine="page.AddCanvasImage(\"eric\", \"../images/eric.png\")";
_page.AddCanvasImage("eric","../images/eric.png");
 //BA.debugLineNum = 130;BA.debugLine="ABMShared.BuildFooter(page)";
_abmshared._buildfooter(_page);
 //BA.debugLineNum = 131;BA.debugLine="End Sub";
return "";
}
public String  _buildtheme() throws Exception{
 //BA.debugLineNum = 87;BA.debugLine="public Sub BuildTheme()";
 //BA.debugLineNum = 89;BA.debugLine="theme.Initialize(\"pagetheme\")";
_theme.Initialize("pagetheme");
 //BA.debugLineNum = 90;BA.debugLine="theme.AddABMTheme(ABMShared.MyTheme)";
_theme.AddABMTheme(_abmshared._mytheme);
 //BA.debugLineNum = 94;BA.debugLine="theme.AddButtonTheme(\"bluegrey\")";
_theme.AddButtonTheme("bluegrey");
 //BA.debugLineNum = 95;BA.debugLine="theme.Button(\"bluegrey\").BackColor = ABM.COLOR_BL";
_theme.Button("bluegrey").BackColor = _abm.COLOR_BLUEGREY;
 //BA.debugLineNum = 96;BA.debugLine="theme.Button(\"bluegrey\").BackColorIntensity = ABM";
_theme.Button("bluegrey").BackColorIntensity = _abm.INTENSITY_DARKEN1;
 //BA.debugLineNum = 97;BA.debugLine="End Sub";
return "";
}
public String  _canvas1_canvasdown(int _x,int _y) throws Exception{
 //BA.debugLineNum = 470;BA.debugLine="Sub canvas1_CanvasDown(x As Int, y As Int)";
 //BA.debugLineNum = 471;BA.debugLine="Log(\"canvas down: \" & x & \" - \" & y)";
__c.Log("canvas down: "+BA.NumberToString(_x)+" - "+BA.NumberToString(_y));
 //BA.debugLineNum = 472;BA.debugLine="End Sub";
return "";
}
public String  _canvas1_objectup(String _objectid) throws Exception{
String _changedto = "";
com.ab.abmaterial.ABMCanvas _canvas1 = null;
com.ab.abmaterial.ABMCanvasObject _kyle = null;
 //BA.debugLineNum = 442;BA.debugLine="Sub canvas1_ObjectUp(objectId As String)";
 //BA.debugLineNum = 443;BA.debugLine="myToastId = myToastId + 1";
_mytoastid = (int) (_mytoastid+1);
 //BA.debugLineNum = 445;BA.debugLine="Dim ChangedTo As String";
_changedto = "";
 //BA.debugLineNum = 447;BA.debugLine="Dim canvas1 As ABMCanvas = page.Component(\"canvas";
_canvas1 = (com.ab.abmaterial.ABMCanvas)(_page.Component("canvas1"));
 //BA.debugLineNum = 448;BA.debugLine="Dim Kyle As ABMCanvasObject = canvas1.GetObject(o";
_kyle = _canvas1.GetObject(_objectid);
 //BA.debugLineNum = 449;BA.debugLine="If Kyle.Width = 109 Then";
if (_kyle.getWidth()==109) { 
 //BA.debugLineNum = 451;BA.debugLine="Kyle.SetSize(98,129)";
_kyle.SetSize(98,129);
 //BA.debugLineNum = 452;BA.debugLine="Kyle.Clear";
_kyle.Clear();
 //BA.debugLineNum = 453;BA.debugLine="Kyle.drawImage(\"kenny\",0,0)";
_kyle.drawImage("kenny",0,0);
 //BA.debugLineNum = 454;BA.debugLine="Kyle.Refresh ' IMPORTANT";
_kyle.Refresh();
 //BA.debugLineNum = 455;BA.debugLine="ChangedTo = \"Kenny\"";
_changedto = "Kenny";
 }else {
 //BA.debugLineNum = 458;BA.debugLine="Kyle.SetSize(109,136)";
_kyle.SetSize(109,136);
 //BA.debugLineNum = 459;BA.debugLine="Kyle.Clear";
_kyle.Clear();
 //BA.debugLineNum = 460;BA.debugLine="Kyle.drawImage(\"kyle\",0,0)";
_kyle.drawImage("kyle",0,0);
 //BA.debugLineNum = 461;BA.debugLine="Kyle.Refresh ' IMPORTANT";
_kyle.Refresh();
 //BA.debugLineNum = 462;BA.debugLine="ChangedTo = \"Kyle\"";
_changedto = "Kyle";
 };
 //BA.debugLineNum = 465;BA.debugLine="canvas1.Refresh ' IMPORTANT!";
_canvas1.Refresh();
 //BA.debugLineNum = 467;BA.debugLine="page.ShowToast(\"toast\" & myToastId, \"toastred\", o";
_page.ShowToast("toast"+BA.NumberToString(_mytoastid),"toastred",_objectid+" changed to "+_changedto+"!",(int) (5000));
 //BA.debugLineNum = 468;BA.debugLine="End Sub";
return "";
}
public String  _canvas3_objectup(String _objectid) throws Exception{
com.ab.abmaterial.ABMCanvas _canvas1 = null;
com.ab.abmaterial.ABMCanvasObject _eric = null;
com.ab.abmaterial.ABMPoint _pos = null;
int _value = 0;
 //BA.debugLineNum = 571;BA.debugLine="Sub canvas3_ObjectUp(objectId As String)";
 //BA.debugLineNum = 573;BA.debugLine="Dim canvas1 As ABMCanvas = page.Component(\"canvas";
_canvas1 = (com.ab.abmaterial.ABMCanvas)(_page.Component("canvas3"));
 //BA.debugLineNum = 574;BA.debugLine="Dim Eric As ABMCanvasObject = canvas1.GetObject(o";
_eric = _canvas1.GetObject(_objectid);
 //BA.debugLineNum = 575;BA.debugLine="Dim Pos As ABMPoint = Eric.GetPosition";
_pos = _eric.GetPosition();
 //BA.debugLineNum = 576;BA.debugLine="If Pos <> Null Then";
if (_pos!= null) { 
 //BA.debugLineNum = 578;BA.debugLine="Dim value As Int = (Pos.x-50)/924*100";
_value = (int) ((_pos.x-50)/(double)924*100);
 //BA.debugLineNum = 579;BA.debugLine="myToastId = myToastId + 1";
_mytoastid = (int) (_mytoastid+1);
 //BA.debugLineNum = 580;BA.debugLine="page.ShowToast(\"toast\" & myToastId, \"toastred\",";
_page.ShowToast("toast"+BA.NumberToString(_mytoastid),"toastred","Eric is at value "+BA.NumberToString(_value),(int) (5000));
 };
 //BA.debugLineNum = 582;BA.debugLine="End Sub";
return "";
}
public String  _class_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Class_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Private ws As WebSocket 'ignore";
_ws = new anywheresoftware.b4j.object.WebSocket();
 //BA.debugLineNum = 5;BA.debugLine="Public page As ABMPage";
_page = new com.ab.abmaterial.ABMPage();
 //BA.debugLineNum = 7;BA.debugLine="Private theme As ABMTheme";
_theme = new com.ab.abmaterial.ABMTheme();
 //BA.debugLineNum = 9;BA.debugLine="Private ABM As ABMaterial 'ignore";
_abm = new com.ab.abmaterial.ABMaterial();
 //BA.debugLineNum = 11;BA.debugLine="Public Name As String = \"CompCanvasPage\"";
_name = "CompCanvasPage";
 //BA.debugLineNum = 12;BA.debugLine="Private ABMPageId As String = \"\"";
_abmpageid = "";
 //BA.debugLineNum = 15;BA.debugLine="Dim myToastId As Int";
_mytoastid = 0;
 //BA.debugLineNum = 16;BA.debugLine="Dim kyleTeller As Int";
_kyleteller = 0;
 //BA.debugLineNum = 17;BA.debugLine="End Sub";
return "";
}
public String  _connectpage() throws Exception{
com.ab.abmaterial.ABMCanvas _canvas1 = null;
com.ab.abmaterial.ABMCanvasObject _bg = null;
com.ab.abmaterial.ABMButton _btn = null;
anywheresoftware.b4a.keywords.StringBuilderWrapper _code1 = null;
anywheresoftware.b4a.keywords.StringBuilderWrapper _code2 = null;
com.ab.abmaterial.ABMCanvas _canvas2 = null;
com.ab.abmaterial.ABMCanvasObject _clock = null;
anywheresoftware.b4a.keywords.StringBuilderWrapper _code3 = null;
anywheresoftware.b4a.keywords.StringBuilderWrapper _code4 = null;
com.ab.abmaterial.ABMCanvas _canvas3 = null;
com.ab.abmaterial.ABMCanvasObject _controlbar = null;
com.ab.abmaterial.ABMCanvasObject _controlcircle = null;
anywheresoftware.b4a.keywords.StringBuilderWrapper _code5 = null;
anywheresoftware.b4a.keywords.StringBuilderWrapper _code6 = null;
 //BA.debugLineNum = 133;BA.debugLine="Sub ConnectPage()";
 //BA.debugLineNum = 135;BA.debugLine="ABMShared.ConnectNavigationBar(page)";
_abmshared._connectnavigationbar(_page);
 //BA.debugLineNum = 138;BA.debugLine="page.Cell(1,1).AddComponent(ABMShared.BuildParagr";
_page.Cell((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par1","ABMCanvas is a HTML5 Canvas with Dragging possibilities.  All drawing is done with ABMVCanvasObjects and supports almost all methods described in {AL}http://www.w3schools.com/tags/ref_canvas.asp{AT}W3Schools{/AL}.")));
 //BA.debugLineNum = 141;BA.debugLine="Dim canvas1 As ABMCanvas";
_canvas1 = new com.ab.abmaterial.ABMCanvas();
 //BA.debugLineNum = 142;BA.debugLine="canvas1.Initialize(page, \"canvas1\", ABM.COLOR_BLA";
_canvas1.Initialize(_page,"canvas1",_abm.COLOR_BLACK,_abm.INTENSITY_NORMAL,(int) (1024),(int) (569),__c.True);
 //BA.debugLineNum = 145;BA.debugLine="Dim bg As ABMCanvasObject";
_bg = new com.ab.abmaterial.ABMCanvasObject();
 //BA.debugLineNum = 146;BA.debugLine="bg.InitializeAsRectangle(page, \"bg\",0,0,1024,569,";
_bg.InitializeAsRectangle(_page,"bg",(int) (0),(int) (0),(int) (1024),(int) (569),__c.False);
 //BA.debugLineNum = 147;BA.debugLine="bg.drawImage(\"background\", 0,0)";
_bg.drawImage("background",0,0);
 //BA.debugLineNum = 148;BA.debugLine="canvas1.AddObject(bg)";
_canvas1.AddObject(_bg);
 //BA.debugLineNum = 150;BA.debugLine="page.Cell(2,1).AddComponent(canvas1)";
_page.Cell((int) (2),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_canvas1));
 //BA.debugLineNum = 152;BA.debugLine="Dim btn As ABMButton";
_btn = new com.ab.abmaterial.ABMButton();
 //BA.debugLineNum = 153;BA.debugLine="btn.InitializeRaised(page, \"btn\", \"\", \"\", \"Add Ky";
_btn.InitializeRaised(_page,"btn","","","Add Kyle","bluegrey");
 //BA.debugLineNum = 154;BA.debugLine="page.Cell(3,1).AddComponent(btn)";
_page.Cell((int) (3),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_btn));
 //BA.debugLineNum = 157;BA.debugLine="Dim code1 As StringBuilder";
_code1 = new anywheresoftware.b4a.keywords.StringBuilderWrapper();
 //BA.debugLineNum = 158;BA.debugLine="code1.Initialize";
_code1.Initialize();
 //BA.debugLineNum = 159;BA.debugLine="code1.Append(\"// load images we will need in the";
_code1.Append("// load images we will need in the canvases").Append(__c.CRLF);
 //BA.debugLineNum = 160;BA.debugLine="code1.Append(\"page.AddCanvasImage(\"\"background\"\",";
_code1.Append("page.AddCanvasImage(\"background\", \"../images/background.jpg\")").Append(__c.CRLF);
 //BA.debugLineNum = 161;BA.debugLine="code1.Append(\"page.AddCanvasImage(\"\"kyle\"\", \"\"../";
_code1.Append("page.AddCanvasImage(\"kyle\", \"../images/kyle.png\")").Append(__c.CRLF);
 //BA.debugLineNum = 162;BA.debugLine="code1.Append(\"page.AddCanvasImage(\"\"kenny\"\", \"\"..";
_code1.Append("page.AddCanvasImage(\"kenny\", \"../images/kenny.png\")").Append(__c.CRLF);
 //BA.debugLineNum = 163;BA.debugLine="code1.Append(\"\").Append(CRLF)";
_code1.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 164;BA.debugLine="code1.Append(\"// create canvas\").Append(CRLF)";
_code1.Append("// create canvas").Append(__c.CRLF);
 //BA.debugLineNum = 165;BA.debugLine="code1.Append(\"Dim canvas1 As ABMCanvas\").Append(C";
_code1.Append("Dim canvas1 As ABMCanvas").Append(__c.CRLF);
 //BA.debugLineNum = 166;BA.debugLine="code1.Append(\"canvas1.Initialize(page, \"\"canvas1\"";
_code1.Append("canvas1.Initialize(page, \"canvas1\", ABM.COLOR_BLACK, ABM.INTENSITY_NORMAL,1024,569, True)").Append(__c.CRLF);
 //BA.debugLineNum = 167;BA.debugLine="code1.Append(\"\").Append(CRLF)";
_code1.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 168;BA.debugLine="code1.Append(\"// create background\").Append(CRLF)";
_code1.Append("// create background").Append(__c.CRLF);
 //BA.debugLineNum = 169;BA.debugLine="code1.Append(\"Dim bg As ABMCanvasObject\").Append(";
_code1.Append("Dim bg As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 170;BA.debugLine="code1.Append(\"bg.InitializeAsRectangle(page, \"\"bg";
_code1.Append("bg.InitializeAsRectangle(page, \"bg\",0,0,1024,569,False)").Append(__c.CRLF);
 //BA.debugLineNum = 171;BA.debugLine="code1.Append(\"bg.drawImage(\"\"background\"\", 0,0)\")";
_code1.Append("bg.drawImage(\"background\", 0,0)").Append(__c.CRLF);
 //BA.debugLineNum = 172;BA.debugLine="code1.Append(\"canvas1.AddObject(bg)\").Append(CRLF";
_code1.Append("canvas1.AddObject(bg)").Append(__c.CRLF);
 //BA.debugLineNum = 174;BA.debugLine="page.Cell(4,1).AddComponent(ABMShared.BuildCodeBl";
_page.Cell((int) (4),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildcodeblock(_page,"code1",_code1)));
 //BA.debugLineNum = 177;BA.debugLine="Dim code2 As StringBuilder";
_code2 = new anywheresoftware.b4a.keywords.StringBuilderWrapper();
 //BA.debugLineNum = 178;BA.debugLine="code2.Initialize";
_code2.Initialize();
 //BA.debugLineNum = 179;BA.debugLine="code2.Append(\"Sub btn_Clicked(Target As String)\")";
_code2.Append("Sub btn_Clicked(Target As String)").Append(__c.CRLF);
 //BA.debugLineNum = 180;BA.debugLine="code2.Append(\"   Dim canvas1 As ABMCanvas = page.";
_code2.Append("   Dim canvas1 As ABMCanvas = page.Component(\"canvas1\")").Append(__c.CRLF);
 //BA.debugLineNum = 181;BA.debugLine="code2.Append(\"   Dim Kyle As ABMCanvasObject\").Ap";
_code2.Append("   Dim Kyle As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 182;BA.debugLine="code2.Append(\"   Dim x As Int = Rnd(0,1024-109)\")";
_code2.Append("   Dim x As Int = Rnd(0,1024-109)").Append(__c.CRLF);
 //BA.debugLineNum = 183;BA.debugLine="code2.Append(\"   Dim y As Int = Rnd(0,569-136)\").";
_code2.Append("   Dim y As Int = Rnd(0,569-136)").Append(__c.CRLF);
 //BA.debugLineNum = 184;BA.debugLine="code2.Append(\"   kyleTeller=kyleTeller+1\").Append";
_code2.Append("   kyleTeller=kyleTeller+1").Append(__c.CRLF);
 //BA.debugLineNum = 185;BA.debugLine="code2.Append(\"   Kyle.InitializeAsRectangle(page,";
_code2.Append("   Kyle.InitializeAsRectangle(page, \"kyle\" & kyleTeller, x, y, 109,136, True)").Append(__c.CRLF);
 //BA.debugLineNum = 186;BA.debugLine="code2.Append(\"   Kyle.drawImage(\"\"kyle\"\", 0,0)\").";
_code2.Append("   Kyle.drawImage(\"kyle\", 0,0)").Append(__c.CRLF);
 //BA.debugLineNum = 187;BA.debugLine="code2.Append(\"   canvas1.AddObject(Kyle)\").Append";
_code2.Append("   canvas1.AddObject(Kyle)").Append(__c.CRLF);
 //BA.debugLineNum = 188;BA.debugLine="code2.Append(\"   canvas1.refresh // IMPORTANT\").A";
_code2.Append("   canvas1.refresh // IMPORTANT").Append(__c.CRLF);
 //BA.debugLineNum = 189;BA.debugLine="code2.Append(\"End Sub\").Append(CRLF)";
_code2.Append("End Sub").Append(__c.CRLF);
 //BA.debugLineNum = 190;BA.debugLine="code2.Append(\"\").Append(CRLF)";
_code2.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 191;BA.debugLine="code2.Append(\"Sub canvas1_ObjectUp(objectId As St";
_code2.Append("Sub canvas1_ObjectUp(objectId As String)").Append(__c.CRLF);
 //BA.debugLineNum = 192;BA.debugLine="code2.Append(\"   myToastId = myToastId + 1	\").App";
_code2.Append("   myToastId = myToastId + 1	").Append(__c.CRLF);
 //BA.debugLineNum = 193;BA.debugLine="code2.Append(\"   Dim ChangedTo As String\").Append";
_code2.Append("   Dim ChangedTo As String").Append(__c.CRLF);
 //BA.debugLineNum = 194;BA.debugLine="code2.Append(\"   Dim canvas1 As ABMCanvas = page.";
_code2.Append("   Dim canvas1 As ABMCanvas = page.Component(\"canvas1\")").Append(__c.CRLF);
 //BA.debugLineNum = 195;BA.debugLine="code2.Append(\"   Dim Kyle As ABMCanvasObject = ca";
_code2.Append("   Dim Kyle As ABMCanvasObject = canvas1.GetObject(objectId)").Append(__c.CRLF);
 //BA.debugLineNum = 196;BA.debugLine="code2.Append(\"   If Kyle.Width = 109 Then\").Appen";
_code2.Append("   If Kyle.Width = 109 Then").Append(__c.CRLF);
 //BA.debugLineNum = 197;BA.debugLine="code2.Append(\"   	//changing the size to the new";
_code2.Append("   	//changing the size to the new picture").Append(__c.CRLF);
 //BA.debugLineNum = 198;BA.debugLine="code2.Append(\"   	Kyle.SetSize(98,129)\").Append(C";
_code2.Append("   	Kyle.SetSize(98,129)").Append(__c.CRLF);
 //BA.debugLineNum = 199;BA.debugLine="code2.Append(\"   	Kyle.Clear\").Append(CRLF)";
_code2.Append("   	Kyle.Clear").Append(__c.CRLF);
 //BA.debugLineNum = 200;BA.debugLine="code2.Append(\"   	Kyle.drawImage(\"\"kenny\"\",0,0)\")";
_code2.Append("   	Kyle.drawImage(\"kenny\",0,0)").Append(__c.CRLF);
 //BA.debugLineNum = 201;BA.debugLine="code2.Append(\"   	Kyle.Refresh // IMPORTANT\").App";
_code2.Append("   	Kyle.Refresh // IMPORTANT").Append(__c.CRLF);
 //BA.debugLineNum = 202;BA.debugLine="code2.Append(\"   	ChangedTo = \"\"Kenny\"\"\").Append(";
_code2.Append("   	ChangedTo = \"Kenny\"").Append(__c.CRLF);
 //BA.debugLineNum = 203;BA.debugLine="code2.Append(\"   Else\").Append(CRLF)";
_code2.Append("   Else").Append(__c.CRLF);
 //BA.debugLineNum = 204;BA.debugLine="code2.Append(\"   	// changing the size to the new";
_code2.Append("   	// changing the size to the new picture").Append(__c.CRLF);
 //BA.debugLineNum = 205;BA.debugLine="code2.Append(\"   	Kyle.SetSize(109,136)\").Append(";
_code2.Append("   	Kyle.SetSize(109,136)").Append(__c.CRLF);
 //BA.debugLineNum = 206;BA.debugLine="code2.Append(\"   	Kyle.Clear\").Append(CRLF)";
_code2.Append("   	Kyle.Clear").Append(__c.CRLF);
 //BA.debugLineNum = 207;BA.debugLine="code2.Append(\"   	Kyle.drawImage(\"\"kyle\"\",0,0)\").";
_code2.Append("   	Kyle.drawImage(\"kyle\",0,0)").Append(__c.CRLF);
 //BA.debugLineNum = 208;BA.debugLine="code2.Append(\"   	Kyle.Refresh // IMPORTANT\").App";
_code2.Append("   	Kyle.Refresh // IMPORTANT").Append(__c.CRLF);
 //BA.debugLineNum = 209;BA.debugLine="code2.Append(\"   	ChangedTo = \"\"Kyle\"\"\").Append(C";
_code2.Append("   	ChangedTo = \"Kyle\"").Append(__c.CRLF);
 //BA.debugLineNum = 210;BA.debugLine="code2.Append(\"   End If\").Append(CRLF)";
_code2.Append("   End If").Append(__c.CRLF);
 //BA.debugLineNum = 211;BA.debugLine="code2.Append(\"\").Append(CRLF)";
_code2.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 212;BA.debugLine="code2.Append(\"   canvas1.Refresh // IMPORTANT!\").";
_code2.Append("   canvas1.Refresh // IMPORTANT!").Append(__c.CRLF);
 //BA.debugLineNum = 213;BA.debugLine="code2.Append(\"\").Append(CRLF)";
_code2.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 214;BA.debugLine="code2.Append(\"   page.ShowToast(\"\"toast\"\" & myToa";
_code2.Append("   page.ShowToast(\"toast\" & myToastId, \"toastred\", objectId & \" changed to \" & ChangedTo & \"!\", 5000)").Append(__c.CRLF);
 //BA.debugLineNum = 215;BA.debugLine="code2.Append(\"   End Sub\").Append(CRLF)";
_code2.Append("   End Sub").Append(__c.CRLF);
 //BA.debugLineNum = 217;BA.debugLine="page.Cell(4,1).AddComponent(ABMShared.BuildCodeBl";
_page.Cell((int) (4),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildcodeblock(_page,"code2",_code2)));
 //BA.debugLineNum = 220;BA.debugLine="page.Cell(5,1).AddComponent(ABMShared.BuildParagr";
_page.Cell((int) (5),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par2","An example of the basic drawing functionalities on the ABMCanvas.")));
 //BA.debugLineNum = 223;BA.debugLine="Dim canvas2 As ABMCanvas";
_canvas2 = new com.ab.abmaterial.ABMCanvas();
 //BA.debugLineNum = 224;BA.debugLine="canvas2.Initialize(page, \"canvas2\", ABM.COLOR_BLA";
_canvas2.Initialize(_page,"canvas2",_abm.COLOR_BLACK,_abm.INTENSITY_NORMAL,(int) (300),(int) (300),__c.False);
 //BA.debugLineNum = 226;BA.debugLine="Dim clock As ABMCanvasObject = BuildClock";
_clock = _buildclock();
 //BA.debugLineNum = 227;BA.debugLine="canvas2.AddObject(clock)";
_canvas2.AddObject(_clock);
 //BA.debugLineNum = 229;BA.debugLine="page.Cell(6,1).AddComponent(canvas2)";
_page.Cell((int) (6),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_canvas2));
 //BA.debugLineNum = 232;BA.debugLine="Dim code3 As StringBuilder";
_code3 = new anywheresoftware.b4a.keywords.StringBuilderWrapper();
 //BA.debugLineNum = 233;BA.debugLine="code3.Initialize";
_code3.Initialize();
 //BA.debugLineNum = 234;BA.debugLine="code3.Append(\"// the clock canvas\").Append(CRLF)";
_code3.Append("// the clock canvas").Append(__c.CRLF);
 //BA.debugLineNum = 235;BA.debugLine="code3.Append(\"Dim canvas2 As ABMCanvas\").Append(C";
_code3.Append("Dim canvas2 As ABMCanvas").Append(__c.CRLF);
 //BA.debugLineNum = 236;BA.debugLine="code3.Append(\"canvas2.Initialize(page, \"\"canvas2\"";
_code3.Append("canvas2.Initialize(page, \"canvas2\", ABM.COLOR_BLACK, ABM.INTENSITY_NORMAL, 300,300, False)").Append(__c.CRLF);
 //BA.debugLineNum = 237;BA.debugLine="code3.Append(\"\").Append(CRLF)";
_code3.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 238;BA.debugLine="code3.Append(\"Dim clock As ABMCanvasObject = Buil";
_code3.Append("Dim clock As ABMCanvasObject = BuildClock").Append(__c.CRLF);
 //BA.debugLineNum = 239;BA.debugLine="code3.Append(\"canvas2.AddObject(clock)\").Append(C";
_code3.Append("canvas2.AddObject(clock)").Append(__c.CRLF);
 //BA.debugLineNum = 240;BA.debugLine="code3.Append(\"\").Append(CRLF)";
_code3.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 241;BA.debugLine="code3.Append(\"page.Cell(6,1).AddComponent(canvas2";
_code3.Append("page.Cell(6,1).AddComponent(canvas2)").Append(__c.CRLF);
 //BA.debugLineNum = 243;BA.debugLine="page.Cell(7,1).AddComponent(ABMShared.BuildCodeBl";
_page.Cell((int) (7),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildcodeblock(_page,"code3",_code3)));
 //BA.debugLineNum = 246;BA.debugLine="Dim code4 As StringBuilder";
_code4 = new anywheresoftware.b4a.keywords.StringBuilderWrapper();
 //BA.debugLineNum = 247;BA.debugLine="code4.Initialize";
_code4.Initialize();
 //BA.debugLineNum = 248;BA.debugLine="code4.Append(\"// check out the tutorial on W3Scho";
_code4.Append("// check out the tutorial on W3Schools.com: http://www.w3schools.com/canvas/canvas_clock.asp").Append(__c.CRLF);
 //BA.debugLineNum = 249;BA.debugLine="code4.Append(\"Sub BuildClock() As ABMCanvasObject";
_code4.Append("Sub BuildClock() As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 250;BA.debugLine="code4.Append(\"   Dim clock As ABMCanvasObject\").A";
_code4.Append("   Dim clock As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 251;BA.debugLine="code4.Append(\"   Dim Radius As Double = 150\").App";
_code4.Append("   Dim Radius As Double = 150").Append(__c.CRLF);
 //BA.debugLineNum = 252;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 253;BA.debugLine="code4.Append(\"   clock.InitializeAsRectangle(page";
_code4.Append("   clock.InitializeAsRectangle(page, \"clock\", 0,0,300,300, True)").Append(__c.CRLF);
 //BA.debugLineNum = 254;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 255;BA.debugLine="code4.Append(\"   Radius = Radius * 0.9\").Append(C";
_code4.Append("   Radius = Radius * 0.9").Append(__c.CRLF);
 //BA.debugLineNum = 256;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 257;BA.debugLine="code4.Append(\"   // draw face\").Append(CRLF)";
_code4.Append("   // draw face").Append(__c.CRLF);
 //BA.debugLineNum = 258;BA.debugLine="code4.Append(\"   clock.translate(150,150)\").Appen";
_code4.Append("   clock.translate(150,150)").Append(__c.CRLF);
 //BA.debugLineNum = 259;BA.debugLine="code4.Append(\"   clock.beginPath\").Append(CRLF)";
_code4.Append("   clock.beginPath").Append(__c.CRLF);
 //BA.debugLineNum = 260;BA.debugLine="code4.Append(\"   clock.arc(0,0,Radius, 0, 2*cPI)\"";
_code4.Append("   clock.arc(0,0,Radius, 0, 2*cPI)").Append(__c.CRLF);
 //BA.debugLineNum = 261;BA.debugLine="code4.Append(\"   clock.fillStyleColor(\"\"#FFFFFF\"\"";
_code4.Append("   clock.fillStyleColor(\"#FFFFFF\")").Append(__c.CRLF);
 //BA.debugLineNum = 262;BA.debugLine="code4.Append(\"   clock.fill\").Append(CRLF)";
_code4.Append("   clock.fill").Append(__c.CRLF);
 //BA.debugLineNum = 263;BA.debugLine="code4.Append(\"   clock.strokeStyleRadialGradient(";
_code4.Append("   clock.strokeStyleRadialGradient(0,0,Radius*0.95,0,0,Radius*1.05, Array As Double(0,0.5,1), Array As String(\"#333\", \"white\", \"#333\"))").Append(__c.CRLF);
 //BA.debugLineNum = 264;BA.debugLine="code4.Append(\"   clock.lineWidth(Radius*0.1)\")";
_code4.Append("   clock.lineWidth(Radius*0.1)").Append(__c.CRLF);
 //BA.debugLineNum = 265;BA.debugLine="code4.Append(\"   clock.stroke()\").Append(CRLF)";
_code4.Append("   clock.stroke()").Append(__c.CRLF);
 //BA.debugLineNum = 266;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 267;BA.debugLine="code4.Append(\"   clock.beginPath\").Append(CRLF)";
_code4.Append("   clock.beginPath").Append(__c.CRLF);
 //BA.debugLineNum = 268;BA.debugLine="code4.Append(\"   clock.arc(0, 0, Radius*0.1, 0,";
_code4.Append("   clock.arc(0, 0, Radius*0.1, 0, 2*cPI)").Append(__c.CRLF);
 //BA.debugLineNum = 269;BA.debugLine="code4.Append(\"   clock.fillStyleColor(\"\"#333\"\")";
_code4.Append("   clock.fillStyleColor(\"#333\")").Append(__c.CRLF);
 //BA.debugLineNum = 270;BA.debugLine="code4.Append(\"   clock.fill\").Append(CRLF)";
_code4.Append("   clock.fill").Append(__c.CRLF);
 //BA.debugLineNum = 271;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 272;BA.debugLine="code4.Append(\"   //draw numbers\").Append(CRLF)";
_code4.Append("   //draw numbers").Append(__c.CRLF);
 //BA.debugLineNum = 273;BA.debugLine="code4.Append(\"   clock.font(\"\"arial\"\", Radius*0.1";
_code4.Append("   clock.font(\"arial\", Radius*0.15)").Append(__c.CRLF);
 //BA.debugLineNum = 274;BA.debugLine="code4.Append(\"   clock.textBaseline(ABM.CANVAS_";
_code4.Append("   clock.textBaseline(ABM.CANVAS_TEXTBASELINE_MIDDLE)").Append(__c.CRLF);
 //BA.debugLineNum = 275;BA.debugLine="code4.Append(\"   clock.textAlign(ABM.CANVAS_TEX";
_code4.Append("   clock.textAlign(ABM.CANVAS_TEXTALIGN_CENTER)").Append(__c.CRLF);
 //BA.debugLineNum = 276;BA.debugLine="code4.Append(\"   Dim ang As Double\").Append(CRLF)";
_code4.Append("   Dim ang As Double").Append(__c.CRLF);
 //BA.debugLineNum = 277;BA.debugLine="code4.Append(\"   For num = 1 To 12\").Append(CRL";
_code4.Append("   For num = 1 To 12").Append(__c.CRLF);
 //BA.debugLineNum = 278;BA.debugLine="code4.Append(\"   	ang = num * cPI / 6\").Append";
_code4.Append("   	ang = num * cPI / 6").Append(__c.CRLF);
 //BA.debugLineNum = 279;BA.debugLine="code4.Append(\"   	clock.rotate(ang)\").Append(C";
_code4.Append("   	clock.rotate(ang)").Append(__c.CRLF);
 //BA.debugLineNum = 280;BA.debugLine="code4.Append(\"   	clock.translate(0, -Radius*0";
_code4.Append("   	clock.translate(0, -Radius*0.85)").Append(__c.CRLF);
 //BA.debugLineNum = 281;BA.debugLine="code4.Append(\"   	clock.rotate(-ang)\").Append(";
_code4.Append("   	clock.rotate(-ang)").Append(__c.CRLF);
 //BA.debugLineNum = 282;BA.debugLine="code4.Append(\"   	clock.fillText(\"\"\"\" & num, 0";
_code4.Append("   	clock.fillText(\"\" & num, 0, 0)").Append(__c.CRLF);
 //BA.debugLineNum = 283;BA.debugLine="code4.Append(\"   	clock.rotate(ang)\").Append(C";
_code4.Append("   	clock.rotate(ang)").Append(__c.CRLF);
 //BA.debugLineNum = 284;BA.debugLine="code4.Append(\"   	clock.translate(0, Radius*0.";
_code4.Append("   	clock.translate(0, Radius*0.85)").Append(__c.CRLF);
 //BA.debugLineNum = 285;BA.debugLine="code4.Append(\"   	clock.rotate(-ang)\").Append(";
_code4.Append("   	clock.rotate(-ang)").Append(__c.CRLF);
 //BA.debugLineNum = 286;BA.debugLine="code4.Append(\"   Next\").Append(CRLF)";
_code4.Append("   Next").Append(__c.CRLF);
 //BA.debugLineNum = 287;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 288;BA.debugLine="code4.Append(\"   // draw time\").Append(CRLF)";
_code4.Append("   // draw time").Append(__c.CRLF);
 //BA.debugLineNum = 289;BA.debugLine="code4.Append(\"   Dim hour As Double = DateTime.Ge";
_code4.Append("   Dim hour As Double = DateTime.GetHour(DateTime.Now)").Append(__c.CRLF);
 //BA.debugLineNum = 290;BA.debugLine="code4.Append(\"   Dim minute As Double = DateTime.";
_code4.Append("   Dim minute As Double = DateTime.GetMinute(DateTime.Now)").Append(__c.CRLF);
 //BA.debugLineNum = 291;BA.debugLine="code4.Append(\"   Dim second As Double = DateTime.";
_code4.Append("   Dim second As Double = DateTime.GetSecond(DateTime.Now)").Append(__c.CRLF);
 //BA.debugLineNum = 292;BA.debugLine="code4.Append(\"   hour = hour mod 12\").Append(CRLF";
_code4.Append("   hour = hour mod 12").Append(__c.CRLF);
 //BA.debugLineNum = 293;BA.debugLine="code4.Append(\"   hour = (hour*cPI/6)+(minute*cPI/";
_code4.Append("   hour = (hour*cPI/6)+(minute*cPI/(6*60))+(second*cPI/(360*60))").Append(__c.CRLF);
 //BA.debugLineNum = 294;BA.debugLine="code4.Append(\"   BuildHand(clock, hour, Radius*0.";
_code4.Append("   BuildHand(clock, hour, Radius*0.5, Radius*0.07)").Append(__c.CRLF);
 //BA.debugLineNum = 295;BA.debugLine="code4.Append(\"   minute=(minute*cPI/30)+(second*c";
_code4.Append("   minute=(minute*cPI/30)+(second*cPI/(30*60))").Append(__c.CRLF);
 //BA.debugLineNum = 296;BA.debugLine="code4.Append(\"   BuildHand(clock, minute, Radius*";
_code4.Append("   BuildHand(clock, minute, Radius*0.8, Radius*0.07)").Append(__c.CRLF);
 //BA.debugLineNum = 297;BA.debugLine="code4.Append(\"   second=(second*cPI/30)\").Append(";
_code4.Append("   second=(second*cPI/30)").Append(__c.CRLF);
 //BA.debugLineNum = 298;BA.debugLine="code4.Append(\"   BuildHand(clock, second, Radius*";
_code4.Append("   BuildHand(clock, second, Radius*0.9, Radius*0.02)").Append(__c.CRLF);
 //BA.debugLineNum = 299;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 300;BA.debugLine="code4.Append(\"   Return clock\").Append(CRLF)";
_code4.Append("   Return clock").Append(__c.CRLF);
 //BA.debugLineNum = 301;BA.debugLine="code4.Append(\"End Sub\").Append(CRLF)";
_code4.Append("End Sub").Append(__c.CRLF);
 //BA.debugLineNum = 302;BA.debugLine="code4.Append(\"\").Append(CRLF)";
_code4.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 303;BA.debugLine="code4.Append(\"Sub BuildHand(clock As ABMCanvasObj";
_code4.Append("Sub BuildHand(clock As ABMCanvasObject, pos As Int, length As Double, width As Double)").Append(__c.CRLF);
 //BA.debugLineNum = 304;BA.debugLine="code4.Append(\"   clock.beginPath\").Append(CRLF)";
_code4.Append("   clock.beginPath").Append(__c.CRLF);
 //BA.debugLineNum = 305;BA.debugLine="code4.Append(\"   clock.lineWidth(width)\").Appe";
_code4.Append("   clock.lineWidth(width)").Append(__c.CRLF);
 //BA.debugLineNum = 306;BA.debugLine="code4.Append(\"   clock.lineCap(ABM.CANVAS_LINE";
_code4.Append("   clock.lineCap(ABM.CANVAS_LINECAP_ROUND)").Append(__c.CRLF);
 //BA.debugLineNum = 307;BA.debugLine="code4.Append(\"   clock.moveTo(0,0)\").Append(CR";
_code4.Append("   clock.moveTo(0,0)").Append(__c.CRLF);
 //BA.debugLineNum = 308;BA.debugLine="code4.Append(\"   clock.rotate(pos)\").Append(CR";
_code4.Append("   clock.rotate(pos)").Append(__c.CRLF);
 //BA.debugLineNum = 309;BA.debugLine="code4.Append(\"   clock.lineTo(0, -length)\").Ap";
_code4.Append("   clock.lineTo(0, -length)").Append(__c.CRLF);
 //BA.debugLineNum = 310;BA.debugLine="code4.Append(\"   clock.stroke\").Append(CRLF)";
_code4.Append("   clock.stroke").Append(__c.CRLF);
 //BA.debugLineNum = 311;BA.debugLine="code4.Append(\"   clock.rotate(-pos)\").Append(C";
_code4.Append("   clock.rotate(-pos)").Append(__c.CRLF);
 //BA.debugLineNum = 312;BA.debugLine="code4.Append(\"End Sub\").Append(CRLF)";
_code4.Append("End Sub").Append(__c.CRLF);
 //BA.debugLineNum = 314;BA.debugLine="page.Cell(7,1).AddComponent(ABMShared.BuildCodeBl";
_page.Cell((int) (7),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildcodeblock(_page,"code4",_code4)));
 //BA.debugLineNum = 317;BA.debugLine="page.Cell(8,1).AddComponent(ABMShared.BuildParagr";
_page.Cell((int) (8),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par3","ABMCanvas can be used to build your own controls.")));
 //BA.debugLineNum = 320;BA.debugLine="Dim canvas3 As ABMCanvas";
_canvas3 = new com.ab.abmaterial.ABMCanvas();
 //BA.debugLineNum = 321;BA.debugLine="canvas3.Initialize(page, \"canvas3\", ABM.COLOR_TRA";
_canvas3.Initialize(_page,"canvas3",_abm.COLOR_TRANSPARENT,_abm.INTENSITY_NORMAL,(int) (1024),(int) (100),__c.True);
 //BA.debugLineNum = 323;BA.debugLine="Dim controlBar As ABMCanvasObject = BuildControlB";
_controlbar = _buildcontrolbar();
 //BA.debugLineNum = 324;BA.debugLine="canvas3.AddObject(controlBar)";
_canvas3.AddObject(_controlbar);
 //BA.debugLineNum = 326;BA.debugLine="Dim controlCircle As ABMCanvasObject = BuildContr";
_controlcircle = _buildcontrolcircle();
 //BA.debugLineNum = 327;BA.debugLine="canvas3.AddObject(controlCircle)";
_canvas3.AddObject(_controlcircle);
 //BA.debugLineNum = 329;BA.debugLine="page.Cell(9,1).AddComponent(canvas3)";
_page.Cell((int) (9),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_canvas3));
 //BA.debugLineNum = 332;BA.debugLine="Dim code5 As StringBuilder";
_code5 = new anywheresoftware.b4a.keywords.StringBuilderWrapper();
 //BA.debugLineNum = 333;BA.debugLine="code5.Initialize";
_code5.Initialize();
 //BA.debugLineNum = 334;BA.debugLine="code5.Append(\"// the control canvas\").Append(CRLF";
_code5.Append("// the control canvas").Append(__c.CRLF);
 //BA.debugLineNum = 335;BA.debugLine="code5.Append(\"Dim canvas3 As ABMCanvas\").Append(C";
_code5.Append("Dim canvas3 As ABMCanvas").Append(__c.CRLF);
 //BA.debugLineNum = 336;BA.debugLine="code5.Append(\"canvas3.Initialize(page, \"\"canvas3\"";
_code5.Append("canvas3.Initialize(page, \"canvas3\", ABM.COLOR_TRANSPARENT, ABM.INTENSITY_NORMAL, 1024,100, True)").Append(__c.CRLF);
 //BA.debugLineNum = 337;BA.debugLine="code5.Append(\"\").Append(CRLF)";
_code5.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 338;BA.debugLine="code5.Append(\"Dim controlBar As ABMCanvasObject =";
_code5.Append("Dim controlBar As ABMCanvasObject = BuildControlBar").Append(__c.CRLF);
 //BA.debugLineNum = 339;BA.debugLine="code5.Append(\"canvas3.AddObject(controlBar)\").App";
_code5.Append("canvas3.AddObject(controlBar)").Append(__c.CRLF);
 //BA.debugLineNum = 340;BA.debugLine="code5.Append(\"\").Append(CRLF)";
_code5.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 341;BA.debugLine="code5.Append(\"Dim controlCircle As ABMCanvasObjec";
_code5.Append("Dim controlCircle As ABMCanvasObject = BuildControlCircle").Append(__c.CRLF);
 //BA.debugLineNum = 342;BA.debugLine="code5.Append(\"canvas3.AddObject(controlCircle)\").";
_code5.Append("canvas3.AddObject(controlCircle)").Append(__c.CRLF);
 //BA.debugLineNum = 344;BA.debugLine="page.Cell(10,1).AddComponent(ABMShared.BuildCodeB";
_page.Cell((int) (10),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildcodeblock(_page,"code5",_code5)));
 //BA.debugLineNum = 347;BA.debugLine="Dim code6 As StringBuilder";
_code6 = new anywheresoftware.b4a.keywords.StringBuilderWrapper();
 //BA.debugLineNum = 348;BA.debugLine="code6.Initialize";
_code6.Initialize();
 //BA.debugLineNum = 349;BA.debugLine="code6.Append(\"// the control canvas\").Append(CRLF";
_code6.Append("// the control canvas").Append(__c.CRLF);
 //BA.debugLineNum = 350;BA.debugLine="code6.Append(\"Sub BuildControlBar() As ABMCanvasO";
_code6.Append("Sub BuildControlBar() As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 351;BA.debugLine="code6.Append(\"   Dim cont As ABMCanvasObject\").Ap";
_code6.Append("   Dim cont As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 352;BA.debugLine="code6.Append(\"   cont.InitializeAsRectangle(page,";
_code6.Append("   cont.InitializeAsRectangle(page, \"contbar\", 0,0,1024,100,False)").Append(__c.CRLF);
 //BA.debugLineNum = 353;BA.debugLine="code6.Append(\"   cont.beginPath\").Append(CRLF)";
_code6.Append("   cont.beginPath").Append(__c.CRLF);
 //BA.debugLineNum = 354;BA.debugLine="code6.Append(\"   cont.lineWidth(5)\").Append(CRLF)";
_code6.Append("   cont.lineWidth(5)").Append(__c.CRLF);
 //BA.debugLineNum = 355;BA.debugLine="code6.Append(\"   cont.lineCap(ABM.CANVAS_LINECAP_";
_code6.Append("   cont.lineCap(ABM.CANVAS_LINECAP_ROUND)").Append(__c.CRLF);
 //BA.debugLineNum = 356;BA.debugLine="code6.Append(\"   cont.strokeStyleColor(\"\"#888888\"";
_code6.Append("   cont.strokeStyleColor(\"#888888\")").Append(__c.CRLF);
 //BA.debugLineNum = 357;BA.debugLine="code6.Append(\"   cont.moveTo(20,47)\").Append(CRLF";
_code6.Append("   cont.moveTo(20,47)").Append(__c.CRLF);
 //BA.debugLineNum = 358;BA.debugLine="code6.Append(\"   cont.lineTo(1004,47)\").Append(CR";
_code6.Append("   cont.lineTo(1004,47)").Append(__c.CRLF);
 //BA.debugLineNum = 359;BA.debugLine="code6.Append(\"   cont.stroke\").Append(CRLF)";
_code6.Append("   cont.stroke").Append(__c.CRLF);
 //BA.debugLineNum = 360;BA.debugLine="code6.Append(\"   Return cont\").Append(CRLF)";
_code6.Append("   Return cont").Append(__c.CRLF);
 //BA.debugLineNum = 361;BA.debugLine="code6.Append(\"End Sub\").Append(CRLF)";
_code6.Append("End Sub").Append(__c.CRLF);
 //BA.debugLineNum = 362;BA.debugLine="code6.Append(\"\").Append(CRLF)";
_code6.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 363;BA.debugLine="code6.Append(\"Sub BuildControlCircle() As ABMCanv";
_code6.Append("Sub BuildControlCircle() As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 364;BA.debugLine="code6.Append(\"   Dim cont As ABMCanvasObject\").Ap";
_code6.Append("   Dim cont As ABMCanvasObject").Append(__c.CRLF);
 //BA.debugLineNum = 365;BA.debugLine="code6.Append(\"   cont.InitializeAsCircle(page, \"\"";
_code6.Append("   cont.InitializeAsCircle(page, \"contcirc\", 50,48,40, True)").Append(__c.CRLF);
 //BA.debugLineNum = 366;BA.debugLine="code6.Append(\"   // here we restrict the movement";
_code6.Append("   // here we restrict the movement of the control so it only can me moved on the X-Axis ").Append(__c.CRLF);
 //BA.debugLineNum = 367;BA.debugLine="code6.Append(\"   cont.SetDragZone(50,48,924,1)\").";
_code6.Append("   cont.SetDragZone(50,48,924,1)").Append(__c.CRLF);
 //BA.debugLineNum = 368;BA.debugLine="code6.Append(\"\").Append(CRLF)";
_code6.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 369;BA.debugLine="code6.Append(\"   cont.beginPath\").Append(CRLF)";
_code6.Append("   cont.beginPath").Append(__c.CRLF);
 //BA.debugLineNum = 370;BA.debugLine="code6.Append(\"   cont.arc(0,0,40, 0, 2*cPI)\").App";
_code6.Append("   cont.arc(0,0,40, 0, 2*cPI)").Append(__c.CRLF);
 //BA.debugLineNum = 371;BA.debugLine="code6.Append(\"   cont.fillStyleColor(\"\"#000000\"\")";
_code6.Append("   cont.fillStyleColor(\"#000000\")").Append(__c.CRLF);
 //BA.debugLineNum = 372;BA.debugLine="code6.Append(\"   cont.fill\").Append(CRLF)";
_code6.Append("   cont.fill").Append(__c.CRLF);
 //BA.debugLineNum = 373;BA.debugLine="code6.Append(\"   cont.save\").Append(CRLF)";
_code6.Append("   cont.save").Append(__c.CRLF);
 //BA.debugLineNum = 374;BA.debugLine="code6.Append(\"   cont.translate(-40,-40)\").Append";
_code6.Append("   cont.translate(-40,-40)").Append(__c.CRLF);
 //BA.debugLineNum = 375;BA.debugLine="code6.Append(\"   cont.drawImage3(\"\"eric\"\", 0,0,14";
_code6.Append("   cont.drawImage3(\"eric\", 0,0,147,135,5,5, 70,64)").Append(__c.CRLF);
 //BA.debugLineNum = 376;BA.debugLine="code6.Append(\"   cont.closePath\").Append(CRLF)";
_code6.Append("   cont.closePath").Append(__c.CRLF);
 //BA.debugLineNum = 377;BA.debugLine="code6.Append(\"   cont.restore\").Append(CRLF)";
_code6.Append("   cont.restore").Append(__c.CRLF);
 //BA.debugLineNum = 378;BA.debugLine="code6.Append(\"   Return cont\").Append(CRLF)";
_code6.Append("   Return cont").Append(__c.CRLF);
 //BA.debugLineNum = 379;BA.debugLine="code6.Append(\"End Sub\").Append(CRLF)";
_code6.Append("End Sub").Append(__c.CRLF);
 //BA.debugLineNum = 380;BA.debugLine="code6.Append(\"\").Append(CRLF)";
_code6.Append("").Append(__c.CRLF);
 //BA.debugLineNum = 381;BA.debugLine="code6.Append(\"Sub canvas3_ObjectUp(objectId As St";
_code6.Append("Sub canvas3_ObjectUp(objectId As String)").Append(__c.CRLF);
 //BA.debugLineNum = 382;BA.debugLine="code6.Append(\"   // calculate value from position";
_code6.Append("   // calculate value from position").Append(__c.CRLF);
 //BA.debugLineNum = 383;BA.debugLine="code6.Append(\"   Dim canvas1 As ABMCanvas = page.";
_code6.Append("   Dim canvas1 As ABMCanvas = page.Component(\"canvas3\")").Append(__c.CRLF);
 //BA.debugLineNum = 384;BA.debugLine="code6.Append(\"   Dim Eric As ABMCanvasObject = ca";
_code6.Append("   Dim Eric As ABMCanvasObject = canvas1.GetObject(objectId)").Append(__c.CRLF);
 //BA.debugLineNum = 385;BA.debugLine="code6.Append(\"   Dim Pos As ABMPoint = Eric.GetPo";
_code6.Append("   Dim Pos As ABMPoint = Eric.GetPosition").Append(__c.CRLF);
 //BA.debugLineNum = 386;BA.debugLine="code6.Append(\"   If Pos <> Null Then\").Append(CRL";
_code6.Append("   If Pos <> Null Then").Append(__c.CRLF);
 //BA.debugLineNum = 387;BA.debugLine="code6.Append(\"     // map to 0 to 100: (our posit";
_code6.Append("     // map to 0 to 100: (our position - the dragzone left)/(dragzone width)*100").Append(__c.CRLF);
 //BA.debugLineNum = 388;BA.debugLine="code6.Append(\"   	Dim value As Int = (Pos.x-50)/9";
_code6.Append("   	Dim value As Int = (Pos.x-50)/924*100").Append(__c.CRLF);
 //BA.debugLineNum = 389;BA.debugLine="code6.Append(\"   	myToastId = myToastId + 1\").App";
_code6.Append("   	myToastId = myToastId + 1").Append(__c.CRLF);
 //BA.debugLineNum = 390;BA.debugLine="code6.Append(\"   	page.ShowToast(\"\"toast\"\" & myTo";
_code6.Append("   	page.ShowToast(\"toast\" & myToastId, \"toastred\", \"Eric is at value \" & value, 5000)").Append(__c.CRLF);
 //BA.debugLineNum = 391;BA.debugLine="code6.Append(\"   End If\").Append(CRLF)";
_code6.Append("   End If").Append(__c.CRLF);
 //BA.debugLineNum = 392;BA.debugLine="code6.Append(\"End Sub\").Append(CRLF)";
_code6.Append("End Sub").Append(__c.CRLF);
 //BA.debugLineNum = 394;BA.debugLine="page.Cell(11,1).AddComponent(ABMShared.BuildCodeB";
_page.Cell((int) (11),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildcodeblock(_page,"code6",_code6)));
 //BA.debugLineNum = 397;BA.debugLine="ABMShared.ConnectFooter(page)";
_abmshared._connectfooter(_page);
 //BA.debugLineNum = 399;BA.debugLine="page.Refresh ' IMPORTANT";
_page.Refresh();
 //BA.debugLineNum = 402;BA.debugLine="page.FinishedLoading 'IMPORTANT";
_page.FinishedLoading();
 //BA.debugLineNum = 404;BA.debugLine="page.RestoreNavigationBarPosition";
_page.RestoreNavigationBarPosition();
 //BA.debugLineNum = 405;BA.debugLine="End Sub";
return "";
}
public String  _initialize(anywheresoftware.b4a.BA _ba) throws Exception{
innerInitialize(_ba);
 //BA.debugLineNum = 20;BA.debugLine="Public Sub Initialize";
 //BA.debugLineNum = 22;BA.debugLine="BuildPage";
_buildpage();
 //BA.debugLineNum = 23;BA.debugLine="End Sub";
return "";
}
public String  _page_navigationbarclicked(String _action,String _value) throws Exception{
 //BA.debugLineNum = 408;BA.debugLine="Sub Page_NavigationbarClicked(Action As String, Va";
 //BA.debugLineNum = 409;BA.debugLine="page.SaveNavigationBarPosition";
_page.SaveNavigationBarPosition();
 //BA.debugLineNum = 410;BA.debugLine="If Action = \"ABMCanvas\" Then Return";
if ((_action).equals("ABMCanvas")) { 
if (true) return "";};
 //BA.debugLineNum = 411;BA.debugLine="If Action = \"Contact\" Then";
if ((_action).equals("Contact")) { 
 //BA.debugLineNum = 412;BA.debugLine="myToastId = myToastId + 1";
_mytoastid = (int) (_mytoastid+1);
 //BA.debugLineNum = 413;BA.debugLine="page.ShowToast(\"toast\" & myToastId, \"toastred\",";
_page.ShowToast("toast"+BA.NumberToString(_mytoastid),"toastred","Hello to you too!",(int) (5000));
 //BA.debugLineNum = 414;BA.debugLine="Return";
if (true) return "";
 };
 //BA.debugLineNum = 416;BA.debugLine="If Action = \"LogOff\" Then";
if ((_action).equals("LogOff")) { 
 //BA.debugLineNum = 417;BA.debugLine="ABMShared.LogOff(page)";
_abmshared._logoff(_page);
 //BA.debugLineNum = 418;BA.debugLine="Return";
if (true) return "";
 };
 //BA.debugLineNum = 420;BA.debugLine="ABMShared.NavigateToPage(ws, ABMPageId, Value)";
_abmshared._navigatetopage(_ws,_abmpageid,_value);
 //BA.debugLineNum = 421;BA.debugLine="End Sub";
return "";
}
public String  _page_parseevent(anywheresoftware.b4a.objects.collections.Map _params) throws Exception{
String _eventname = "";
String[] _eventparams = null;
anywheresoftware.b4a.objects.collections.List _passedtables = null;
 //BA.debugLineNum = 57;BA.debugLine="Sub Page_ParseEvent(Params As Map)";
 //BA.debugLineNum = 58;BA.debugLine="Dim eventName As String = Params.Get(\"eventname\")";
_eventname = BA.ObjectToString(_params.Get((Object)("eventname")));
 //BA.debugLineNum = 59;BA.debugLine="Dim eventParams() As String = Regex.Split(\",\",Par";
_eventparams = __c.Regex.Split(",",BA.ObjectToString(_params.Get((Object)("eventparams"))));
 //BA.debugLineNum = 60;BA.debugLine="If eventName = \"beforeunload\" Then";
if ((_eventname).equals("beforeunload")) { 
 //BA.debugLineNum = 61;BA.debugLine="Log(\"preparing for url refresh\")";
__c.Log("preparing for url refresh");
 //BA.debugLineNum = 62;BA.debugLine="ABM.RemoveMeFromCache(ABMShared.CachedPages, ABM";
_abm.RemoveMeFromCache(_abmshared._cachedpages,_abmpageid);
 //BA.debugLineNum = 63;BA.debugLine="Return";
if (true) return "";
 };
 //BA.debugLineNum = 65;BA.debugLine="If SubExists(Me, eventName) Then";
if (__c.SubExists(ba,this,_eventname)) { 
 //BA.debugLineNum = 66;BA.debugLine="Params.Remove(\"eventname\")";
_params.Remove((Object)("eventname"));
 //BA.debugLineNum = 67;BA.debugLine="Params.Remove(\"eventparams\")";
_params.Remove((Object)("eventparams"));
 //BA.debugLineNum = 68;BA.debugLine="Select Case Params.Size";
switch (BA.switchObjectToInt(_params.getSize(),(int) (0),(int) (1),(int) (2))) {
case 0: {
 //BA.debugLineNum = 70;BA.debugLine="CallSub(Me, eventName)";
__c.CallSubNew(ba,this,_eventname);
 break; }
case 1: {
 //BA.debugLineNum = 72;BA.debugLine="CallSub2(Me, eventName, Params.Get(eventParams";
__c.CallSubNew2(ba,this,_eventname,_params.Get((Object)(_eventparams[(int) (0)])));
 break; }
case 2: {
 //BA.debugLineNum = 74;BA.debugLine="If Params.get(eventParams(0)) = \"abmistable\" T";
if ((_params.Get((Object)(_eventparams[(int) (0)]))).equals((Object)("abmistable"))) { 
 //BA.debugLineNum = 75;BA.debugLine="Dim PassedTables As List = ABM.ProcessTablesF";
_passedtables = new anywheresoftware.b4a.objects.collections.List();
_passedtables = _abm.ProcessTablesFromTargetName(BA.ObjectToString(_params.Get((Object)(_eventparams[(int) (1)]))));
 //BA.debugLineNum = 76;BA.debugLine="CallSub2(Me, eventName, PassedTables)";
__c.CallSubNew2(ba,this,_eventname,(Object)(_passedtables));
 }else {
 //BA.debugLineNum = 78;BA.debugLine="CallSub3(Me, eventName, Params.Get(eventParam";
__c.CallSubNew3(ba,this,_eventname,_params.Get((Object)(_eventparams[(int) (0)])),_params.Get((Object)(_eventparams[(int) (1)])));
 };
 break; }
default: {
 //BA.debugLineNum = 82;BA.debugLine="CallSub2(Me, eventName, Params)";
__c.CallSubNew2(ba,this,_eventname,(Object)(_params));
 break; }
}
;
 };
 //BA.debugLineNum = 85;BA.debugLine="End Sub";
return "";
}
public String  _page_signedoffsocialnetwork(String _network,String _extra) throws Exception{
 //BA.debugLineNum = 423;BA.debugLine="Sub Page_SignedOffSocialNetwork(Network As String,";
 //BA.debugLineNum = 424;BA.debugLine="page.ws.Session.SetAttribute(\"authType\", \"\")";
_page.ws.getSession().SetAttribute("authType",(Object)(""));
 //BA.debugLineNum = 425;BA.debugLine="page.ws.Session.SetAttribute(\"authName\", \"\")";
_page.ws.getSession().SetAttribute("authName",(Object)(""));
 //BA.debugLineNum = 426;BA.debugLine="page.ws.Session.SetAttribute(\"IsAuthorized\", \"\")";
_page.ws.getSession().SetAttribute("IsAuthorized",(Object)(""));
 //BA.debugLineNum = 427;BA.debugLine="ABMShared.NavigateToPage(ws, ABMPageId, \"../\")";
_abmshared._navigatetopage(_ws,_abmpageid,"../");
 //BA.debugLineNum = 428;BA.debugLine="End Sub";
return "";
}
public String  _websocket_connected(anywheresoftware.b4j.object.WebSocket _websocket1) throws Exception{
anywheresoftware.b4j.object.HttpSessionWrapper _session = null;
 //BA.debugLineNum = 25;BA.debugLine="Private Sub WebSocket_Connected (WebSocket1 As Web";
 //BA.debugLineNum = 26;BA.debugLine="Log(\"Connected\")";
__c.Log("Connected");
 //BA.debugLineNum = 27;BA.debugLine="ws = WebSocket1";
_ws = _websocket1;
 //BA.debugLineNum = 28;BA.debugLine="ABMPageId = ABM.GetPageID(page, Name,ws)";
_abmpageid = _abm.GetPageID(_page,_name,_ws);
 //BA.debugLineNum = 29;BA.debugLine="Dim session As HttpSession = ABM.GetSession(ws, A";
_session = new anywheresoftware.b4j.object.HttpSessionWrapper();
_session = _abm.GetSession(_ws,_abmshared._sessionmaxinactiveintervalseconds);
 //BA.debugLineNum = 31;BA.debugLine="If ABMShared.NeedsAuthorization Then";
if (_abmshared._needsauthorization) { 
 //BA.debugLineNum = 32;BA.debugLine="If session.GetAttribute2(\"IsAuthorized\", \"\") = \"";
if ((_session.GetAttribute2("IsAuthorized",(Object)(""))).equals((Object)(""))) { 
 //BA.debugLineNum = 33;BA.debugLine="ABMShared.NavigateToPage(ws, ABMPageId, \"../\")";
_abmshared._navigatetopage(_ws,_abmpageid,"../");
 //BA.debugLineNum = 34;BA.debugLine="Return";
if (true) return "";
 };
 };
 //BA.debugLineNum = 38;BA.debugLine="ABM.UpdateFromCache(Me, ABMShared.CachedPages, AB";
_abm.UpdateFromCache((anywheresoftware.b4a.B4AClass)(this),_abmshared._cachedpages,_abmpageid,_ws,ba);
 //BA.debugLineNum = 39;BA.debugLine="If page.ComesFromPageCache Then";
if (_page.ComesFromPageCache) { 
 //BA.debugLineNum = 41;BA.debugLine="page.Refresh";
_page.Refresh();
 //BA.debugLineNum = 43;BA.debugLine="page.FinishedLoading";
_page.FinishedLoading();
 }else {
 //BA.debugLineNum = 46;BA.debugLine="page.Prepare";
_page.Prepare();
 //BA.debugLineNum = 48;BA.debugLine="ConnectPage";
_connectpage();
 };
 //BA.debugLineNum = 50;BA.debugLine="Log(ABMPageId)";
__c.Log(_abmpageid);
 //BA.debugLineNum = 51;BA.debugLine="End Sub";
return "";
}
public String  _websocket_disconnected() throws Exception{
 //BA.debugLineNum = 53;BA.debugLine="Private Sub WebSocket_Disconnected";
 //BA.debugLineNum = 54;BA.debugLine="Log(\"Disconnected\")";
__c.Log("Disconnected");
 //BA.debugLineNum = 55;BA.debugLine="End Sub";
return "";
}
public Object callSub(String sub, Object sender, Object[] args) throws Exception {
BA.senderHolder.set(sender);
return BA.SubDelegator.SubNotFound;
}
}
