package abmaterial.ab.com;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.B4AClass;
import anywheresoftware.b4a.debug.*;

public class compchartpage extends B4AClass.ImplB4AClass implements BA.SubDelegator{
    public static java.util.HashMap<String, java.lang.reflect.Method> htSubs;
    private void innerInitialize(BA _ba) throws Exception {
        if (ba == null) {
            ba = new  anywheresoftware.b4a.StandardBA("abmaterial.ab.com", "abmaterial.ab.com.compchartpage", this);
            if (htSubs == null) {
                ba.loadHtSubs(this.getClass());
                htSubs = ba.htSubs;
            }
            ba.htSubs = htSubs;
             
        }
        if (BA.isShellModeRuntimeCheck(ba))
                this.getClass().getMethod("_class_globals", abmaterial.ab.com.compchartpage.class).invoke(this, new Object[] {null});
        else
            ba.raiseEvent2(null, true, "class_globals", false);
    }

 public anywheresoftware.b4a.keywords.Common __c = null;
public anywheresoftware.b4j.object.WebSocket _ws = null;
public com.ab.abmaterial.ABMPage _page = null;
public com.ab.abmaterial.ABMTheme _theme = null;
public com.ab.abmaterial.ABMaterial _abm = null;
public String _name = "";
public String _abmpageid = "";
public int _mytoastid = 0;
public anywheresoftware.b4a.objects.collections.List _currentvalues = null;
public anywheresoftware.b4a.objects.collections.List _currentlabels = null;
public anywheresoftware.b4a.objects.Timer _temperaturetimer = null;
public abmaterial.ab.com.testclassforalain _atest = null;
public b4j.example.dateutils _dateutils = null;
public abmaterial.ab.com.main _main = null;
public abmaterial.ab.com.abmshared _abmshared = null;
public abmaterial.ab.com.abmprint _abmprint = null;
public String  _btn1_clicked(String _target) throws Exception{
com.ab.abmaterial.ABMChart _chart2 = null;
 //BA.debugLineNum = 462;BA.debugLine="Sub btn1_Clicked(Target As String)";
 //BA.debugLineNum = 463;BA.debugLine="Dim chart2 As ABMChart = page.Component(\"chart2\")";
_chart2 = (com.ab.abmaterial.ABMChart)(_page.Component("chart2"));
 //BA.debugLineNum = 464;BA.debugLine="chart2.ResetZoom";
_chart2.ResetZoom();
 //BA.debugLineNum = 465;BA.debugLine="End Sub";
return "";
}
public String  _buildpage() throws Exception{
 //BA.debugLineNum = 126;BA.debugLine="public Sub BuildPage()";
 //BA.debugLineNum = 128;BA.debugLine="BuildTheme";
_buildtheme();
 //BA.debugLineNum = 131;BA.debugLine="page.InitializeWithTheme(Name, \"/ws/\" & ABMshared";
_page.InitializeWithTheme(_name,"/ws/"+_abmshared._appname+"/"+_name,__c.False,_abmshared._sessionmaxinactiveintervalseconds,_theme);
 //BA.debugLineNum = 132;BA.debugLine="page.ShowLoader=True";
_page.setShowLoader(__c.True);
 //BA.debugLineNum = 133;BA.debugLine="page.ShowLoaderType=ABM.LOADER_TYPE_MANUAL ' NEW";
_page.setShowLoaderType(_abm.LOADER_TYPE_MANUAL);
 //BA.debugLineNum = 134;BA.debugLine="page.PageTitle = \"ABMChart\"";
_page.PageTitle = "ABMChart";
 //BA.debugLineNum = 135;BA.debugLine="page.PageDescription = \"The chart component \"";
_page.PageDescription = "The chart component ";
 //BA.debugLineNum = 136;BA.debugLine="page.PageHTMLName = \"abmaterial-chart.html\"";
_page.PageHTMLName = "abmaterial-chart.html";
 //BA.debugLineNum = 137;BA.debugLine="page.PageKeywords = \"ABMaterial, material design,";
_page.PageKeywords = "ABMaterial, material design, B4X, B4J, SEO, framework, search engine optimization";
 //BA.debugLineNum = 138;BA.debugLine="page.PageSiteMapPriority = \"0.50\"";
_page.PageSiteMapPriority = "0.50";
 //BA.debugLineNum = 139;BA.debugLine="page.PageSiteMapFrequency = ABM.SITEMAP_FREQ_MONT";
_page.PageSiteMapFrequency = _abm.SITEMAP_FREQ_MONTHLY;
 //BA.debugLineNum = 140;BA.debugLine="page.UseGoogleAnalytics(ABMShared.TrackingID, Nul";
_page.UseGoogleAnalytics(_abmshared._trackingid,(anywheresoftware.b4a.objects.collections.List) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.List(), (java.util.List)(__c.Null)));
 //BA.debugLineNum = 141;BA.debugLine="page.ShowConnectedIndicator = True";
_page.ShowConnectedIndicator = __c.True;
 //BA.debugLineNum = 144;BA.debugLine="page.AddExtraJavaScriptFile(\"chartist-plugin-axis";
_page.AddExtraJavaScriptFile("chartist-plugin-axistitle.min.js");
 //BA.debugLineNum = 145;BA.debugLine="page.AddExtraJavaScriptFile(\"chartist-plugin-lege";
_page.AddExtraJavaScriptFile("chartist-plugin-legend.js");
 //BA.debugLineNum = 146;BA.debugLine="page.AddExtraJavaScriptFile(\"chartist-plugin-poin";
_page.AddExtraJavaScriptFile("chartist-plugin-pointlabels.min.js");
 //BA.debugLineNum = 147;BA.debugLine="page.AddExtraJavaScriptFile(\"chartist-plugin-zoom";
_page.AddExtraJavaScriptFile("chartist-plugin-zoom.min.js");
 //BA.debugLineNum = 148;BA.debugLine="page.AddExtraCSSFile(\"chartist-plugin-tooltip.css";
_page.AddExtraCSSFile("chartist-plugin-tooltip.css");
 //BA.debugLineNum = 149;BA.debugLine="page.AddExtraJavaScriptFile(\"chartist-plugin-tool";
_page.AddExtraJavaScriptFile("chartist-plugin-tooltip.min.js");
 //BA.debugLineNum = 151;BA.debugLine="ABMShared.BuildNavigationBar(page, \"ABMChart\", \".";
_abmshared._buildnavigationbar(_page,"ABMChart","../images/logo.png","","Controls","ABMChart");
 //BA.debugLineNum = 154;BA.debugLine="page.AddRows(9,True, \"\").AddCells12(1,\"\")";
_page.AddRows((int) (9),__c.True,"").AddCells12((int) (1),"");
 //BA.debugLineNum = 155;BA.debugLine="page.AddRows(1,True, \"\").AddCellsOS(2,1,1,1,8,4,4";
_page.AddRows((int) (1),__c.True,"").AddCellsOS((int) (2),(int) (1),(int) (1),(int) (1),(int) (8),(int) (4),(int) (4),"");
 //BA.debugLineNum = 156;BA.debugLine="page.AddRows(2,True, \"\").AddCells12(1,\"\")";
_page.AddRows((int) (2),__c.True,"").AddCells12((int) (1),"");
 //BA.debugLineNum = 157;BA.debugLine="page.BuildGrid 'IMPORTANT once you loaded the com";
_page.BuildGrid();
 //BA.debugLineNum = 159;BA.debugLine="ABMShared.BuildFooter(page)";
_abmshared._buildfooter(_page);
 //BA.debugLineNum = 160;BA.debugLine="End Sub";
return "";
}
public String  _buildtheme() throws Exception{
 //BA.debugLineNum = 99;BA.debugLine="public Sub BuildTheme()";
 //BA.debugLineNum = 101;BA.debugLine="theme.Initialize(\"pagetheme\")";
_theme.Initialize("pagetheme");
 //BA.debugLineNum = 102;BA.debugLine="theme.AddABMTheme(ABMShared.MyTheme)";
_theme.AddABMTheme(_abmshared._mytheme);
 //BA.debugLineNum = 105;BA.debugLine="theme.AddChartTheme(\"chart1theme\")";
_theme.AddChartTheme("chart1theme");
 //BA.debugLineNum = 106;BA.debugLine="theme.Chart(\"chart1theme\").Serie(ABM.CHART_SERIEI";
_theme.Chart("chart1theme").Serie(_abm.CHART_SERIEINDEX_C).LinePointStrokeWidthPx = (int) (8);
 //BA.debugLineNum = 107;BA.debugLine="theme.Chart(\"chart1theme\").Serie(ABM.CHART_SERIEI";
_theme.Chart("chart1theme").Serie(_abm.CHART_SERIEINDEX_C).LineStrokeWidthPx = (int) (5);
 //BA.debugLineNum = 109;BA.debugLine="theme.AddChartTheme(\"chart2theme\")";
_theme.AddChartTheme("chart2theme");
 //BA.debugLineNum = 110;BA.debugLine="theme.Chart(\"chart2theme\").ZDepth = ABM.ZDEPTH_1";
_theme.Chart("chart2theme").ZDepth = _abm.ZDEPTH_1;
 //BA.debugLineNum = 111;BA.debugLine="theme.Chart(\"chart2theme\").BackColor = ABM.COLOR_";
_theme.Chart("chart2theme").BackColor = _abm.COLOR_WHITE;
 //BA.debugLineNum = 113;BA.debugLine="theme.AddChartTheme(\"chart4theme\")";
_theme.AddChartTheme("chart4theme");
 //BA.debugLineNum = 114;BA.debugLine="theme.Chart(\"chart4theme\").ZDepth = ABM.ZDEPTH_1";
_theme.Chart("chart4theme").ZDepth = _abm.ZDEPTH_1;
 //BA.debugLineNum = 115;BA.debugLine="theme.Chart(\"chart4theme\").BackColor = ABM.COLOR_";
_theme.Chart("chart4theme").BackColor = _abm.COLOR_WHITE;
 //BA.debugLineNum = 116;BA.debugLine="theme.Chart(\"chart4theme\").Serie(ABM.CHART_SERIEI";
_theme.Chart("chart4theme").Serie(_abm.CHART_SERIEINDEX_A).BarStrokeWidthPx = (int) (25);
 //BA.debugLineNum = 117;BA.debugLine="theme.Chart(\"chart4theme\").Serie(ABM.CHART_SERIEI";
_theme.Chart("chart4theme").Serie(_abm.CHART_SERIEINDEX_A).Color = _abm.COLOR_AMBER;
 //BA.debugLineNum = 118;BA.debugLine="theme.Chart(\"chart4theme\").Serie(ABM.CHART_SERIEI";
_theme.Chart("chart4theme").Serie(_abm.CHART_SERIEINDEX_B).BarStrokeWidthPx = (int) (25);
 //BA.debugLineNum = 119;BA.debugLine="theme.Chart(\"chart4theme\").Serie(ABM.CHART_SERIEI";
_theme.Chart("chart4theme").Serie(_abm.CHART_SERIEINDEX_B).Color = _abm.COLOR_ORANGE;
 //BA.debugLineNum = 121;BA.debugLine="theme.AddChartTheme(\"chart5theme\")";
_theme.AddChartTheme("chart5theme");
 //BA.debugLineNum = 122;BA.debugLine="theme.Chart(\"chart5theme\").LabelColor = ABM.COLOR";
_theme.Chart("chart5theme").LabelColor = _abm.COLOR_WHITE;
 //BA.debugLineNum = 124;BA.debugLine="End Sub";
return "";
}
public String  _class_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Class_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Private ws As WebSocket 'ignore";
_ws = new anywheresoftware.b4j.object.WebSocket();
 //BA.debugLineNum = 5;BA.debugLine="Public page As ABMPage";
_page = new com.ab.abmaterial.ABMPage();
 //BA.debugLineNum = 7;BA.debugLine="Private theme As ABMTheme";
_theme = new com.ab.abmaterial.ABMTheme();
 //BA.debugLineNum = 9;BA.debugLine="Private ABM As ABMaterial 'ignore";
_abm = new com.ab.abmaterial.ABMaterial();
 //BA.debugLineNum = 11;BA.debugLine="Public Name As String = \"CompChartPage\"";
_name = "CompChartPage";
 //BA.debugLineNum = 13;BA.debugLine="Private ABMPageId As String = \"\"";
_abmpageid = "";
 //BA.debugLineNum = 16;BA.debugLine="Dim myToastId As Int";
_mytoastid = 0;
 //BA.debugLineNum = 17;BA.debugLine="Dim CurrentValues As List";
_currentvalues = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 18;BA.debugLine="Dim CurrentLabels As List";
_currentlabels = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 19;BA.debugLine="Dim TemperatureTimer As Timer";
_temperaturetimer = new anywheresoftware.b4a.objects.Timer();
 //BA.debugLineNum = 21;BA.debugLine="Dim ATest As TestClassForAlain 'ignore";
_atest = new abmaterial.ab.com.testclassforalain();
 //BA.debugLineNum = 22;BA.debugLine="End Sub";
return "";
}
public String  _connectpage() throws Exception{
com.ab.abmaterial.ABMChart _chart1 = null;
com.ab.abmaterial.ABMChartSerie _seriea = null;
com.ab.abmaterial.ABMChartSerie _seriec = null;
com.ab.abmaterial.ABMChart _chart2 = null;
com.ab.abmaterial.ABMChartSerie _serie2a = null;
com.ab.abmaterial.ABMChartSerie _serie2b = null;
com.ab.abmaterial.ABMChartSerie _serie2c = null;
com.ab.abmaterial.ABMChartSerie _serie2d = null;
com.ab.abmaterial.ABMButton _btn1 = null;
com.ab.abmaterial.ABMChart _chart3 = null;
com.ab.abmaterial.ABMChartSerie _serie3a = null;
com.ab.abmaterial.ABMChartSerie _serie3b = null;
com.ab.abmaterial.ABMChart _chart4 = null;
com.ab.abmaterial.ABMChartSerie _serie4a = null;
com.ab.abmaterial.ABMChartSerie _serie4b = null;
com.ab.abmaterial.ABMChart _chart5 = null;
int _sumvalues = 0;
com.ab.abmaterial.ABMChartSerie _serie5a = null;
com.ab.abmaterial.ABMChart _chart6 = null;
com.ab.abmaterial.ABMChartSerie _serie6a = null;
com.ab.abmaterial.ABMChart _chart7 = null;
com.ab.abmaterial.ABMChartSerie _serie7a = null;
 //BA.debugLineNum = 162;BA.debugLine="Sub ConnectPage()";
 //BA.debugLineNum = 164;BA.debugLine="ABMShared.ConnectNavigationBar(page)";
_abmshared._connectnavigationbar(_page);
 //BA.debugLineNum = 170;BA.debugLine="page.CellR(0,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par1","ABMaterial can create several types of charts. Because of the nature of responsive design it's important to understand that blocks in design like images, videos and similar content need to be able to scale and adapt to the media. In order for an element to scale, you need to rely on a certain aspect ratios (like 4:3, 3:2, 16:9 etc.) rather than specifying a fixed width and height.")));
 //BA.debugLineNum = 172;BA.debugLine="page.CellR(0,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par5","To designers this Idea is absolutely not new, but to developers this might be at first. However, when a designer talks to a developer about the images being 320x240 on this page and 300x200 on that element, he actually just translated his idea of using 4:3 and 3:2 images into pixels.{BR}{BR}With ABMaterial you can specify those ratios directly on charts without the need To calculate any fixed dimensions. In order To create a chart that Is using the aspect ratio of a golden section you can just use the constant ABM.CHART_RATIO_GOLDENSECTION in the Initialize.")));
 //BA.debugLineNum = 174;BA.debugLine="page.CellR(0,1).AddComponent(ABMShared.BuildHeade";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildheader(_page,"hdr1","Line Charts")));
 //BA.debugLineNum = 176;BA.debugLine="page.CellR(0,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par6","The ABMaterial line chart can be used to draw Line or Scatter charts. Use the constant ABM.CHART_NULLVALUE when you want to make holes in the data.")));
 //BA.debugLineNum = 180;BA.debugLine="Dim chart1 As ABMChart";
_chart1 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 181;BA.debugLine="chart1.Initialize(page, \"chart1\", ABM.CHART_TYPEL";
_chart1.Initialize(_page,"chart1",_abm.CHART_TYPELINE,_abm.CHART_RATIO_GOLDENSECTION,"chart1theme");
 //BA.debugLineNum = 184;BA.debugLine="chart1.AddLabels(Array As String(\"Mon\", \"The\", \"W";
_chart1.AddLabels(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"Mon","The","Wed","Thu","Fri","Sat","Sun"}));
 //BA.debugLineNum = 186;BA.debugLine="chart1.OptionsLine.FullWidth=True";
_chart1.OptionsLine().FullWidth = __c.True;
 //BA.debugLineNum = 187;BA.debugLine="chart1.OptionsLine.ChartPaddingRight=60 ' because";
_chart1.OptionsLine().ChartPaddingRight = (int) (60);
 //BA.debugLineNum = 188;BA.debugLine="chart1.OptionsLine.Serie(ABM.CHART_SERIEINDEX_A).";
_chart1.OptionsLine().Serie(_abm.CHART_SERIEINDEX_A).LineSmooth = _abm.CHART_LINESMOOTH_NONE;
 //BA.debugLineNum = 189;BA.debugLine="chart1.OptionsLine.Serie(ABM.CHART_SERIEINDEX_C).";
_chart1.OptionsLine().Serie(_abm.CHART_SERIEINDEX_C).LineSmooth = _abm.CHART_LINESMOOTH_SIMPLE;
 //BA.debugLineNum = 190;BA.debugLine="chart1.OptionsLine.Serie(ABM.CHART_SERIEINDEX_C).";
_chart1.OptionsLine().Serie(_abm.CHART_SERIEINDEX_C).ShowArea = __c.True;
 //BA.debugLineNum = 191;BA.debugLine="chart1.AddPluginDefinition(\"Chartist.plugins.ctPo";
_chart1.AddPluginDefinition("Chartist.plugins.ctPointLabels({textAnchor: 'middle'})");
 //BA.debugLineNum = 194;BA.debugLine="Dim SerieA As ABMChartSerie";
_seriea = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 195;BA.debugLine="SerieA.InitializeForLine(ABM.CHART_SERIEINDEX_A)";
_seriea.InitializeForLine(_abm.CHART_SERIEINDEX_A);
 //BA.debugLineNum = 196;BA.debugLine="SerieA.SetValues(Array As Int(30,50,70,80,ABM.CHA";
_seriea.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (30),(int) (50),(int) (70),(int) (80),_abm.CHART_NULLVALUE,(int) (140),(int) (170)}));
 //BA.debugLineNum = 197;BA.debugLine="chart1.AddSerie(SerieA)";
_chart1.AddSerie(_seriea);
 //BA.debugLineNum = 199;BA.debugLine="Dim SerieC As ABMChartSerie";
_seriec = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 200;BA.debugLine="SerieC.InitializeForLine(ABM.CHART_SERIEINDEX_C)";
_seriec.InitializeForLine(_abm.CHART_SERIEINDEX_C);
 //BA.debugLineNum = 201;BA.debugLine="SerieC.SetValues(Array As Int(100,120,180,150,190";
_seriec.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (100),(int) (120),(int) (180),(int) (150),(int) (190),(int) (100),(int) (70)}));
 //BA.debugLineNum = 202;BA.debugLine="chart1.AddSerie(SerieC)";
_chart1.AddSerie(_seriec);
 //BA.debugLineNum = 206;BA.debugLine="page.CellR(1,1).AddComponent(chart1)";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart1));
 //BA.debugLineNum = 210;BA.debugLine="page.CellR(1,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par2","Line Charts are very tunable through Theme and OptionsLine. You can modify the look and feel on the chart and on individual lines.  Charts can use up to 15 'Series' of data values. A line chart is the only one where you can pick a 'Serie'.  This is due to a hack in the underlying Chartist.js library which does not provide this option.")));
 //BA.debugLineNum = 213;BA.debugLine="Dim chart2 As ABMChart";
_chart2 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 214;BA.debugLine="chart2.Initialize(page, \"chart2\", ABM.CHART_TYPEL";
_chart2.Initialize(_page,"chart2",_abm.CHART_TYPELINE,_abm.CHART_RATIO_GOLDENSECTION,"chart2theme");
 //BA.debugLineNum = 216;BA.debugLine="chart2.OptionsLine.ChartPaddingBottom = 30";
_chart2.OptionsLine().ChartPaddingBottom = (int) (30);
 //BA.debugLineNum = 217;BA.debugLine="chart2.OptionsLine.ChartPaddingTop = 30";
_chart2.OptionsLine().ChartPaddingTop = (int) (30);
 //BA.debugLineNum = 218;BA.debugLine="chart2.OptionsLine.ChartPaddingRight = 130";
_chart2.OptionsLine().ChartPaddingRight = (int) (130);
 //BA.debugLineNum = 219;BA.debugLine="chart2.OptionsLine.AxisYLow=-3 ' must be set if y";
_chart2.OptionsLine().AxisYLow = (int) (-3);
 //BA.debugLineNum = 220;BA.debugLine="chart2.OptionsLine.AxisYHigh=3 ' must be set if y";
_chart2.OptionsLine().AxisYHigh = (int) (3);
 //BA.debugLineNum = 221;BA.debugLine="chart2.OptionsLine.AxisYOnlyInteger=True";
_chart2.OptionsLine().AxisYOnlyInteger = __c.True;
 //BA.debugLineNum = 222;BA.debugLine="chart2.OptionsLine.AxisYAxisType = \"Chartist.Auto";
_chart2.OptionsLine().AxisYAxisType = "Chartist.AutoScaleAxis";
 //BA.debugLineNum = 223;BA.debugLine="chart2.OptionsLine.AxisXLow=10 ' must be set if y";
_chart2.OptionsLine().AxisXLow = (int) (10);
 //BA.debugLineNum = 224;BA.debugLine="chart2.OptionsLine.AxisXHigh=80 ' must be set if";
_chart2.OptionsLine().AxisXHigh = (int) (80);
 //BA.debugLineNum = 225;BA.debugLine="chart2.OptionsLine.AxisXAxisType = \"Chartist.Auto";
_chart2.OptionsLine().AxisXAxisType = "Chartist.AutoScaleAxis";
 //BA.debugLineNum = 226;BA.debugLine="chart2.OptionsLine.AxisXOnlyInteger=True";
_chart2.OptionsLine().AxisXOnlyInteger = __c.True;
 //BA.debugLineNum = 227;BA.debugLine="chart2.OptionsLine.FullWidth=True";
_chart2.OptionsLine().FullWidth = __c.True;
 //BA.debugLineNum = 228;BA.debugLine="chart2.OptionsLine.AxisXShowGrid = True";
_chart2.OptionsLine().AxisXShowGrid = __c.True;
 //BA.debugLineNum = 229;BA.debugLine="chart2.OptionsLine.AxisXShowLabel = True";
_chart2.OptionsLine().AxisXShowLabel = __c.True;
 //BA.debugLineNum = 230;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_A).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_A).LineSmooth = _abm.CHART_LINESMOOTH_SIMPLE;
 //BA.debugLineNum = 231;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_A).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_A).ShowArea = __c.True;
 //BA.debugLineNum = 232;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_A).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_A).ShowLine = __c.False;
 //BA.debugLineNum = 233;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_A).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_A).ShowPoint = __c.False;
 //BA.debugLineNum = 234;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_B).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_B).LineSmooth = _abm.CHART_LINESMOOTH_SIMPLE;
 //BA.debugLineNum = 235;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_B).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_B).ShowArea = __c.True;
 //BA.debugLineNum = 236;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_B).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_B).ShowLine = __c.False;
 //BA.debugLineNum = 237;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_B).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_B).ShowPoint = __c.False;
 //BA.debugLineNum = 238;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_C).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_C).LineSmooth = _abm.CHART_LINESMOOTH_SIMPLE;
 //BA.debugLineNum = 239;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_C).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_C).ShowArea = __c.True;
 //BA.debugLineNum = 240;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_C).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_C).ShowLine = __c.False;
 //BA.debugLineNum = 241;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_C).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_C).ShowPoint = __c.False;
 //BA.debugLineNum = 242;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_D).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_D).LineSmooth = _abm.CHART_LINESMOOTH_SIMPLE;
 //BA.debugLineNum = 243;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_D).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_D).ShowArea = __c.True;
 //BA.debugLineNum = 244;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_D).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_D).ShowLine = __c.True;
 //BA.debugLineNum = 245;BA.debugLine="chart2.OptionsLine.Serie(ABM.CHART_SERIEINDEX_D).";
_chart2.OptionsLine().Serie(_abm.CHART_SERIEINDEX_D).ShowPoint = __c.True;
 //BA.debugLineNum = 246;BA.debugLine="chart2.AddPluginDefinition($\"Chartist.plugins.ctA";
_chart2.AddPluginDefinition(("Chartist.plugins.ctAxisTitle({\n"+"      axisX: {\n"+"        axisTitle: 'Time (mins)',\n"+"        axisClass: 'ct-axis-title',\n"+"        offset: {\n"+"          x: 0,\n"+"          y: 45\n"+"        },\n"+"        textAnchor: 'middle'\n"+"      },\n"+"      axisY: {\n"+"        axisTitle: 'Goals',\n"+"        axisClass: 'ct-axis-title',\n"+"        offset: {\n"+"          x: 0,\n"+"          y: -12\n"+"        },\n"+"        textAnchor: 'middle',\n"+"        flipTitle: false\n"+"      }\n"+"    })"));
 //BA.debugLineNum = 267;BA.debugLine="chart2.AddPluginDefinition(\"Chartist.plugins.lege";
_chart2.AddPluginDefinition("Chartist.plugins.legend({legendNames: ['Blue pill', 'Red pill', 'Green pill', 'Yellow pill'],})");
 //BA.debugLineNum = 268;BA.debugLine="chart2.AddPluginDefinition(\"Chartist.plugins.tool";
_chart2.AddPluginDefinition("Chartist.plugins.tooltip()");
 //BA.debugLineNum = 269;BA.debugLine="chart2.AddPluginDefinition(\"Chartist.plugins.zoom";
_chart2.AddPluginDefinition("Chartist.plugins.zoom({ onZoom : onZoom })");
 //BA.debugLineNum = 272;BA.debugLine="Dim Serie2A As ABMChartSerie";
_serie2a = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 273;BA.debugLine="Serie2A.InitializeForLine(ABM.CHART_SERIEINDEX_A)";
_serie2a.InitializeForLine(_abm.CHART_SERIEINDEX_A);
 //BA.debugLineNum = 274;BA.debugLine="Serie2A.Name = \"Blue pill\"";
_serie2a.Name = "Blue pill";
 //BA.debugLineNum = 275;BA.debugLine="Serie2A.SetValuesXY(Array As Int(10,20,30,40,50,6";
_serie2a.SetValuesXY(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (10),(int) (20),(int) (30),(int) (40),(int) (50),(int) (60),(int) (70),(int) (80)}),anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (1),(int) (2),(int) (3),(int) (1),(int) (-2),(int) (0),(int) (1),(int) (0)}));
 //BA.debugLineNum = 276;BA.debugLine="chart2.AddSerie(Serie2A)";
_chart2.AddSerie(_serie2a);
 //BA.debugLineNum = 278;BA.debugLine="Dim Serie2B As ABMChartSerie";
_serie2b = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 279;BA.debugLine="Serie2B.InitializeForLine(ABM.CHART_SERIEINDEX_B)";
_serie2b.InitializeForLine(_abm.CHART_SERIEINDEX_B);
 //BA.debugLineNum = 280;BA.debugLine="Serie2B.Name = \"Red pill\"";
_serie2b.Name = "Red pill";
 //BA.debugLineNum = 281;BA.debugLine="Serie2B.SetValuesXY(Array As Int(10,20,30,40,50,6";
_serie2b.SetValuesXY(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (10),(int) (20),(int) (30),(int) (40),(int) (50),(int) (60),(int) (70),(int) (80)}),anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (-2),(int) (-1),(int) (-2),(int) (-1),(int) (-2.5),(int) (-1),(int) (-2),(int) (-1)}));
 //BA.debugLineNum = 282;BA.debugLine="chart2.AddSerie(Serie2B)";
_chart2.AddSerie(_serie2b);
 //BA.debugLineNum = 284;BA.debugLine="Dim Serie2C As ABMChartSerie";
_serie2c = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 285;BA.debugLine="Serie2C.InitializeforLine(ABM.CHART_SERIEINDEX_C)";
_serie2c.InitializeForLine(_abm.CHART_SERIEINDEX_C);
 //BA.debugLineNum = 286;BA.debugLine="Serie2C.Name = \"Green pill\"";
_serie2c.Name = "Green pill";
 //BA.debugLineNum = 287;BA.debugLine="Serie2C.SetValuesXY(Array As Int(10,20,30,40,50,6";
_serie2c.SetValuesXY(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (10),(int) (20),(int) (30),(int) (40),(int) (50),(int) (60),(int) (70),(int) (80)}),anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (0),(int) (0),(int) (0),(int) (1),(int) (2),(int) (2.5),(int) (2.),(int) (1)}));
 //BA.debugLineNum = 288;BA.debugLine="chart2.AddSerie(Serie2C)";
_chart2.AddSerie(_serie2c);
 //BA.debugLineNum = 290;BA.debugLine="Dim Serie2D As ABMChartSerie";
_serie2d = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 291;BA.debugLine="Serie2D.InitializeforLine(ABM.CHART_SERIEINDEX_D)";
_serie2d.InitializeForLine(_abm.CHART_SERIEINDEX_D);
 //BA.debugLineNum = 292;BA.debugLine="Serie2D.Name = \"Yellow pill\"";
_serie2d.Name = "Yellow pill";
 //BA.debugLineNum = 293;BA.debugLine="Serie2D.SetValuesXY(Array As Int(10,20,30,40,50,6";
_serie2d.SetValuesXY(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (10),(int) (20),(int) (30),(int) (40),(int) (50),(int) (60),(int) (70),(int) (80)}),anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (2.5),(int) (2),(int) (1),(int) (0.5),(int) (1),(int) (0.5),(int) (-1),(int) (-2.5)}));
 //BA.debugLineNum = 294;BA.debugLine="chart2.AddSerie(Serie2D)";
_chart2.AddSerie(_serie2d);
 //BA.debugLineNum = 298;BA.debugLine="page.CellR(1,1).AddComponent(chart2)";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart2));
 //BA.debugLineNum = 300;BA.debugLine="Dim btn1 As ABMButton";
_btn1 = new com.ab.abmaterial.ABMButton();
 //BA.debugLineNum = 301;BA.debugLine="btn1.InitializeFlat(page, \"btn1\", \"\", \"\", \"Reset";
_btn1.InitializeFlat(_page,"btn1","","","Reset zoom","");
 //BA.debugLineNum = 302;BA.debugLine="page.CellR(0,1).AddComponent(btn1)";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_btn1));
 //BA.debugLineNum = 306;BA.debugLine="page.CellR(1,1).AddComponent(ABMShared.BuildHeade";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildheader(_page,"hdr2","Bar Charts")));
 //BA.debugLineNum = 309;BA.debugLine="page.CellR(0,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par7","A bar chart or bar graph is a chart that presents Grouped data with rectangular bars with lengths proportional to the values that they represent. The bars can be plotted vertically or horizontally. A vertical bar chart is sometimes called a column bar chart.")));
 //BA.debugLineNum = 313;BA.debugLine="Dim chart3 As ABMChart";
_chart3 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 314;BA.debugLine="chart3.Initialize(page, \"chart3\", ABM.CHART_TYPEB";
_chart3.Initialize(_page,"chart3",_abm.CHART_TYPEBAR,_abm.CHART_RATIO_GOLDENSECTION,"");
 //BA.debugLineNum = 316;BA.debugLine="chart3.OptionsBar.AxisYOnlyInteger=True";
_chart3.OptionsBar().AxisYOnlyInteger = __c.True;
 //BA.debugLineNum = 317;BA.debugLine="chart3.OptionsBar.ChartPaddingRight=60";
_chart3.OptionsBar().ChartPaddingRight = (int) (60);
 //BA.debugLineNum = 320;BA.debugLine="chart3.AddLabels(Array As String(\"Mon\", \"The\", \"W";
_chart3.AddLabels(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"Mon","The","Wed","Thu","Fri","Sat","Sun"}));
 //BA.debugLineNum = 323;BA.debugLine="Dim Serie3A As ABMChartSerie";
_serie3a = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 324;BA.debugLine="Serie3A.InitializeForBar";
_serie3a.InitializeForBar();
 //BA.debugLineNum = 325;BA.debugLine="Serie3A.SetValues(Array As Int(30,50,70,80,100,14";
_serie3a.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (30),(int) (50),(int) (70),(int) (80),(int) (100),(int) (140),(int) (170)}));
 //BA.debugLineNum = 326;BA.debugLine="chart3.AddSerie(Serie3A)";
_chart3.AddSerie(_serie3a);
 //BA.debugLineNum = 328;BA.debugLine="Dim Serie3B As ABMChartSerie";
_serie3b = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 329;BA.debugLine="Serie3B.InitializeForBar";
_serie3b.InitializeForBar();
 //BA.debugLineNum = 330;BA.debugLine="Serie3B.SetValues(Array As Int(100,120,180,150,19";
_serie3b.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (100),(int) (120),(int) (180),(int) (150),(int) (190),(int) (100),(int) (70)}));
 //BA.debugLineNum = 331;BA.debugLine="chart3.AddSerie(Serie3B)";
_chart3.AddSerie(_serie3b);
 //BA.debugLineNum = 335;BA.debugLine="page.CellR(1,1).AddComponent(chart3)";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart3));
 //BA.debugLineNum = 339;BA.debugLine="page.CellR(1,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par22","Bar Charts can also be tuned using Theme and OptionsBar.")));
 //BA.debugLineNum = 342;BA.debugLine="Dim chart4 As ABMChart";
_chart4 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 343;BA.debugLine="chart4.Initialize(page, \"chart4\", ABM.CHART_TYPEB";
_chart4.Initialize(_page,"chart4",_abm.CHART_TYPEBAR,_abm.CHART_RATIO_GOLDENSECTION,"chart4theme");
 //BA.debugLineNum = 345;BA.debugLine="chart4.OptionsBar.AxisXOnlyInteger=True";
_chart4.OptionsBar().AxisXOnlyInteger = __c.True;
 //BA.debugLineNum = 346;BA.debugLine="chart4.OptionsBar.StackBars = True";
_chart4.OptionsBar().StackBars = __c.True;
 //BA.debugLineNum = 347;BA.debugLine="chart4.OptionsBar.HorizontalBars = True";
_chart4.OptionsBar().HorizontalBars = __c.True;
 //BA.debugLineNum = 348;BA.debugLine="chart4.OptionsBar.ChartPaddingRight=60";
_chart4.OptionsBar().ChartPaddingRight = (int) (60);
 //BA.debugLineNum = 351;BA.debugLine="chart4.AddLabels(Array As String(\"Mon\", \"The\", \"W";
_chart4.AddLabels(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"Mon","The","Wed","Thu","Fri","Sat","Sun"}));
 //BA.debugLineNum = 354;BA.debugLine="Dim Serie4A As ABMChartSerie";
_serie4a = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 355;BA.debugLine="Serie4A.InitializeForBar";
_serie4a.InitializeForBar();
 //BA.debugLineNum = 356;BA.debugLine="Serie4A.SetValues(Array As Int(30,50,70,80,100,14";
_serie4a.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (30),(int) (50),(int) (70),(int) (80),(int) (100),(int) (140),(int) (170)}));
 //BA.debugLineNum = 357;BA.debugLine="chart4.AddSerie(Serie4A)";
_chart4.AddSerie(_serie4a);
 //BA.debugLineNum = 359;BA.debugLine="Dim Serie4B As ABMChartSerie";
_serie4b = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 360;BA.debugLine="Serie4B.InitializeForBar";
_serie4b.InitializeForBar();
 //BA.debugLineNum = 361;BA.debugLine="Serie4B.SetValues(Array As Int(100,120,180,150,19";
_serie4b.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (100),(int) (120),(int) (180),(int) (150),(int) (190),(int) (100),(int) (70)}));
 //BA.debugLineNum = 362;BA.debugLine="chart4.AddSerie(Serie4B)";
_chart4.AddSerie(_serie4b);
 //BA.debugLineNum = 366;BA.debugLine="page.CellR(1,1).AddComponent(chart4)";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart4));
 //BA.debugLineNum = 370;BA.debugLine="page.CellR(1,1).AddComponent(ABMShared.BuildHeade";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildheader(_page,"hdr3","Pie and Donut Charts")));
 //BA.debugLineNum = 373;BA.debugLine="page.CellR(0,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par8","A pie chart (or a circle chart) is a circular statistical graphic, which is divided into slices to illustrate numerical proportion. In a pie chart, the arc length of each slice (and consequently its central angle and area), is proportional to the quantity it represents. While it is named for its resemblance to a pie which has been sliced, there are variations on the way it can be presented. Pie Charts be transformed to Donut charts through the Theme and OptionsPie.")));
 //BA.debugLineNum = 376;BA.debugLine="Dim chart5 As ABMChart";
_chart5 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 377;BA.debugLine="chart5.Initialize(page, \"chart5\", ABM.CHART_TYPEP";
_chart5.Initialize(_page,"chart5",_abm.CHART_TYPEPIE,_abm.CHART_RATIO_SQUARE,"chart5theme");
 //BA.debugLineNum = 379;BA.debugLine="Dim SumValues As Int = 30+50+70+80+100+140+170";
_sumvalues = (int) (30+50+70+80+100+140+170);
 //BA.debugLineNum = 380;BA.debugLine="chart5.OptionsPie.LabelInterpolation = \"Math.roun";
_chart5.OptionsPie().LabelInterpolation = "Math.round(value / "+BA.NumberToString(_sumvalues)+" * 100) + '%'";
 //BA.debugLineNum = 385;BA.debugLine="Dim Serie5A As ABMChartSerie";
_serie5a = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 386;BA.debugLine="Serie5A.InitializeForPie";
_serie5a.InitializeForPie();
 //BA.debugLineNum = 387;BA.debugLine="Serie5A.SetValues(Array As Int(30,50,70,80,100,14";
_serie5a.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (30),(int) (50),(int) (70),(int) (80),(int) (100),(int) (140),(int) (170)}));
 //BA.debugLineNum = 388;BA.debugLine="chart5.AddSerie(Serie5A)";
_chart5.AddSerie(_serie5a);
 //BA.debugLineNum = 392;BA.debugLine="page.CellR(1,1).AddComponent(chart5)";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart5));
 //BA.debugLineNum = 395;BA.debugLine="Dim chart6 As ABMChart";
_chart6 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 396;BA.debugLine="chart6.Initialize(page, \"chart6\", ABM.CHART_TYPEP";
_chart6.Initialize(_page,"chart6",_abm.CHART_TYPEPIE,_abm.CHART_RATIO_SQUARE,"chart5theme");
 //BA.debugLineNum = 397;BA.debugLine="chart6.OptionsPie.IsDonut = True";
_chart6.OptionsPie().IsDonut = __c.True;
 //BA.debugLineNum = 398;BA.debugLine="chart6.OptionsPie.DonutWidth = 80";
_chart6.OptionsPie().DonutWidth = (int) (80);
 //BA.debugLineNum = 399;BA.debugLine="chart6.OptionsPie.StartAngle = 270";
_chart6.OptionsPie().StartAngle = (int) (270);
 //BA.debugLineNum = 400;BA.debugLine="chart6.OptionsPie.Total = 200";
_chart6.OptionsPie().Total = (int) (200);
 //BA.debugLineNum = 402;BA.debugLine="Dim SumValues As Int = 20+10+30+40";
_sumvalues = (int) (20+10+30+40);
 //BA.debugLineNum = 403;BA.debugLine="chart6.OptionsPie.LabelInterpolation = \"Math.roun";
_chart6.OptionsPie().LabelInterpolation = "Math.round(value / "+BA.NumberToString(_sumvalues)+" * 100) + '%'";
 //BA.debugLineNum = 408;BA.debugLine="Dim Serie6A As ABMChartSerie";
_serie6a = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 409;BA.debugLine="Serie6A.InitializeForPie";
_serie6a.InitializeForPie();
 //BA.debugLineNum = 410;BA.debugLine="Serie6A.SetValues(Array As Int(20,10,30,40))";
_serie6a.SetValues(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (20),(int) (10),(int) (30),(int) (40)}));
 //BA.debugLineNum = 411;BA.debugLine="chart6.AddSerie(Serie6A)";
_chart6.AddSerie(_serie6a);
 //BA.debugLineNum = 415;BA.debugLine="page.CellR(0,2).AddComponent(chart6)";
_page.CellR((int) (0),(int) (2)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart6));
 //BA.debugLineNum = 419;BA.debugLine="page.CellR(1,1).AddComponent(ABMShared.BuildHeade";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildheader(_page,"hdr4","Update chart with new values")));
 //BA.debugLineNum = 422;BA.debugLine="page.CellR(0,1).AddComponent(ABMShared.BuildParag";
_page.CellR((int) (0),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_abmshared._buildparagraph(_page,"par3","You can update the charts with new values.  E.g. you can use this to update the chart with real-time telemetry data, like the temperature of a machine.")));
 //BA.debugLineNum = 425;BA.debugLine="Dim chart7 As ABMChart";
_chart7 = new com.ab.abmaterial.ABMChart();
 //BA.debugLineNum = 426;BA.debugLine="chart7.Initialize(page, \"chart7\", ABM.CHART_TYPEL";
_chart7.Initialize(_page,"chart7",_abm.CHART_TYPELINE,_abm.CHART_RATIO_GOLDENSECTION,"");
 //BA.debugLineNum = 428;BA.debugLine="chart7.OptionsLine.FixedHeightPx = 300";
_chart7.OptionsLine().FixedHeightPx = (int) (300);
 //BA.debugLineNum = 429;BA.debugLine="chart7.OptionsLine.AxisYLow=-10";
_chart7.OptionsLine().AxisYLow = (int) (-10);
 //BA.debugLineNum = 430;BA.debugLine="chart7.OptionsLine.AxisYHigh=10";
_chart7.OptionsLine().AxisYHigh = (int) (10);
 //BA.debugLineNum = 431;BA.debugLine="chart7.OptionsLine.AxisYOnlyInteger=True";
_chart7.OptionsLine().AxisYOnlyInteger = __c.True;
 //BA.debugLineNum = 432;BA.debugLine="chart7.OptionsLine.FullWidth=True";
_chart7.OptionsLine().FullWidth = __c.True;
 //BA.debugLineNum = 433;BA.debugLine="chart7.OptionsLine.ChartPaddingRight=60 ' because";
_chart7.OptionsLine().ChartPaddingRight = (int) (60);
 //BA.debugLineNum = 434;BA.debugLine="chart7.OptionsLine.Serie(ABM.CHART_SERIEINDEX_A).";
_chart7.OptionsLine().Serie(_abm.CHART_SERIEINDEX_A).LineSmooth = _abm.CHART_LINESMOOTH_SIMPLE;
 //BA.debugLineNum = 435;BA.debugLine="chart7.OptionsLine.Serie(ABM.CHART_SERIEINDEX_A).";
_chart7.OptionsLine().Serie(_abm.CHART_SERIEINDEX_A).ShowPoint = __c.False;
 //BA.debugLineNum = 437;BA.debugLine="CurrentLabels.addAll(Array As String(\"0\", \"0\", \"0";
_currentlabels.AddAll(anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"0","0","0","0","0","0","0","0","0","0"}));
 //BA.debugLineNum = 438;BA.debugLine="chart7.AddLabels(CurrentLabels)";
_chart7.AddLabels(_currentlabels);
 //BA.debugLineNum = 441;BA.debugLine="CurrentValues.AddAll(Array As Int(0,0,0,0,0,0,0,0";
_currentvalues.AddAll(anywheresoftware.b4a.keywords.Common.ArrayToList(new int[]{(int) (0),(int) (0),(int) (0),(int) (0),(int) (0),(int) (0),(int) (0),(int) (0),(int) (0),(int) (0)}));
 //BA.debugLineNum = 442;BA.debugLine="Dim Serie7A As ABMChartSerie";
_serie7a = new com.ab.abmaterial.ABMChartSerie();
 //BA.debugLineNum = 443;BA.debugLine="Serie7A.InitializeForBar";
_serie7a.InitializeForBar();
 //BA.debugLineNum = 444;BA.debugLine="Serie7A.SetValues(CurrentValues)";
_serie7a.SetValues(_currentvalues);
 //BA.debugLineNum = 445;BA.debugLine="chart7.AddSerie(Serie7A)";
_chart7.AddSerie(_serie7a);
 //BA.debugLineNum = 449;BA.debugLine="page.CellR(1,1).AddComponent(chart7)";
_page.CellR((int) (1),(int) (1)).AddComponent((com.ab.abmaterial.ABMComponent)(_chart7));
 //BA.debugLineNum = 452;BA.debugLine="ABMShared.ConnectFooter(page)";
_abmshared._connectfooter(_page);
 //BA.debugLineNum = 454;BA.debugLine="page.Refresh ' IMPORTANT";
_page.Refresh();
 //BA.debugLineNum = 457;BA.debugLine="page.FinishedLoading 'IMPORTANT";
_page.FinishedLoading();
 //BA.debugLineNum = 459;BA.debugLine="page.RestoreNavigationBarPosition";
_page.RestoreNavigationBarPosition();
 //BA.debugLineNum = 460;BA.debugLine="End Sub";
return "";
}
public String  _initialize(anywheresoftware.b4a.BA _ba) throws Exception{
innerInitialize(_ba);
 //BA.debugLineNum = 25;BA.debugLine="Public Sub Initialize";
 //BA.debugLineNum = 27;BA.debugLine="CurrentLabels.Initialize";
_currentlabels.Initialize();
 //BA.debugLineNum = 28;BA.debugLine="CurrentValues.Initialize";
_currentvalues.Initialize();
 //BA.debugLineNum = 30;BA.debugLine="BuildPage";
_buildpage();
 //BA.debugLineNum = 31;BA.debugLine="End Sub";
return "";
}
public String  _page_navigationbarclicked(String _action,String _value) throws Exception{
 //BA.debugLineNum = 468;BA.debugLine="Sub Page_NavigationbarClicked(Action As String, Va";
 //BA.debugLineNum = 469;BA.debugLine="page.SaveNavigationBarPosition";
_page.SaveNavigationBarPosition();
 //BA.debugLineNum = 470;BA.debugLine="If Action = \"ABMChart\" Then Return";
if ((_action).equals("ABMChart")) { 
if (true) return "";};
 //BA.debugLineNum = 471;BA.debugLine="If Action = \"Contact\" Then";
if ((_action).equals("Contact")) { 
 //BA.debugLineNum = 472;BA.debugLine="myToastId = myToastId + 1";
_mytoastid = (int) (_mytoastid+1);
 //BA.debugLineNum = 473;BA.debugLine="page.ShowToast(\"toast\" & myToastId, \"toastred\",";
_page.ShowToast("toast"+BA.NumberToString(_mytoastid),"toastred","Hello to you too!",(int) (5000));
 //BA.debugLineNum = 474;BA.debugLine="Return";
if (true) return "";
 };
 //BA.debugLineNum = 476;BA.debugLine="If Action = \"LogOff\" Then";
if ((_action).equals("LogOff")) { 
 //BA.debugLineNum = 477;BA.debugLine="ABMShared.LogOff(page)";
_abmshared._logoff(_page);
 //BA.debugLineNum = 478;BA.debugLine="Return";
if (true) return "";
 };
 //BA.debugLineNum = 480;BA.debugLine="ABMShared.NavigateToPage(ws,ABMPageId, Value)";
_abmshared._navigatetopage(_ws,_abmpageid,_value);
 //BA.debugLineNum = 481;BA.debugLine="End Sub";
return "";
}
public String  _page_parseevent(anywheresoftware.b4a.objects.collections.Map _params) throws Exception{
String _eventname = "";
String[] _eventparams = null;
anywheresoftware.b4a.objects.collections.List _passedtables = null;
 //BA.debugLineNum = 69;BA.debugLine="Sub Page_ParseEvent(Params As Map)";
 //BA.debugLineNum = 70;BA.debugLine="Dim eventName As String = Params.Get(\"eventname\")";
_eventname = BA.ObjectToString(_params.Get((Object)("eventname")));
 //BA.debugLineNum = 71;BA.debugLine="Dim eventParams() As String = Regex.Split(\",\",Par";
_eventparams = __c.Regex.Split(",",BA.ObjectToString(_params.Get((Object)("eventparams"))));
 //BA.debugLineNum = 72;BA.debugLine="If eventName = \"beforeunload\" Then";
if ((_eventname).equals("beforeunload")) { 
 //BA.debugLineNum = 73;BA.debugLine="Log(\"preparing for url refresh\")";
__c.Log("preparing for url refresh");
 //BA.debugLineNum = 74;BA.debugLine="ABM.RemoveMeFromCache(ABMShared.CachedPages, ABM";
_abm.RemoveMeFromCache(_abmshared._cachedpages,_abmpageid);
 //BA.debugLineNum = 75;BA.debugLine="Return";
if (true) return "";
 };
 //BA.debugLineNum = 77;BA.debugLine="If SubExists(Me, eventName) Then";
if (__c.SubExists(ba,this,_eventname)) { 
 //BA.debugLineNum = 78;BA.debugLine="Params.Remove(\"eventname\")";
_params.Remove((Object)("eventname"));
 //BA.debugLineNum = 79;BA.debugLine="Params.Remove(\"eventparams\")";
_params.Remove((Object)("eventparams"));
 //BA.debugLineNum = 80;BA.debugLine="Select Case Params.Size";
switch (BA.switchObjectToInt(_params.getSize(),(int) (0),(int) (1),(int) (2))) {
case 0: {
 //BA.debugLineNum = 82;BA.debugLine="CallSub(Me, eventName)";
__c.CallSubNew(ba,this,_eventname);
 break; }
case 1: {
 //BA.debugLineNum = 84;BA.debugLine="CallSub2(Me, eventName, Params.Get(eventParams";
__c.CallSubNew2(ba,this,_eventname,_params.Get((Object)(_eventparams[(int) (0)])));
 break; }
case 2: {
 //BA.debugLineNum = 86;BA.debugLine="If Params.get(eventParams(0)) = \"abmistable\" T";
if ((_params.Get((Object)(_eventparams[(int) (0)]))).equals((Object)("abmistable"))) { 
 //BA.debugLineNum = 87;BA.debugLine="Dim PassedTables As List = ABM.ProcessTablesF";
_passedtables = new anywheresoftware.b4a.objects.collections.List();
_passedtables = _abm.ProcessTablesFromTargetName(BA.ObjectToString(_params.Get((Object)(_eventparams[(int) (1)]))));
 //BA.debugLineNum = 88;BA.debugLine="CallSub2(Me, eventName, PassedTables)";
__c.CallSubNew2(ba,this,_eventname,(Object)(_passedtables));
 }else {
 //BA.debugLineNum = 90;BA.debugLine="CallSub3(Me, eventName, Params.Get(eventParam";
__c.CallSubNew3(ba,this,_eventname,_params.Get((Object)(_eventparams[(int) (0)])),_params.Get((Object)(_eventparams[(int) (1)])));
 };
 break; }
default: {
 //BA.debugLineNum = 94;BA.debugLine="CallSub2(Me, eventName, Params)";
__c.CallSubNew2(ba,this,_eventname,(Object)(_params));
 break; }
}
;
 };
 //BA.debugLineNum = 97;BA.debugLine="End Sub";
return "";
}
public String  _page_signedoffsocialnetwork(String _network,String _extra) throws Exception{
 //BA.debugLineNum = 483;BA.debugLine="Sub Page_SignedOffSocialNetwork(Network As String,";
 //BA.debugLineNum = 484;BA.debugLine="page.ws.Session.SetAttribute(\"authType\", \"\")";
_page.ws.getSession().SetAttribute("authType",(Object)(""));
 //BA.debugLineNum = 485;BA.debugLine="page.ws.Session.SetAttribute(\"authName\", \"\")";
_page.ws.getSession().SetAttribute("authName",(Object)(""));
 //BA.debugLineNum = 486;BA.debugLine="page.ws.Session.SetAttribute(\"IsAuthorized\", \"\")";
_page.ws.getSession().SetAttribute("IsAuthorized",(Object)(""));
 //BA.debugLineNum = 487;BA.debugLine="ABMShared.NavigateToPage(ws,ABMPageId, \"../\")";
_abmshared._navigatetopage(_ws,_abmpageid,"../");
 //BA.debugLineNum = 488;BA.debugLine="End Sub";
return "";
}
public String  _temperaturetimer_tick() throws Exception{
com.ab.abmaterial.ABMChart _chart7 = null;
int _newvalue = 0;
 //BA.debugLineNum = 490;BA.debugLine="Sub TemperatureTimer_Tick";
 //BA.debugLineNum = 491;BA.debugLine="Dim chart7 As ABMChart = page.Component(\"chart7\")";
_chart7 = (com.ab.abmaterial.ABMChart)(_page.Component("chart7"));
 //BA.debugLineNum = 492;BA.debugLine="If chart7 <> Null Then";
if (_chart7!= null) { 
 //BA.debugLineNum = 493;BA.debugLine="CurrentLabels.RemoveAt(0)";
_currentlabels.RemoveAt((int) (0));
 //BA.debugLineNum = 494;BA.debugLine="CurrentValues.RemoveAt(0)";
_currentvalues.RemoveAt((int) (0));
 //BA.debugLineNum = 495;BA.debugLine="Dim newValue As Int = Rnd(-10,11)";
_newvalue = __c.Rnd((int) (-10),(int) (11));
 //BA.debugLineNum = 496;BA.debugLine="CurrentValues.Add(newValue)";
_currentvalues.Add((Object)(_newvalue));
 //BA.debugLineNum = 497;BA.debugLine="CurrentLabels.Add(\"\" & newValue)";
_currentlabels.Add((Object)(""+BA.NumberToString(_newvalue)));
 //BA.debugLineNum = 498;BA.debugLine="chart7.SetLabels(CurrentLabels)";
_chart7.SetLabels(_currentlabels);
 //BA.debugLineNum = 499;BA.debugLine="chart7.GetSerie(ABM.CHART_SERIEINDEX_A).SetValue";
_chart7.GetSerie(_abm.CHART_SERIEINDEX_A).SetValues(_currentvalues);
 //BA.debugLineNum = 500;BA.debugLine="chart7.Refresh";
_chart7.Refresh();
 };
 //BA.debugLineNum = 502;BA.debugLine="End Sub";
return "";
}
public String  _websocket_connected(anywheresoftware.b4j.object.WebSocket _websocket1) throws Exception{
anywheresoftware.b4j.object.HttpSessionWrapper _session = null;
 //BA.debugLineNum = 33;BA.debugLine="Private Sub WebSocket_Connected (WebSocket1 As Web";
 //BA.debugLineNum = 34;BA.debugLine="Log(\"Connected\")";
__c.Log("Connected");
 //BA.debugLineNum = 35;BA.debugLine="ws = WebSocket1";
_ws = _websocket1;
 //BA.debugLineNum = 36;BA.debugLine="ABMPageId = ABM.GetPageID(page, Name,ws)";
_abmpageid = _abm.GetPageID(_page,_name,_ws);
 //BA.debugLineNum = 37;BA.debugLine="Dim session As HttpSession = ABM.GetSession(ws, A";
_session = new anywheresoftware.b4j.object.HttpSessionWrapper();
_session = _abm.GetSession(_ws,_abmshared._sessionmaxinactiveintervalseconds);
 //BA.debugLineNum = 39;BA.debugLine="If ABMShared.NeedsAuthorization Then";
if (_abmshared._needsauthorization) { 
 //BA.debugLineNum = 40;BA.debugLine="If session.GetAttribute2(\"IsAuthorized\", \"\") = \"";
if ((_session.GetAttribute2("IsAuthorized",(Object)(""))).equals((Object)(""))) { 
 //BA.debugLineNum = 41;BA.debugLine="ABMShared.NavigateToPage(ws, ABMPageId,\"../\")";
_abmshared._navigatetopage(_ws,_abmpageid,"../");
 //BA.debugLineNum = 42;BA.debugLine="Return";
if (true) return "";
 };
 };
 //BA.debugLineNum = 46;BA.debugLine="ABM.UpdateFromCache(Me, ABMShared.CachedPages, AB";
_abm.UpdateFromCache((anywheresoftware.b4a.B4AClass)(this),_abmshared._cachedpages,_abmpageid,_ws,ba);
 //BA.debugLineNum = 47;BA.debugLine="If page.ComesFromPageCache Then";
if (_page.ComesFromPageCache) { 
 //BA.debugLineNum = 49;BA.debugLine="page.Refresh";
_page.Refresh();
 //BA.debugLineNum = 51;BA.debugLine="page.FinishedLoading";
_page.FinishedLoading();
 }else {
 //BA.debugLineNum = 54;BA.debugLine="page.Prepare";
_page.Prepare();
 //BA.debugLineNum = 56;BA.debugLine="ConnectPage";
_connectpage();
 };
 //BA.debugLineNum = 58;BA.debugLine="Log(ABMPageId)";
__c.Log(_abmpageid);
 //BA.debugLineNum = 60;BA.debugLine="TemperatureTimer.Initialize(\"TemperatureTimer\", 1";
_temperaturetimer.Initialize(ba,"TemperatureTimer",(long) (1000));
 //BA.debugLineNum = 61;BA.debugLine="TemperatureTimer.Enabled = True";
_temperaturetimer.setEnabled(__c.True);
 //BA.debugLineNum = 62;BA.debugLine="End Sub";
return "";
}
public String  _websocket_disconnected() throws Exception{
 //BA.debugLineNum = 64;BA.debugLine="Private Sub WebSocket_Disconnected";
 //BA.debugLineNum = 65;BA.debugLine="TemperatureTimer.Enabled = False";
_temperaturetimer.setEnabled(__c.False);
 //BA.debugLineNum = 66;BA.debugLine="Log(\"Disconnected\")";
__c.Log("Disconnected");
 //BA.debugLineNum = 67;BA.debugLine="End Sub";
return "";
}
public Object callSub(String sub, Object sender, Object[] args) throws Exception {
BA.senderHolder.set(sender);
return BA.SubDelegator.SubNotFound;
}
}
