package abmaterial.ab.com;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.debug.*;

public class main extends Object{
public static main mostCurrent = new main();

public static BA ba;
static {
		ba = new  anywheresoftware.b4a.StandardBA("abmaterial.ab.com", "abmaterial.ab.com.main", null);
		ba.loadHtSubs(main.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "abmaterial.ab.com.main", ba);
		}
	}
    public static Class<?> getObject() {
		return main.class;
	}

 
    public static void main(String[] args) throws Exception{
        try {
            anywheresoftware.b4a.keywords.Common.LogDebug("Program started.");
            initializeProcessGlobals();
            ba.raiseEvent(null, "appstart", (Object)args);
        } catch (Throwable t) {
			BA.printException(t, true);
		
        } finally {
            anywheresoftware.b4a.keywords.Common.LogDebug("Program terminated (StartMessageLoop was not called).");
        }
    }
public static anywheresoftware.b4a.keywords.Common __c = null;
public static anywheresoftware.b4j.object.ServerWrapper _srvr = null;
public static b4j.example.dateutils _dateutils = null;
public static abmaterial.ab.com.abmshared _abmshared = null;
public static abmaterial.ab.com.abmprint _abmprint = null;
public static String  _appstart(String[] _args) throws Exception{
abmaterial.ab.com.abmapplication _myapp = null;
abmaterial.ab.com.aboutpage _aboutp = null;
abmaterial.ab.com.compactionbuttonpage _compactionbuttonp = null;
abmaterial.ab.com.compaudioplayerpage _compaudioplayerp = null;
abmaterial.ab.com.compbadgepage _compbadgep = null;
abmaterial.ab.com.compbuttonpage _compbuttonp = null;
abmaterial.ab.com.compcalendarpage _compcalp = null;
abmaterial.ab.com.compcanvaspage _compcanvasp = null;
abmaterial.ab.com.compcardpage _compcardp = null;
abmaterial.ab.com.compchartpage _compchartp = null;
abmaterial.ab.com.compchatpage _compchatp = null;
abmaterial.ab.com.compcheckboxpage _compcheckboxp = null;
abmaterial.ab.com.compchippage _compchipp = null;
abmaterial.ab.com.compchronologypage _compchronop = null;
abmaterial.ab.com.compcodelabelpage _compcodelabelp = null;
abmaterial.ab.com.compcombopage _compcombop = null;
abmaterial.ab.com.compcustomcomppage _compcustp = null;
abmaterial.ab.com.compdatetimepickerpage _compdtpickerp = null;
abmaterial.ab.com.compdatetimescrollerpage _compdtscrollerp = null;
abmaterial.ab.com.compdividerpage _compdividerp = null;
abmaterial.ab.com.compeditorpage _compeditorp = null;
abmaterial.ab.com.compfileinputpage _compfileinputp = null;
abmaterial.ab.com.compgooglemappage _compgooglemapp = null;
abmaterial.ab.com.compimagepage _compimagep = null;
abmaterial.ab.com.compinputpage _compinputp = null;
abmaterial.ab.com.complabelpage _complabelp = null;
abmaterial.ab.com.complistpage _complistp = null;
abmaterial.ab.com.compoauthpage _compoauthp = null;
abmaterial.ab.com.comppaginationpage _comppaginationp = null;
abmaterial.ab.com.comppatternlockpage _comppatternlockp = null;
abmaterial.ab.com.comppdfviewerpage _comppdfviewerp = null;
abmaterial.ab.com.comppercentsliderpage _comppercentsliderp = null;
abmaterial.ab.com.comppivottablepage _comppivottablep = null;
abmaterial.ab.com.compplannerpage _compplannerp = null;
abmaterial.ab.com.compradiogrouppage _compradiogroupp = null;
abmaterial.ab.com.comprangepage _comprangep = null;
abmaterial.ab.com.compsignaturepage _compsignaturep = null;
abmaterial.ab.com.comprealsliderpage _comprealsliderp = null;
abmaterial.ab.com.compsliderpage _compsliderp = null;
abmaterial.ab.com.compsocialsharepage _compsocialsharep = null;
abmaterial.ab.com.compsvgsurfacepage _compsvgsurfacep = null;
abmaterial.ab.com.compswitchpage _compswitchp = null;
abmaterial.ab.com.comptimelinepage _comptimelinep = null;
abmaterial.ab.com.comptabspage _comptabsp = null;
abmaterial.ab.com.comptreetablepage _comptreetablep = null;
abmaterial.ab.com.compuploadpage _compuploadp = null;
abmaterial.ab.com.compvideopage _compvideop = null;
abmaterial.ab.com.gettingstartedpage _gettingstartedp = null;
abmaterial.ab.com.gridspage _gridsp = null;
abmaterial.ab.com.helpercontainerpage _helpercontainerp = null;
abmaterial.ab.com.helperflexwallpage _helperflexwallp = null;
abmaterial.ab.com.helpergeneratorpage _helpergeneratorp = null;
abmaterial.ab.com.helpermodalsheetpage _helpermodalsheetp = null;
abmaterial.ab.com.helpernavigationbarpage _helpernavbarp = null;
abmaterial.ab.com.helperpagepage _helperpagep = null;
abmaterial.ab.com.helperparallaxpage _helperparallaxp = null;
abmaterial.ab.com.helpertablepage _helpertablep = null;
abmaterial.ab.com.helpertablemutablepage _helpertablemutablep = null;
abmaterial.ab.com.iconspage _iconsp = null;
abmaterial.ab.com.themespage _themesp = null;
abmaterial.ab.com.otherfirebasepage _otherfirebasep = null;
abmaterial.ab.com.otherfirebasestorpage _otherfirebasestorp = null;
abmaterial.ab.com.donatorsextralibspage _donatorsxtralibsp = null;
abmaterial.ab.com.testpage _testp = null;
 //BA.debugLineNum = 13;BA.debugLine="Sub AppStart (Args() As String)";
 //BA.debugLineNum = 15;BA.debugLine="ABMShared.BuildTheme(\"mytheme\")";
_abmshared._buildtheme("mytheme");
 //BA.debugLineNum = 17;BA.debugLine="ABMShared.NeedsAuthorization = False";
_abmshared._needsauthorization = anywheresoftware.b4a.keywords.Common.False;
 //BA.debugLineNum = 19;BA.debugLine="ABMShared.TrackingID = \"UA-73903814-1\" ' IMPORTAN";
_abmshared._trackingid = "UA-73903814-1";
 //BA.debugLineNum = 22;BA.debugLine="Dim myApp As ABMApplication";
_myapp = new abmaterial.ab.com.abmapplication();
 //BA.debugLineNum = 23;BA.debugLine="myApp.Initialize";
_myapp._initialize(ba);
 //BA.debugLineNum = 26;BA.debugLine="Dim aboutp As AboutPage";
_aboutp = new abmaterial.ab.com.aboutpage();
 //BA.debugLineNum = 27;BA.debugLine="aboutp.Initialize";
_aboutp._initialize(ba);
 //BA.debugLineNum = 29;BA.debugLine="Dim compactionbuttonp As CompActionButtonPage";
_compactionbuttonp = new abmaterial.ab.com.compactionbuttonpage();
 //BA.debugLineNum = 30;BA.debugLine="compactionbuttonp.Initialize";
_compactionbuttonp._initialize(ba);
 //BA.debugLineNum = 32;BA.debugLine="Dim compaudioplayerp As CompAudioPlayerPage";
_compaudioplayerp = new abmaterial.ab.com.compaudioplayerpage();
 //BA.debugLineNum = 33;BA.debugLine="compaudioplayerp.Initialize";
_compaudioplayerp._initialize(ba);
 //BA.debugLineNum = 35;BA.debugLine="Dim compbadgep As CompBadgePage";
_compbadgep = new abmaterial.ab.com.compbadgepage();
 //BA.debugLineNum = 36;BA.debugLine="compbadgep.Initialize";
_compbadgep._initialize(ba);
 //BA.debugLineNum = 38;BA.debugLine="Dim compbuttonp As CompButtonPage";
_compbuttonp = new abmaterial.ab.com.compbuttonpage();
 //BA.debugLineNum = 39;BA.debugLine="compbuttonp.Initialize";
_compbuttonp._initialize(ba);
 //BA.debugLineNum = 41;BA.debugLine="Dim compcalp As CompCalendarPage";
_compcalp = new abmaterial.ab.com.compcalendarpage();
 //BA.debugLineNum = 42;BA.debugLine="compcalp.initialize";
_compcalp._initialize(ba);
 //BA.debugLineNum = 44;BA.debugLine="Dim compcanvasp As CompCanvasPage";
_compcanvasp = new abmaterial.ab.com.compcanvaspage();
 //BA.debugLineNum = 45;BA.debugLine="compcanvasp.Initialize";
_compcanvasp._initialize(ba);
 //BA.debugLineNum = 47;BA.debugLine="Dim compcardp As CompCardPage";
_compcardp = new abmaterial.ab.com.compcardpage();
 //BA.debugLineNum = 48;BA.debugLine="compcardp.Initialize";
_compcardp._initialize(ba);
 //BA.debugLineNum = 50;BA.debugLine="Dim compchartp As CompChartPage";
_compchartp = new abmaterial.ab.com.compchartpage();
 //BA.debugLineNum = 51;BA.debugLine="compchartp.initialize";
_compchartp._initialize(ba);
 //BA.debugLineNum = 53;BA.debugLine="Dim compchatp As CompChatPage";
_compchatp = new abmaterial.ab.com.compchatpage();
 //BA.debugLineNum = 54;BA.debugLine="compchatp.initialize";
_compchatp._initialize(ba);
 //BA.debugLineNum = 56;BA.debugLine="Dim compcheckboxp As CompCheckboxPage";
_compcheckboxp = new abmaterial.ab.com.compcheckboxpage();
 //BA.debugLineNum = 57;BA.debugLine="compcheckboxp.Initialize";
_compcheckboxp._initialize(ba);
 //BA.debugLineNum = 59;BA.debugLine="Dim compchipp As CompChipPage";
_compchipp = new abmaterial.ab.com.compchippage();
 //BA.debugLineNum = 60;BA.debugLine="compchipp.Initialize";
_compchipp._initialize(ba);
 //BA.debugLineNum = 62;BA.debugLine="Dim compchronop As CompChronologyPage";
_compchronop = new abmaterial.ab.com.compchronologypage();
 //BA.debugLineNum = 63;BA.debugLine="compchronop.Initialize";
_compchronop._initialize(ba);
 //BA.debugLineNum = 65;BA.debugLine="Dim compcodelabelp As CompCodeLabelPage";
_compcodelabelp = new abmaterial.ab.com.compcodelabelpage();
 //BA.debugLineNum = 66;BA.debugLine="compcodelabelp.initialize";
_compcodelabelp._initialize(ba);
 //BA.debugLineNum = 68;BA.debugLine="Dim compcombop As CompComboPage";
_compcombop = new abmaterial.ab.com.compcombopage();
 //BA.debugLineNum = 69;BA.debugLine="compcombop.Initialize";
_compcombop._initialize(ba);
 //BA.debugLineNum = 71;BA.debugLine="Dim compcustp As CompCustomCompPage";
_compcustp = new abmaterial.ab.com.compcustomcomppage();
 //BA.debugLineNum = 72;BA.debugLine="compcustp.Initialize";
_compcustp._initialize(ba);
 //BA.debugLineNum = 74;BA.debugLine="Dim compdtpickerp As CompDateTimePickerPage";
_compdtpickerp = new abmaterial.ab.com.compdatetimepickerpage();
 //BA.debugLineNum = 75;BA.debugLine="compdtpickerp.initialize";
_compdtpickerp._initialize(ba);
 //BA.debugLineNum = 77;BA.debugLine="Dim compdtscrollerp As CompDateTimeScrollerPage";
_compdtscrollerp = new abmaterial.ab.com.compdatetimescrollerpage();
 //BA.debugLineNum = 78;BA.debugLine="compdtscrollerp.initialize";
_compdtscrollerp._initialize(ba);
 //BA.debugLineNum = 80;BA.debugLine="Dim compdividerp As CompDividerPage";
_compdividerp = new abmaterial.ab.com.compdividerpage();
 //BA.debugLineNum = 81;BA.debugLine="compdividerp.initialize";
_compdividerp._initialize(ba);
 //BA.debugLineNum = 83;BA.debugLine="Dim compeditorp As CompEditorPage";
_compeditorp = new abmaterial.ab.com.compeditorpage();
 //BA.debugLineNum = 84;BA.debugLine="compeditorp.initialize";
_compeditorp._initialize(ba);
 //BA.debugLineNum = 86;BA.debugLine="Dim compfileinputp As CompFileInputPage";
_compfileinputp = new abmaterial.ab.com.compfileinputpage();
 //BA.debugLineNum = 87;BA.debugLine="compfileinputp.initialize";
_compfileinputp._initialize(ba);
 //BA.debugLineNum = 89;BA.debugLine="Dim compgooglemapp As CompGoogleMapPage";
_compgooglemapp = new abmaterial.ab.com.compgooglemappage();
 //BA.debugLineNum = 90;BA.debugLine="compgooglemapp.Initialize";
_compgooglemapp._initialize(ba);
 //BA.debugLineNum = 92;BA.debugLine="Dim compimagep As CompImagePage";
_compimagep = new abmaterial.ab.com.compimagepage();
 //BA.debugLineNum = 93;BA.debugLine="compimagep.Initialize";
_compimagep._initialize(ba);
 //BA.debugLineNum = 95;BA.debugLine="Dim compinputp As CompInputPage";
_compinputp = new abmaterial.ab.com.compinputpage();
 //BA.debugLineNum = 96;BA.debugLine="compinputp.Initialize";
_compinputp._initialize(ba);
 //BA.debugLineNum = 98;BA.debugLine="Dim complabelp As CompLabelPage";
_complabelp = new abmaterial.ab.com.complabelpage();
 //BA.debugLineNum = 99;BA.debugLine="complabelp.initialize";
_complabelp._initialize(ba);
 //BA.debugLineNum = 101;BA.debugLine="Dim complistp As CompListPage";
_complistp = new abmaterial.ab.com.complistpage();
 //BA.debugLineNum = 102;BA.debugLine="complistp.Initialize";
_complistp._initialize(ba);
 //BA.debugLineNum = 104;BA.debugLine="Dim compoauthp As CompOAuthPage";
_compoauthp = new abmaterial.ab.com.compoauthpage();
 //BA.debugLineNum = 105;BA.debugLine="compoauthp.initialize";
_compoauthp._initialize(ba);
 //BA.debugLineNum = 107;BA.debugLine="Dim comppaginationp As CompPaginationPage";
_comppaginationp = new abmaterial.ab.com.comppaginationpage();
 //BA.debugLineNum = 108;BA.debugLine="comppaginationp.initialize";
_comppaginationp._initialize(ba);
 //BA.debugLineNum = 110;BA.debugLine="Dim comppatternlockp As CompPatternLockPage";
_comppatternlockp = new abmaterial.ab.com.comppatternlockpage();
 //BA.debugLineNum = 111;BA.debugLine="comppatternlockp.initialize";
_comppatternlockp._initialize(ba);
 //BA.debugLineNum = 113;BA.debugLine="Dim comppdfviewerp As CompPDFViewerPage";
_comppdfviewerp = new abmaterial.ab.com.comppdfviewerpage();
 //BA.debugLineNum = 114;BA.debugLine="comppdfviewerp.initialize";
_comppdfviewerp._initialize(ba);
 //BA.debugLineNum = 116;BA.debugLine="Dim comppercentsliderp As CompPercentSliderPage";
_comppercentsliderp = new abmaterial.ab.com.comppercentsliderpage();
 //BA.debugLineNum = 117;BA.debugLine="comppercentsliderp.initialize";
_comppercentsliderp._initialize(ba);
 //BA.debugLineNum = 119;BA.debugLine="Dim comppivottablep As CompPivotTablePage";
_comppivottablep = new abmaterial.ab.com.comppivottablepage();
 //BA.debugLineNum = 120;BA.debugLine="comppivottablep.initialize";
_comppivottablep._initialize(ba);
 //BA.debugLineNum = 122;BA.debugLine="Dim compplannerp As CompPlannerPage";
_compplannerp = new abmaterial.ab.com.compplannerpage();
 //BA.debugLineNum = 123;BA.debugLine="compplannerp.initialize";
_compplannerp._initialize(ba);
 //BA.debugLineNum = 125;BA.debugLine="Dim compradiogroupp As CompRadioGroupPage";
_compradiogroupp = new abmaterial.ab.com.compradiogrouppage();
 //BA.debugLineNum = 126;BA.debugLine="compradiogroupp.Initialize";
_compradiogroupp._initialize(ba);
 //BA.debugLineNum = 128;BA.debugLine="Dim comprangep As CompRangePage";
_comprangep = new abmaterial.ab.com.comprangepage();
 //BA.debugLineNum = 129;BA.debugLine="comprangep.Initialize";
_comprangep._initialize(ba);
 //BA.debugLineNum = 131;BA.debugLine="Dim compsignaturep As CompSignaturePage";
_compsignaturep = new abmaterial.ab.com.compsignaturepage();
 //BA.debugLineNum = 132;BA.debugLine="compsignaturep.initialize";
_compsignaturep._initialize(ba);
 //BA.debugLineNum = 134;BA.debugLine="Dim comprealsliderp As CompRealSliderPage";
_comprealsliderp = new abmaterial.ab.com.comprealsliderpage();
 //BA.debugLineNum = 135;BA.debugLine="comprealsliderp.initialize";
_comprealsliderp._initialize(ba);
 //BA.debugLineNum = 137;BA.debugLine="Dim compsliderp As CompSliderPage";
_compsliderp = new abmaterial.ab.com.compsliderpage();
 //BA.debugLineNum = 138;BA.debugLine="compsliderp.Initialize";
_compsliderp._initialize(ba);
 //BA.debugLineNum = 140;BA.debugLine="Dim compsocialsharep As CompSocialSharePage";
_compsocialsharep = new abmaterial.ab.com.compsocialsharepage();
 //BA.debugLineNum = 141;BA.debugLine="compsocialsharep.Initialize";
_compsocialsharep._initialize(ba);
 //BA.debugLineNum = 143;BA.debugLine="Dim compsvgsurfacep As CompSVGSurfacePage";
_compsvgsurfacep = new abmaterial.ab.com.compsvgsurfacepage();
 //BA.debugLineNum = 144;BA.debugLine="compsvgsurfacep.Initialize";
_compsvgsurfacep._initialize(ba);
 //BA.debugLineNum = 146;BA.debugLine="Dim compswitchp As CompSwitchPage";
_compswitchp = new abmaterial.ab.com.compswitchpage();
 //BA.debugLineNum = 147;BA.debugLine="compswitchp.Initialize";
_compswitchp._initialize(ba);
 //BA.debugLineNum = 149;BA.debugLine="Dim comptimelinep As CompTimeLinePage";
_comptimelinep = new abmaterial.ab.com.comptimelinepage();
 //BA.debugLineNum = 150;BA.debugLine="comptimelinep.Initialize";
_comptimelinep._initialize(ba);
 //BA.debugLineNum = 152;BA.debugLine="Dim comptabsp As CompTabsPage";
_comptabsp = new abmaterial.ab.com.comptabspage();
 //BA.debugLineNum = 153;BA.debugLine="comptabsp.Initialize";
_comptabsp._initialize(ba);
 //BA.debugLineNum = 155;BA.debugLine="Dim comptreetablep As CompTreeTablePage";
_comptreetablep = new abmaterial.ab.com.comptreetablepage();
 //BA.debugLineNum = 156;BA.debugLine="comptreetablep.Initialize";
_comptreetablep._initialize(ba);
 //BA.debugLineNum = 158;BA.debugLine="Dim compuploadp As CompUploadPage";
_compuploadp = new abmaterial.ab.com.compuploadpage();
 //BA.debugLineNum = 159;BA.debugLine="compuploadp.Initialize";
_compuploadp._initialize(ba);
 //BA.debugLineNum = 161;BA.debugLine="Dim compvideop As CompVideoPage";
_compvideop = new abmaterial.ab.com.compvideopage();
 //BA.debugLineNum = 162;BA.debugLine="compvideop.Initialize";
_compvideop._initialize(ba);
 //BA.debugLineNum = 164;BA.debugLine="Dim gettingstartedp As GettingStartedPage";
_gettingstartedp = new abmaterial.ab.com.gettingstartedpage();
 //BA.debugLineNum = 165;BA.debugLine="gettingstartedp.Initialize";
_gettingstartedp._initialize(ba);
 //BA.debugLineNum = 167;BA.debugLine="Dim gridsp As GridsPage";
_gridsp = new abmaterial.ab.com.gridspage();
 //BA.debugLineNum = 168;BA.debugLine="gridsp.Initialize";
_gridsp._initialize(ba);
 //BA.debugLineNum = 170;BA.debugLine="Dim helpercontainerp As HelperContainerPage";
_helpercontainerp = new abmaterial.ab.com.helpercontainerpage();
 //BA.debugLineNum = 171;BA.debugLine="helpercontainerp.initialize";
_helpercontainerp._initialize(ba);
 //BA.debugLineNum = 173;BA.debugLine="Dim helperflexwallp As HelperFlexWallPage";
_helperflexwallp = new abmaterial.ab.com.helperflexwallpage();
 //BA.debugLineNum = 174;BA.debugLine="helperflexwallp.initialize";
_helperflexwallp._initialize(ba);
 //BA.debugLineNum = 176;BA.debugLine="Dim helpergeneratorp As HelperGeneratorPage";
_helpergeneratorp = new abmaterial.ab.com.helpergeneratorpage();
 //BA.debugLineNum = 177;BA.debugLine="helpergeneratorp.initialize";
_helpergeneratorp._initialize(ba);
 //BA.debugLineNum = 179;BA.debugLine="Dim helpermodalsheetp As HelperModalSheetPage";
_helpermodalsheetp = new abmaterial.ab.com.helpermodalsheetpage();
 //BA.debugLineNum = 180;BA.debugLine="helpermodalsheetp.initialize";
_helpermodalsheetp._initialize(ba);
 //BA.debugLineNum = 182;BA.debugLine="Dim helpernavbarp As HelperNavigationBarPage";
_helpernavbarp = new abmaterial.ab.com.helpernavigationbarpage();
 //BA.debugLineNum = 183;BA.debugLine="helpernavbarp.initialize";
_helpernavbarp._initialize(ba);
 //BA.debugLineNum = 185;BA.debugLine="Dim helperpagep As HelperPagePage";
_helperpagep = new abmaterial.ab.com.helperpagepage();
 //BA.debugLineNum = 186;BA.debugLine="helperpagep.initialize";
_helperpagep._initialize(ba);
 //BA.debugLineNum = 188;BA.debugLine="Dim helperparallaxp As HelperParallaxPage";
_helperparallaxp = new abmaterial.ab.com.helperparallaxpage();
 //BA.debugLineNum = 189;BA.debugLine="helperparallaxp.Initialize";
_helperparallaxp._initialize(ba);
 //BA.debugLineNum = 191;BA.debugLine="Dim helpertablep As HelperTablePage";
_helpertablep = new abmaterial.ab.com.helpertablepage();
 //BA.debugLineNum = 192;BA.debugLine="helpertablep.Initialize";
_helpertablep._initialize(ba);
 //BA.debugLineNum = 194;BA.debugLine="Dim helpertablemutablep As HelperTableMutablePage";
_helpertablemutablep = new abmaterial.ab.com.helpertablemutablepage();
 //BA.debugLineNum = 195;BA.debugLine="helpertablemutablep.Initialize";
_helpertablemutablep._initialize(ba);
 //BA.debugLineNum = 197;BA.debugLine="Dim iconsp As IconsPage";
_iconsp = new abmaterial.ab.com.iconspage();
 //BA.debugLineNum = 198;BA.debugLine="iconsp.initialize";
_iconsp._initialize(ba);
 //BA.debugLineNum = 200;BA.debugLine="Dim themesp As ThemesPage";
_themesp = new abmaterial.ab.com.themespage();
 //BA.debugLineNum = 201;BA.debugLine="themesp.initialize";
_themesp._initialize(ba);
 //BA.debugLineNum = 203;BA.debugLine="Dim otherfirebasep As OtherFirebasePage";
_otherfirebasep = new abmaterial.ab.com.otherfirebasepage();
 //BA.debugLineNum = 204;BA.debugLine="otherfirebasep.initialize";
_otherfirebasep._initialize(ba);
 //BA.debugLineNum = 206;BA.debugLine="Dim otherfirebasestorp As OtherFirebaseStorPage";
_otherfirebasestorp = new abmaterial.ab.com.otherfirebasestorpage();
 //BA.debugLineNum = 207;BA.debugLine="otherfirebasestorp.initialize";
_otherfirebasestorp._initialize(ba);
 //BA.debugLineNum = 209;BA.debugLine="Dim donatorsxtralibsp As DonatorsExtraLibsPage";
_donatorsxtralibsp = new abmaterial.ab.com.donatorsextralibspage();
 //BA.debugLineNum = 210;BA.debugLine="donatorsxtralibsp.initialize";
_donatorsxtralibsp._initialize(ba);
 //BA.debugLineNum = 212;BA.debugLine="Dim testp As TestPage";
_testp = new abmaterial.ab.com.testpage();
 //BA.debugLineNum = 213;BA.debugLine="testp.initialize";
_testp._initialize(ba);
 //BA.debugLineNum = 217;BA.debugLine="myApp.AddPage(aboutp.Page)";
_myapp._addpage(_aboutp._page);
 //BA.debugLineNum = 218;BA.debugLine="myApp.AddPage(compactionbuttonp.Page)";
_myapp._addpage(_compactionbuttonp._page);
 //BA.debugLineNum = 219;BA.debugLine="myApp.AddPage(compaudioplayerp.Page)";
_myapp._addpage(_compaudioplayerp._page);
 //BA.debugLineNum = 220;BA.debugLine="myApp.AddPage(compbadgep.Page)";
_myapp._addpage(_compbadgep._page);
 //BA.debugLineNum = 221;BA.debugLine="myApp.AddPage(compbuttonp.Page)";
_myapp._addpage(_compbuttonp._page);
 //BA.debugLineNum = 222;BA.debugLine="myApp.AddPage(compcalp.Page)";
_myapp._addpage(_compcalp._page);
 //BA.debugLineNum = 223;BA.debugLine="myApp.AddPage(compcanvasp.Page)";
_myapp._addpage(_compcanvasp._page);
 //BA.debugLineNum = 224;BA.debugLine="myApp.AddPage(compcardp.Page)";
_myapp._addpage(_compcardp._page);
 //BA.debugLineNum = 225;BA.debugLine="myApp.AddPage(compchartp.Page)";
_myapp._addpage(_compchartp._page);
 //BA.debugLineNum = 226;BA.debugLine="myApp.AddPage(compchatp.Page)";
_myapp._addpage(_compchatp._page);
 //BA.debugLineNum = 227;BA.debugLine="myApp.AddPage(compcheckboxp.Page)";
_myapp._addpage(_compcheckboxp._page);
 //BA.debugLineNum = 228;BA.debugLine="myApp.AddPage(compchipp.Page)";
_myapp._addpage(_compchipp._page);
 //BA.debugLineNum = 229;BA.debugLine="myApp.AddPage(compchronop.Page)";
_myapp._addpage(_compchronop._page);
 //BA.debugLineNum = 230;BA.debugLine="myApp.AddPage(compcodelabelp.Page)";
_myapp._addpage(_compcodelabelp._page);
 //BA.debugLineNum = 231;BA.debugLine="myApp.AddPage(compcombop.Page)";
_myapp._addpage(_compcombop._page);
 //BA.debugLineNum = 232;BA.debugLine="myApp.AddPage(compcustp.Page)";
_myapp._addpage(_compcustp._page);
 //BA.debugLineNum = 233;BA.debugLine="myApp.AddPage(compdtpickerp.Page)";
_myapp._addpage(_compdtpickerp._page);
 //BA.debugLineNum = 234;BA.debugLine="myApp.AddPage(compdtscrollerp.Page)";
_myapp._addpage(_compdtscrollerp._page);
 //BA.debugLineNum = 235;BA.debugLine="myApp.AddPage(compdividerp.Page)";
_myapp._addpage(_compdividerp._page);
 //BA.debugLineNum = 236;BA.debugLine="myApp.AddPage(compeditorp.Page)";
_myapp._addpage(_compeditorp._page);
 //BA.debugLineNum = 237;BA.debugLine="myApp.AddPage(compfileinputp.Page)";
_myapp._addpage(_compfileinputp._page);
 //BA.debugLineNum = 238;BA.debugLine="myApp.AddPage(compgooglemapp.Page)";
_myapp._addpage(_compgooglemapp._page);
 //BA.debugLineNum = 239;BA.debugLine="myApp.AddPage(compimagep.Page)";
_myapp._addpage(_compimagep._page);
 //BA.debugLineNum = 240;BA.debugLine="myApp.AddPage(compinputp.Page)";
_myapp._addpage(_compinputp._page);
 //BA.debugLineNum = 241;BA.debugLine="myApp.AddPage(complabelp.Page)";
_myapp._addpage(_complabelp._page);
 //BA.debugLineNum = 242;BA.debugLine="myApp.AddPage(complistp.Page)";
_myapp._addpage(_complistp._page);
 //BA.debugLineNum = 243;BA.debugLine="myApp.AddPage(compoauthp.Page)";
_myapp._addpage(_compoauthp._page);
 //BA.debugLineNum = 244;BA.debugLine="myApp.AddPage(comppaginationp.Page)";
_myapp._addpage(_comppaginationp._page);
 //BA.debugLineNum = 245;BA.debugLine="myApp.AddPage(comppatternlockp.Page)";
_myapp._addpage(_comppatternlockp._page);
 //BA.debugLineNum = 246;BA.debugLine="myApp.AddPage(comppdfviewerp.Page)";
_myapp._addpage(_comppdfviewerp._page);
 //BA.debugLineNum = 247;BA.debugLine="myApp.AddPage(comppercentsliderp.Page)";
_myapp._addpage(_comppercentsliderp._page);
 //BA.debugLineNum = 248;BA.debugLine="myApp.AddPage(comppivottablep.Page)";
_myapp._addpage(_comppivottablep._page);
 //BA.debugLineNum = 249;BA.debugLine="myApp.AddPage(compplannerp.Page)";
_myapp._addpage(_compplannerp._page);
 //BA.debugLineNum = 250;BA.debugLine="myApp.AddPage(compradiogroupp.Page)";
_myapp._addpage(_compradiogroupp._page);
 //BA.debugLineNum = 251;BA.debugLine="myApp.AddPage(comprangep.Page)";
_myapp._addpage(_comprangep._page);
 //BA.debugLineNum = 252;BA.debugLine="myApp.AddPage(compsignaturep.Page)";
_myapp._addpage(_compsignaturep._page);
 //BA.debugLineNum = 253;BA.debugLine="myApp.AddPage(comprealsliderp.Page)";
_myapp._addpage(_comprealsliderp._page);
 //BA.debugLineNum = 254;BA.debugLine="myApp.AddPage(compsliderp.Page)";
_myapp._addpage(_compsliderp._page);
 //BA.debugLineNum = 255;BA.debugLine="myApp.AddPage(compsocialsharep.Page)";
_myapp._addpage(_compsocialsharep._page);
 //BA.debugLineNum = 256;BA.debugLine="myApp.AddPage(compsvgsurfacep.Page)";
_myapp._addpage(_compsvgsurfacep._page);
 //BA.debugLineNum = 257;BA.debugLine="myApp.AddPage(compswitchp.Page)";
_myapp._addpage(_compswitchp._page);
 //BA.debugLineNum = 258;BA.debugLine="myApp.AddPage(comptreetablep.Page)";
_myapp._addpage(_comptreetablep._page);
 //BA.debugLineNum = 259;BA.debugLine="myApp.AddPage(comptabsp.Page)";
_myapp._addpage(_comptabsp._page);
 //BA.debugLineNum = 260;BA.debugLine="myApp.AddPage(comptimelinep.Page)";
_myapp._addpage(_comptimelinep._page);
 //BA.debugLineNum = 261;BA.debugLine="myApp.AddPage(compuploadp.Page)";
_myapp._addpage(_compuploadp._page);
 //BA.debugLineNum = 262;BA.debugLine="myApp.AddPage(compvideop.Page)";
_myapp._addpage(_compvideop._page);
 //BA.debugLineNum = 263;BA.debugLine="myApp.AddPage(gettingstartedp.Page)";
_myapp._addpage(_gettingstartedp._page);
 //BA.debugLineNum = 264;BA.debugLine="myApp.AddPage(gridsp.Page)";
_myapp._addpage(_gridsp._page);
 //BA.debugLineNum = 265;BA.debugLine="myApp.AddPage(helpercontainerp.Page)";
_myapp._addpage(_helpercontainerp._page);
 //BA.debugLineNum = 266;BA.debugLine="myApp.AddPage(helperflexwallp.Page)";
_myapp._addpage(_helperflexwallp._page);
 //BA.debugLineNum = 267;BA.debugLine="myApp.AddPage(helpergeneratorp.Page)";
_myapp._addpage(_helpergeneratorp._page);
 //BA.debugLineNum = 268;BA.debugLine="myApp.AddPage(helpermodalsheetp.Page)";
_myapp._addpage(_helpermodalsheetp._page);
 //BA.debugLineNum = 269;BA.debugLine="myApp.AddPage(helpernavbarp.Page)";
_myapp._addpage(_helpernavbarp._page);
 //BA.debugLineNum = 270;BA.debugLine="myApp.AddPage(helperpagep.Page)";
_myapp._addpage(_helperpagep._page);
 //BA.debugLineNum = 271;BA.debugLine="myApp.AddPage(helperparallaxp.Page)";
_myapp._addpage(_helperparallaxp._page);
 //BA.debugLineNum = 272;BA.debugLine="myApp.AddPage(helpertablep.Page)";
_myapp._addpage(_helpertablep._page);
 //BA.debugLineNum = 273;BA.debugLine="myApp.AddPage(helpertablemutablep.Page)";
_myapp._addpage(_helpertablemutablep._page);
 //BA.debugLineNum = 274;BA.debugLine="myApp.AddPage(iconsp.Page)";
_myapp._addpage(_iconsp._page);
 //BA.debugLineNum = 275;BA.debugLine="myApp.AddPage(themesp.Page)";
_myapp._addpage(_themesp._page);
 //BA.debugLineNum = 277;BA.debugLine="myApp.AddPage(otherfirebasep.Page)";
_myapp._addpage(_otherfirebasep._page);
 //BA.debugLineNum = 278;BA.debugLine="myApp.AddPage(otherfirebasestorp.Page)";
_myapp._addpage(_otherfirebasestorp._page);
 //BA.debugLineNum = 280;BA.debugLine="myApp.AddPage(donatorsxtralibsp.Page)";
_myapp._addpage(_donatorsxtralibsp._page);
 //BA.debugLineNum = 282;BA.debugLine="myApp.AddPage(testp.Page)";
_myapp._addpage(_testp._page);
 //BA.debugLineNum = 285;BA.debugLine="myApp.StartServer(srvr, \"srvr\", 51042)";
_myapp._startserver(_srvr,"srvr",(int) (51042));
 //BA.debugLineNum = 290;BA.debugLine="ABMShared.RedirectOutput(File.DirApp, \"logs.txt\")";
_abmshared._redirectoutput(anywheresoftware.b4a.keywords.Common.File.getDirApp(),"logs.txt");
 //BA.debugLineNum = 292;BA.debugLine="StartMessageLoop";
anywheresoftware.b4a.keywords.Common.StartMessageLoop(ba);
 //BA.debugLineNum = 293;BA.debugLine="End Sub";
return "";
}

private static boolean processGlobalsRun;
public static void initializeProcessGlobals() {
    
    if (main.processGlobalsRun == false) {
	    main.processGlobalsRun = true;
		try {
		        b4j.example.dateutils._process_globals();
main._process_globals();
abmshared._process_globals();
abmprint._process_globals();
		
        } catch (Exception e) {
			throw new RuntimeException(e);
		}
    }
}public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 9;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 10;BA.debugLine="Public srvr As Server";
_srvr = new anywheresoftware.b4j.object.ServerWrapper();
 //BA.debugLineNum = 11;BA.debugLine="End Sub";
return "";
}
}
